### ISSUE TITLE
 I cannot restrict public access to my ntfy docker instance.

### ISSUE THREAD

**Issue by nikolaos83** [binwiederhier/ntfy#1023]
I'm not sure if this is a bug or I'm doing something dumb but I cannot restrict public access to my ntfy docker instance.

I tried passing the NTFY_AUTH_DEFAULT_ACCESS: deny-all as an environment variable. I tried editing the server.yml. Nothing works. I checked my edits in the container, they are there but the server somehow doesn't restrict access to the public.

I'll restrict public access using a VPN for now but I'd really like to understand what's going on.

**Comment by wunter8** [comment]
The Discord channel is better for troubleshooting issues like this

**Comment by wunter8** [comment]
Does this FAQ answer your question, though? https://docs.ntfy.sh/faq/#can-i-disable-the-web-app-can-i-protect-it-with-a-login-screen

**Comment by nikolaos83** [comment]
Oh? Yes, that surely answers my concerns. I had just deployed ntfy and never had time to understand how it worked.

Thank you!
