### ISSUE TITLE
base-url isn't respected

### ISSUE THREAD

**Issue by rayslinky** [binwiederhier/ntfy#1026]
:lady_beetle: **Describe the bug**
I try to set my baseurl to something with a path, ie: https://example.com/ntfy, requests still go to:
/static/css/app.css
/static/css/fonts.css
/config.js [instead of /ntfy/config.js]

:computer: **Components impacted**
ntfy server

**Comment by wunter8** [comment]
ntfy needs to be served from the root path of a domain (usually a sub domain). Running ntfy at /ntfy isn't supported right now. See https://github.com/binwiederhier/ntfy/issues/398

**Comment by eeuak** [comment]
@wunter8 is it supported to add a port like https://example.com:1234 as the base-url?

**Comment by wunter8** [comment]
@eeuak Yes! Adding a port is fine!
