### ISSUE TITLE
provide a systemd unit file to run the ntfy server as a systemd service

### ISSUE THREAD

**Issue by tgy** [binwiederhier/ntfy#1037]
I think it would be nice if a systemd unit file was provided within this repository to run the ntfy server as a service within a systemd-based system.

In particular, it would be nice if this systemd unit was included within the AUR ntfy package.

One would then just have to type two commands to install and run ntfy on a Arch Linux machine:

```
yay -S ntfy
sudo systemctl start ntfy
```

**Comment by wunter8** [comment]
Here you go! (It's included in the debian package right now. I'm not sure what it would take to add it to the AUR package)

https://github.com/binwiederhier/ntfy/blob/main/server/ntfy.service

**Comment by tgy** [comment]
Ah great! Thanks :) Should have looked more closely!

**Comment by tgy** [comment]
Actually the unit file is already shipped with AUR package. Sorry for the useless issue.
