### ISSUE TITLE
FluffyChat issues on private server

### ISSUE THREAD

**Issue by thefeiter** [binwiederhier/ntfy#107]
I am running a private server behind a traefik instance.

When registering Ntfy as distributor for FluffyChat I am getting the following error:

`HTTP GET /_matrix/push/v1/notify - 404 - 40401 - page not found`

Is there anything that has to be configured for this setup to work?

**Comment by binwiederhier** [comment]
I have seen these 404s on ntfy.sh too, and I am not entirely sure why it's calling this endpoint. Maybe @karmanyaahm or @S1m would be better suited to answer.

**Comment by karmanyaahm** [comment]
Fluffychat checks if the UP server has a matrix gateway. If there's a 404, it uses the default  matrix.gateway.unifiedpush.org. This is expected and totally fine

**Comment by thefeiter** [comment]
Ok, i just noticed, that it seems to be working anyways. Great.

Can you maybe explain, what the matrix gateway doesor what it is for?

**Comment by karmanyaahm** [comment]
The matrix gateway converts the matrix format of push notifications into the UnifiedPush format of push notifications
