### ISSUE TITLE
Feature Request: log rotation

### ISSUE THREAD

**Issue by ksurl** [binwiederhier/ntfy#1074]
:bulb: **Idea**

current log file grows unchecked. add log rotation 

:computer: **Target components**

server side log rotation using something like https://github.com/natefinch/lumberjack

**Comment by binwiederhier** [comment]
As discussed on Discord: 
> Log rotation is really not a thing the app should do itself. logrotate is standard on every Linux system, and if you run in systemd then journalctl will do it for ya.
