### ISSUE TITLE
Poblem with updating notifications in the iOS app ntfy 1.3

### ISSUE THREAD

**Issue by viniciussgoncalves** [binwiederhier/ntfy#1079]
:lady_beetle: **Describe the bug**
I'm having trouble receiving notification updates in my app. I'm able to send and receive messages from my ntfy app on my iphone, but I have to keep refreshing the topic for the messages to be updated. I've cleared all the permissions for the app on iOS and I still can't receive the messages.

:computer: **Components impacted**
Own ntfy server, Iphone 15 iOS 17.3.1, app version 1.3 (4)

:crystal_ball: **Additional context**
The problem does not occur when I use my second Android smartphone. I don't have to keep refreshing the topic to receive or send messages and I don't have a problem receiving messages on the smartphone's notification screen.

**Comment by wunter8** [comment]
To get notifications working on iOS, you need to:
1) make sure `upstream-base-url` is set to "https://ntfy.sh"
2) make sure `base-url` is set to your full domain, including "https://" and without a trailing slash (e.g., `https://ntfy.domain.com`)
3) make sure the default server URL in the iOS app is set to your full domain, I including "https://" and without a trailing slash (it has to exactly match the `base-url`)

**Comment by viniciussgoncalves** [comment]
> To get notifications working on iOS, you need to:
> 
> 1. make sure `upstream-base-url` is set to "https://ntfy.sh"
> 2. make sure `base-url` is set to your full domain, including "https://" and without a trailing slash (e.g., `https://ntfy.domain.com`)
> 3. make sure the default server URL in the iOS app is set to your full domain, I including "https://" and without a trailing slash (it has to exactly match the `base-url`)

Thank you very much! I ended up getting excited when installing and didn't even see this part of the docs. It worked now wunter8.

**Comment by adebisi-fa** [comment]
> To get notifications working on iOS, you need to:
. . .
> 
>     3. make sure the default server URL in the iOS app is set to your full domain, I including "https://" and without a trailing slash (it has to exactly match the `base-url`)

Will things still work if a device subscribes to a topic on a custom domain while the default server URL is still set to https://ntfy.sh?

**Comment by wunter8** [comment]
@adebisi-fa I think that will work fine as long as you set the server for that topic to "your full domain, including "https://" and without a trailing slash (it has to exactly match the `base-url`)"
