### ISSUE TITLE
refactor http Handling

### ISSUE THREAD

**Issue by genofire** [binwiederhier/ntfy#108]
Please use switch instatt of a list of `else if`:
https://github.com/binwiederhier/ntfy/blob/c83b5c6e73c6b386b83a63a77704d8e40fb45df3/server/server.go#L314

Example with expression in `case`:
```golang
    // doesn't have an expression after switch
    switch {  
        case v == "Rob":         // check the case here
        fmt.Println("Hi, Rob!")
        default:
        fmt.Println("Hi, user!")
    }
```

---

Otherwise there are routing libraries out there, and ways: https://benhoyt.com/writings/go-routing/

I love [gin-gonic](https://gin-gonic.com/) not here meanthan

**Comment by binwiederhier** [comment]
It's funny I read the post you linked before, and I chose not to do any of them. I have read and kept up with routers a lot and I think they just don't add enough value to bring them in. 

As for the switch case; isn't that just a personal preference?

**Comment by genofire** [comment]
personal preference if you call it that way ....

source code should be readable and therefore `switch` was designed ...

normally switch is optimized by compiler for runtime, but i believe that is not possible in a expression in case way.

**Comment by genofire** [comment]
You are already using an Http-Router:
https://github.com/binwiederhier/ntfy/blob/c83b5c6e73c6b386b83a63a77704d8e40fb45df3/server/server.go#L232-L238

maybe you should rename :
https://github.com/binwiederhier/ntfy/blob/c83b5c6e73c6b386b83a63a77704d8e40fb45df3/server/server.go#L296 
to `func (s *Server) ServeHTTP(w ResponseWriter, r *Request)` and direct use it. 

And put it `s` here instatt of `mux`:
https://github.com/binwiederhier/ntfy/blob/c83b5c6e73c6b386b83a63a77704d8e40fb45df3/server/server.go#L238

**Comment by binwiederhier** [comment]
>  to func (s *Server) ServeHTTP(w ResponseWriter, r *Request) and direct use it.

That would expose the ServeHTTP method to the outside, which I did not want. 

Overall I am quite happy with the HTTP routing handling. I like the if/then/else the way it is. I may adjust it a little if it gets too unwieldy in the future but for now I think this is fine. 

Thanks for the suggestion though. Keep them coming!
