### ISSUE TITLE
`ntfy sub --from-config` won't receive messages until self-hosted ntfy server (Docker) is restarted or stopped

### ISSUE THREAD

**Issue by afunworm** [binwiederhier/ntfy#1081]
This is the discovery I made follow some attempts for #1076.

:lady_beetle: **Describe the bug**

**Demonstration videos below**
Let's call Server the machine hosting the ntfy server through Docker.
Let's call Client the machine hosting ntfy through Docker, but is only used for the docker CLI.
Let's call the topic `clitest`.

On machine A, run `ntfy sub --from-config`.
Using any method, publish a message to `clitest`. Supposedly, Client should output the receipt of the message sent to Server. However, this doesn't happen *until* the Docker container on Server is stopped.

This won't happen when using to the official https://ntfy.sh server instead of the self-hosted ntfy server.

:computer: **Components impacted**

ntfy CLI or ntfy Server. Both run on Ubuntu 22.04, through Docker Engine.

:bulb: **Screenshots and/or logs**
Testing with self-hosted server: https://streamable.com/7fx5f2
Testing with ntfy.sh: https://streamable.com/7s4oy7

**Comment by afunworm** [comment]
> This is the discovery I made follow some attempts for #1076.
> 
> 🐞 **Describe the bug**
> 
> **Demonstration videos below** Let's call Server the machine hosting the ntfy server through Docker. Let's call Client the machine hosting ntfy through Docker, but is only used for the docker CLI. Let's call the topic `clitest`.
> 
> On machine A, run `ntfy sub --from-config`. Using any method, publish a message to `clitest`. Supposedly, Client should output the receipt of the message sent to Server. However, this doesn't happen _until_ the Docker container on Server is stopped.
> 
> This won't happen when using to the official https://ntfy.sh server instead of the self-hosted ntfy server.
> 
> 💻 **Components impacted**
> 
> ntfy CLI or ntfy Server. Both run on Ubuntu 22.04, through Docker Engine.
> 
> 💡 **Screenshots and/or logs** Testing with self-hosted server: https://streamable.com/7fx5f2 Testing with ntfy.sh: https://streamable.com/7s4oy7

I did some more digging and it seems like it has to do with the server. I wrote a small script to subscribe to SSE from a topic from a self-hosted server, it wouldn't work. When I switched back to ntfy.sh, it works. Here's the script.

```js
const EventSource = require("eventsource");

const evtSource = new EventSource(
        /* This self-hosted server won't work */
	"https://ntfy.byh.uy/clitest/sse?auth=<auth_token_goes_here>"

        /* But the official server will work flawlessly */
	// "https://ntfy.sh/clitest/sse?auth=<auth_token_goes_here>"
);

evtSource.onmessage = function (e) {
	let data = JSON.parse(e.data);
	console.log(data);
};
```

With that said, it seems like the stream isn't working properly. Is there anything I can do to diagnose this?

**Comment by wunter8** [comment]
I was able to test this tonight. I have one container running `ntfy serve`, another container running `ntfy sub --from-config`, and a third container running `ntfy pub`. Everything worked fine for me (e.g., ntfy sub ran the correct command without me needing to kill the server container first).

So maybe there is a problem with nginx proxy manager? Or like you said, something with SSL/TLS?

**Comment by wunter8** [comment]
Did you determine the source of the problem?

**Comment by afunworm** [comment]
> Did you determine the source of the problem?

I didn't. I just settled to use `http` and called it a day. If you are not able to replicate it, it feels like it's more of my responsibility. Nginx Proxy Manager shows no error either.

**Comment by theatischbein** [comment]
I had the same problem and find a solution and wanted to share this here if anyone else stumble upon this error!

My ntfy server is behind a nginx reverse proxy and was missing configurations.
I followed https://docs.ntfy.sh/config/#behind-a-proxy-tls-etc and added:
```
    proxy_http_version 1.1;

    proxy_buffering off;
    proxy_request_buffering off;
    proxy_redirect off;

    proxy_set_header Host $http_host;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    proxy_connect_timeout 3m;
    proxy_send_timeout 3m;
    proxy_read_timeout 3m;

    client_max_body_size 0; # Stream request body to backend
```

Afterwards everything works fine!
