### ISSUE TITLE
refactoring message receive handling

### ISSUE THREAD

**Issue by genofire** [binwiederhier/ntfy#109]
The parsing of an message and delivery (into SMTP and so on) should be split into two functions:

https://github.com/binwiederhier/ntfy/blob/c83b5c6e73c6b386b83a63a77704d8e40fb45df3/server/server.go#L411

Otherwise a handling of multiple message (a batch of message) in one request is not possible like needed here: #104

**Comment by genofire** [comment]
This Workaround over sending an Request should also be solved with it:

https://github.com/binwiederhier/ntfy/blob/c83b5c6e73c6b386b83a63a77704d8e40fb45df3/server/server.go#L1005-L1013

**Comment by binwiederhier** [comment]
I think I'll figure out how to structure the code when/if I do #104. Than you for your feedback though. Much appreciated, keep it coming.
