### ISSUE TITLE
`click`/`x-click` header support for iOS

### ISSUE THREAD

**Issue by brian6932** [binwiederhier/ntfy#1093]
:bulb: **Idea**

When a notification that has a `click`/`x-click` header associated with it, or if you click the entry within the topic in the app, the click action should either open the link in the header, or a button should be included that opens the header link. Anyone coming from PushBullet would like this.
:computer: **Target components**

iOS app

**Comment by binwiederhier** [comment]
It does that. If tap on the notification it'll open the click link. That's literally what it's for.

**Comment by brian6932** [comment]
My bad, it does work on Android, it doesn't seem to work for me on iOS though

**Comment by brian6932** [comment]
Closed in favor of #586 (duplicate)
