### ISSUE TITLE
ntfy.sh currently down

### ISSUE THREAD

**Issue by micseydel** [binwiederhier/ntfy#1094]
I know that it was up 14 hours ago and by 15 minutes ago it was down. I love ntfy and haven't got a local instance going yet but wanted to let the dev(s) know.

**Comment by binwiederhier** [comment]
Thank you @micseydel for letting me know. I have a lot of alerting and monitoring around ntfy so I was well aware. I was fighting issues all day, and will have to do a lot of work to scale ntfy further. Read more on Discord - https://discord.com/invite/cT7ECsZj9w
