### ISSUE TITLE
Make link (from click parameter) also available in the notification list

### ISSUE THREAD

**Issue by cmeis** [binwiederhier/ntfy#110]
The link from a "Click:" header in a notification can only be opened by clicking the Android notification right now.
It would be handy to be able to open is also from the notification list in the app (in case the notification has been dismissed and the link is needed again).

**Comment by binwiederhier** [comment]
Working on this now. On the fence about whether to put the click target in the drop-down menu or the copy action.

Probably the copy action, since you specifically set Click

**Comment by binwiederhier** [comment]
Done. Will be in next release.
