### ISSUE TITLE
Unified Push (Matrix / Element) not working correctly

### ISSUE THREAD

**Issue by Error00101** [binwiederhier/ntfy#1102]
:lady_beetle: **Describe the bug**

I selfhost ntfy and a Matrix Synapse and i want to recive notifications via ntfy.
Inside the Element app i added the notification service (working just fine)
When trying to check for Problems it doesnt find any.

The ntfy app does show the im.vector.app (unified push)
But when clicking on it i only can change the name of the topic or copy the theme url.

Matrix lists an 200 success Message & my ntfy server does recive something!
When following the up* topic for the Matrix notifications i get an unformated message.

:computer: **Components impacted**

- Matrix Synapse (Docker - Synapse / 1.105.1)
- ntfy Server (Docker  - ntfy / v2.10.0)
- Android (ntfy 1.16.0 - fdroid) - not recieving anything for unified push
- Desktop (Firefox 125.0.3) - showing the unformated message 

❓ **What i think should happen**
A well formated message should be recived by all subscibed devices

:bulb: **Screenshots and/or logs**

[combined_logs.log](https://github.com/binwiederhier/ntfy/files/15203226/combined_logs.log)
<details>
<summary>A few screenshots i made</summary>
<li>1</li> How the Message shows inside the Webbrowser

![WebBrowser_Message](https://github.com/binwiederhier/ntfy/assets/54121491/85505f6e-9e3c-40d4-abc6-58124bfd1342)
<li>2</li> "Startscreen" of ntfy

![ntfy_app_startscreen](https://github.com/binwiederhier/ntfy/assets/54121491/f0c183c0-5ca5-4919-bdda-b0685155bc4a)
<li>3</li> What it shows when clicking on the up* tab

![clicking_on_the_uppusher](https://github.com/binwiederhier/ntfy/assets/54121491/e143806e-a662-4b96-8bba-663ed23d9508)
<li>3</li> The Matrix Test

![element_matrixTest](https://github.com/binwiederhier/ntfy/assets/54121491/450f815c-fbb2-403c-bb46-f4a3eac4bc91)

</details>

:crystal_ball: **Additional context**

Other Pushers work just fine on any platform: skripts/uptime kuma/... - Web/Android
I have whitelisted the up* for any user

Did I do something wrong?

**Comment by wunter8** [comment]
It looks like everything is hooked up correctly. The unformatted messages seen in the web app are to be expected (you're not supposed to look at that topic manually). ntfy sends the notifications to Element Android behind the scenes, and Element Android will format them into a proper notification.

The Element Android notification troubleshooter shows that the "Push Test" passed. Did any notification pop up during the test? Do you have the notifications enabled for the Element app in Android settings?

**Comment by Error00101** [comment]
Thank you for the response.
A notification did show up from Element. (it does even recive the callback from the click on it)
I did expect a ntfy notification to pop up.
