### ISSUE TITLE
Acknowledging a notification on the web interface does not extend to the Android app

### ISSUE THREAD

**Issue by wsw70** [binwiederhier/ntfy#1103]
:question: **Question**

When I acknowledge a notification on the web interface, it is not acknowledged on the Android app (and vice-versa). Is this normal and expected?

- If this is not normal (= one ack should do it for all devices) → is there a specific thing that needs to be open between the devices (I do not think so, I am asking just in case -- they all ultimately point to the same instance)
- If this is normal → I will raise a feature idea :)

**Comment by wunter8** [comment]
This is the expected behavior right now. There have been discussions about implementing sync across devices, but it hasn't been implemented yet (and there's no estimated timeline)

**Comment by wunter8** [comment]
Haha, yes, "ntfy (pronounced notify) is a simple HTTP-based [pub-sub](https://en.wikipedia.org/wiki/Publish%E2%80%93subscribe_pattern) notification service" (from the first line of the website)

Right now, subscribed topics can be synced across instances of the web app (so if you subscribe to a topic on your desktop in the web app, the web app on your laptop will also subscribe to that topic). That is done using a special "sync" topic in the background. I presume message syncing will work similarly

**Comment by wsw70** [comment]
> Haha, yes, "ntfy (pronounced notify) is a simple HTTP-based [pub-sub](https://en.wikipedia.org/wiki/Publish%E2%80%93subscribe_pattern) notification service" (from the first line of the website)

I should be more careful reading the web site (I jumped to the docs :))

Thanks a lot - it's all clear now!
