### ISSUE TITLE
A proper Web UI from the 21st century

### ISSUE THREAD

**Issue by binwiederhier** [binwiederhier/ntfy#111]

**Comment by ohitsdylan** [comment]
I might be able to provide some support in this area. Can you describe what you're looking for, please?

**Comment by binwiederhier** [comment]
Uhhhh I love it. I think this is best discussed in chat if you like ([Discord](https://discord.gg/cT7ECsZj9w) or [Matrix](https://matrix.to/#/#ntfy:matrix.org)). Especially since I don't quite know what I want. 

Ultimately though, I'd like to:
- Split the main web page and the web app
- A UI similar to the Android app, maybe material-design style
- Maybe
  - A card view of the subscriptions
  - A list of notifications with cards too?!
  - Support for attachments
  - ...

The Gotify interface is a good start I think, though something more material would be nice. As you can see, I don't know what I want.

As for technologies, maybe React or Vue, with actual modern JS (as opposed to the horribleness I've written).

**Comment by binwiederhier** [comment]
From a style perspective, this https://mui.com/

**Comment by ohitsdylan** [comment]
Understanding what I do about React and Vue, the way they handle data and the way this application behaves, I'd say that's a perfect fit.

Unfortunately, I'm not that savvy in Javascript, myself. However, I would be willing to design a UI that fits the needs and let someone better than the both of us make it work in practice. I can hop into the Matrix chat in a bit, if you'd like, still!

**Comment by binwiederhier** [comment]
I was hoping for someone with lots of JS+React experience.
This template I like: https://material-ui.com/store/previews/paperbase/

**Comment by ohitsdylan** [comment]
No problem! Won't know without asking.
I'll let someone else take the lead on this, then. Thanks!

**Comment by binwiederhier** [comment]
I mean you can try and see how far you can get. It's probably a good learning exercise.

**Comment by ohitsdylan** [comment]
I'll see what happens, no promises though 😅

**Comment by binwiederhier** [comment]
Done; will be in the next release.
