### ISSUE TITLE
Sending notifications with authentication

### ISSUE THREAD

**Issue by devarxify** [binwiederhier/ntfy#1132]
:question: **Question**

Hello! I have taken the permissions from regular users to send notifications through the server.yml file, thus making sending notifications from any means other than the web app (logged in through an admin account) not possible without authentication. I would like to know how to be able to authenticate myself through cURL to send a notification. Perhaps using an access token?

Thanks in advance and I hope you can answer my question.

**Comment by wunter8** [comment]
There are many examples in the docs: https://docs.ntfy.sh/publish/#authentication

**Comment by devarxify** [comment]
Thank you bery much! Fixed.
