### ISSUE TITLE
Add export / import function for config (Android app)

### ISSUE THREAD

**Issue by cmeis** [binwiederhier/ntfy#115]
Add the ability to export / import the app config (settings and mainly subscribed topics) for backup purposes.

**Comment by binwiederhier** [comment]
I like this idea. It annoys me a bit myself.

**Comment by binwiederhier** [comment]
![220314 15-53-20 Selection 001](https://user-images.githubusercontent.com/664597/158280878-4ab710ea-ffb2-447b-a1ac-3046db231b5e.png)
![220314 15-53-31 Selection 001](https://user-images.githubusercontent.com/664597/158280887-435e981b-76ef-45c5-b2aa-62fcda7aeed0.png)

This is done as part of https://github.com/binwiederhier/ntfy-android/commit/8e1830d361dea3e7d434d23bd263d4fd345f6a54. Will be in the next release of the Android app
