### ISSUE TITLE
Remove notifications one by one with swiping or button

### ISSUE THREAD

**Issue by xundeenergie** [binwiederhier/ntfy#117]
Please add a gesture to delete notifications one by one with swiping left or right. Or add a button to each notification with wich i can acknowledge/delete a notification.

And/Or a "Delete all" Button. Not to have to go into the menu, just to delete them all at once with only one klick.

**Comment by binwiederhier** [comment]
Since I didn't respond here yet: I like this idea. I'll eventually get to it.

**Comment by binwiederhier** [comment]
Implemented in https://github.com/binwiederhier/ntfy-android/commit/90848fde957f55475499f7fc3fb8e07a42543afc, will be in the next release.

**Comment by phurich** [comment]
Android app 1.16.0
I set the notification setting to "never automatically delete". However, swipe left or right makes my notification deleted unintentionally many times. Today we have a big screen cellphone, I just pick my phone up then my notification deleted. Is it possible to make this feature is an option in setting in the next release ?
