### ISSUE TITLE
[Question] Can we have both public and private groups after setting it with authentication 

### ISSUE THREAD

**Issue by Greatz08** [binwiederhier/ntfy#1189]
Previously i had setup without authentication/account so everything was easy and anyone could suscribe to topic and could conversate and after authentication setup everyone has to signin so is there any mix mode which can let people create and join without sign in in those particular topics and if they wanna join private one then they only they have to login ?

**Comment by wunter8** [comment]
It sounds like you're self-hosting, right? You can setup any access rules you want. You can leave the default as "read-write" so people can access most topics. Then for protected topics, you can require authentication. Unfortunately, most of this needs to be done on the command line for now (at least for more than 1 user to access a restricted topic). If only one user needs to restrict and access a topic, that can be done in the web app UI
