### ISSUE TITLE
Android app text color could be hard to read for some

### ISSUE THREAD

**Issue by kzshantonu** [binwiederhier/ntfy#119]
![Screenshot_20220126-034107__01.jpg](https://user-images.githubusercontent.com/7745374/151267404-be070186-a79c-461e-be1b-b7d4b6276905.jpg)

**Comment by binwiederhier** [comment]
Yup I agree that it's hard to read. I'll eventually get to it. Thanks for reporting.

**Comment by binwiederhier** [comment]
Closed as part of https://github.com/binwiederhier/ntfy-android/commit/e6c3a2e2bdffa2e7464dd8f8510c0691b717b635
Will be in the next release.
