### ISSUE TITLE
Export/Import subscriped topics or mass subscribe topics, webapp

### ISSUE THREAD

**Issue by Proximus888** [binwiederhier/ntfy#1201]
:bulb: **Idea**
I like to test various browsers, the only problem is that with ntfy I have to resubscribe to all my topics. I would love to have a way to export my settings from ntfy and be able to import them in another browser.

Or to have to option to mass subscribe to topics instead of one-by-one.

:computer: **Target components**

webapp

**Comment by wunter8** [comment]
You have a couple options:
1. The web app supports syncing subscriptions across devices. If you sign into your account, subscribe to topics, and then sign in on another device, the subscriptions should show up automatically. (It is just the subscription itself that is synced. Previously received messages and their read status will not sync)
2. If you navigate to the URL of a topic (e.g., https://ntfy.sh/mytopic), it will automatically subscribe to the topic for you. So, you could write a simple bash script or something to load each URL in the browser of your choice

**Comment by Proximus888** [comment]
> 1. The web app supports syncing subscriptions across devices. If you sign into your account, subscribe to topics, and then sign in on another device, the subscriptions should show up automatically. (It is just the subscription itself that is synced. Previously received messages and their read status will not sync)

I selfhost ntfy, but have not seen that option. I login in a new browser or igconito window and the topics/subscriptions are not synced. Am I missing a setting?

> 2. If you navigate to the URL of a topic (e.g., https://ntfy.sh/mytopic), it will automatically subscribe to the topic for you. So, you could write a simple bash script or something to load each URL in the browser of your choice

Thanks, didn't know that worked. Will try it out with zen-browser.

**Comment by wunter8** [comment]
You need to set `enable-login: true` in server.yml (or the equivalent env variables for docker). If you don't set that, you can still "add users" in the web app to authenticate with one or more ntfy servers. I'm pretty sure that's what you've done so far.

With `enable-login`, it will let you sign in to and manage your account on your particular server (but you cannot "login" to another server from yours). There will be a "login" (or "sign in") button in the top right corner of the web app.

I know the distinction between "adding a user" to the web app and "signing in to your account" is a bit confusing

**Comment by Proximus888** [comment]
> You need to set `enable-login: true` in server.yml (or the equivalent env variables for docker). If you don't set that, you can still "add users" in the web app to authenticate with one or more ntfy servers. I'm pretty sure that's what you've done so far.
> 
> With `enable-login`, it will let you sign in to and manage your account on your particular server (but you cannot "login" to another server from yours). There will be a "login" (or "sign in") button in the top right corner of the web app.
> 
> I know the distinction between "adding a user" to the web app and "signing in to your account" is a bit confusing


Thanks, that solved my issue, didn't know it was an option. 

I always went to settings and under 'Manage users' I added my user.

Now with login my subscriptions follow wherever I login. Why is that not the default behavior?

**Comment by wunter8** [comment]
Some people use ntfy without any kind of account. Some people set up their server so everything is read-write and you just need to know the topic to subscribe/publish (like the public ntfy.sh instance). It makes things easier when using curl, for example, so you don't need to worry about any credentials. Basically it's just user preference, so it's included as an option. Also, the subscription sync portion (separate from the account portion) was added semi-recently. When ntfy started, subscription sync wasn't available at all

**Comment by DAE51D** [comment]
@wunter8 Can you elaborate more on this. I also self-host an LXC on Proxmox. It's only a private LAN for my Arrstack and other ntfy notifications so I have mine "wide open" with no users or credentials. However, like you described, I have a dozen various PCs I use for different purposes. I don't understand how to sync my subscriptions across them without creating a user? 

I will look at the idea of harvesting all the channels into my bookmarks as a folder, then that syncs in chrome/firefox/etc. then i could open that folder and effectively "import" them to another PC (browser). Feels kind of hacky though. 

Is there a reason ntfy can't have an export/import of the channels in some JSON format or something to make this easier for the clients? Related, I'm a Sr. Software Engineer and author of the [Vobot ntfy app](https://github.com/DAE51D/vobot-apps/blob/main/ntfy/README.md), so if I were to add this feature in, would you be willing to approve the PR or not so much?

**Comment by wunter8** [comment]
If you create an account and log in to that account in the web app, your topics will sync. It sounds like you're not using accounts at all right now, though. Without accounts, there's no way to sync topics.

Yes, you could sync bookmarks like that, but it is kinda hacky.

A PR to add export and import to the web app would probably be accepted! But I'd suggest you talk with binwiederhier first to figure out exactly what that looks like.

In the meantime, if you want an alternative to syncing browser bookmarks, you can look around in the browser's local storage/index DB. That's where subscriptions are stored. I'm not sure if there's an existing way to export and import (a subset of) that information
