### ISSUE TITLE
web-documentation set own installed hostname in webserver-config-template 

### ISSUE THREAD

**Issue by xundeenergie** [binwiederhier/ntfy#121]
i love on ntfy documentation, that all examples on the self-hosted site are customized to the installed domain.

but the config-example for nginx is not customized.

please change it, that the server_name points also to the domain, where ntfy is installed and listens on.

**Comment by binwiederhier** [comment]
This is very hard to do with mkdocs, because the docs are generated at compile time. I'd have to do some horrible (probably inefficient) JS magic to make this work. I do see the benefit though. Thanks for reporting.
