### ISSUE TITLE
add information about UnifiedPush push-gateway

### ISSUE THREAD

**Issue by xundeenergie** [binwiederhier/ntfy#122]
As discussed in the matrix-rooms...

There is a way to "play" your own push-gateway for matrix (schildichat, fluffychat) to use ["common-proxies"](https://github.com/UnifiedPush/common-proxies)

this are only a few lines in ntfy's nginx config

```
  # this sends traffic to common-proxies
  location ~ ^/(FCM|UP|_matrix) {
          proxy_pass                    http://127.0.0.1:5000;
  }
```

And installing a binary from the link above with a few lines of configuration (add nfty-host) to AllowedHosts list and run it as a service which listens on port 5000.

Then you can use for example (and now only??) matrix with only selfhosted services. matrix->pushgateway->nfty-server->schildi/fluffychat. Not other vendor sees your data!

It's really easy to integrate.

**Comment by binwiederhier** [comment]
As @p1gp1g has said in the Discord channel, this is more of a missing piece in the UP docs, though I'm more than willing to add it to an "Integrations" page (when I eventually make that)

**Comment by binwiederhier** [comment]
> I don't really think ntfy should integrate the push gateway

Oh I wasn't planning to. I was merely planning to add docs potentially.
