### ISSUE TITLE
unable to create new user

### ISSUE THREAD

**Issue by Its-EGS** [binwiederhier/ntfy#1223]
:lady_beetle: **Describe the bug**
trying to create a new user on cli

:computer: **Components impacted**
try it on ntfy server version 2.11.0 running in docker on synology

:bulb: **Screenshots and/or logs**
![grafik](https://github.com/user-attachments/assets/a4d845ca-3fa8-4350-aa03-071a4fc47d5a)
![grafik](https://github.com/user-attachments/assets/02a71de1-3223-4fbd-a7fd-7e2a10651cda)

No logs are generated, neither with the first command nor with the second. Even with`TRACE`

:crystal_ball: **Additional context**
the first command simply does not prompt for the password repeat. It is irrelevant whether it is a complex password with special characters or a simple one as in the example screenshot.

**Comment by wunter8** [comment]
I'm not sure what the issue is. I just ran the same commands without a problem. Try it with `docker exec -it ntfy ...` instead of just "-t".

Also, you could try running the commands from a shell inside the container: `docker exec -it ntfy /bin/sh` then `ntfy user add phil`

**Comment by Its-EGS** [comment]
yes, `docker exec -it ntfy /bin/sh` worked for me. Thanks a lot.
