### ISSUE TITLE
send attachment + a message with curl

### ISSUE THREAD

**Issue by dev72** [binwiederhier/ntfy#1247]
Hello,
if I use che ntfy cli I can send a file and set a custom message.
Is there a way to do the same via curl?

Is there a value I can set in attachment-expiry-duration to never delete attachments?

Thank you.

**Comment by wunter8** [comment]
> if I use che ntfy cli I can send a file and set a custom message.
Is there a way to do the same via curl?

You can use this example to attach a local image: https://docs.ntfy.sh/publish/#__tabbed_24_1

To set a custom message, add `-H "Message: your message here`

> Is there a value I can set in attachment-expiry-duration to never delete attachments?

The value has to be non-zero to store attachments, but you can make it save files for years. "Days" is the largest granularity that works. So you could do 1825 days for 5 years.

**Comment by dev72** [comment]
Thank you.
Can I attach more thank one file in a request?

**Comment by wunter8** [comment]
No, you can't. So if you want to send multiple files, they need to be zipped or archived into a single file first

**Comment by dev72** [comment]
ok, thank you very much.
