### ISSUE TITLE
reword error message when sending test message to read-only topic in the app

### ISSUE THREAD

**Issue by cmeis** [binwiederhier/ntfy#125]
One minor thing in the app regarding auth:
When you're subscribed to a topic with read-only permissions, the "send test message" of course fails.
The error message could be reworded now from "unexpected response 403" to something like " no write permission", to avoid confusion.

**Comment by binwiederhier** [comment]
Did this as part of https://github.com/binwiederhier/ntfy-android/commit/3abd0b3da9a5f0b8d991dc1a3fd081991e0de6fc#diff-5e01f7d37a66e4ca03deefc205d8e7008661cdd0284a05aaba1858e6b7bf9103R132
