### ISSUE TITLE
Feature request: icon param for notifications

### ISSUE THREAD

**Issue by poblabs** [binwiederhier/ntfy#126]
Outside of the file or attachment parameters, it would be nice to have an icon parameter. This would show up on the android client to the side as a quick visual reference to the alert. I also have another use case where I would use it with windows 10 toast notifications. 

Thanks!

**Comment by binwiederhier** [comment]
@poblabs Would you want something like this:

```
curl -d hi -H "Icon: https://example.com/myicon.png" ntfy.sh/mytopic
```

Or (with `myicon` being configured in the app):
```
curl -d hi -H "Icon: myicon" ntfy.sh/mytopic
```

**Comment by binwiederhier** [comment]
Also, would #155 be enough?

**Comment by poblabs** [comment]
@binwiederhier I think per-notification icon would be a nice touch. That way I only have to sub to 1 topic, but use it for multiple apps. The icon would identify the app within the sub. I suppose I'm not picky though as I could make a new topic for each app - just more overhead to remember it all

**Comment by wunter8** [comment]
Alright! The code is just about done!

![image](https://user-images.githubusercontent.com/8421688/179364676-5f466c9d-310a-47ff-8f48-dcdac3474908.png)

![image](https://user-images.githubusercontent.com/8421688/179364682-b9eacb9b-5efb-4ae2-92d2-0b510592131d.png)

![image](https://user-images.githubusercontent.com/8421688/179364685-3ba2e559-60c1-4c4b-929b-7497009ed422.png)

![image](https://user-images.githubusercontent.com/8421688/179364689-c9ec1cc4-6172-4c5d-afc0-1304771b4c8d.png)

![image](https://user-images.githubusercontent.com/8421688/179364692-7eafe58d-5bb9-4009-9783-26cfb0cca45c.png)

**Comment by binwiederhier** [comment]
Done, next release
