### ISSUE TITLE
gio client 

### ISSUE THREAD

**Issue by gedw99** [binwiederhier/ntfy#128]
Adding this in case anyone wants to work on it or i get time to come back and do it.

https://github.com/gioui/gio-example/blob/main/notify/main.go will hook up with nfty quite well
Its designed to do local notifications, but of course can subscribe to the nfty server over SSE to get new messages and show them locally.

works on all desktops, mobiles. 

 No web driver yet: https://github.com/gioui/gio-x/tree/main/notify, but not hard to add.

**Comment by binwiederhier** [comment]
I'm really trying to keep an open mind here, gio looks a little unpolished for my taste, and it also reminds me a little bit of Adobe Flash. It's using non-native widgets and components. 

When I make a web UI, I'll try to make something with React and some Material design components.

As for desktop integrations, I don't know when that'll come, but it has to blend in nicely and this doesn't seem it.

**Comment by gedw99** [comment]
Its cool :)   I think that its a good thing that nfty Clients are built with traditional technologies, and GIO. Devs then have a huge choice. You can also mix and match in that you can build a client with golang with no gui, and then reuse that in traditional android and iOS and / or GIO. 

I appreciate your frank comment. Gio is very different. Its designed to replace ios, android, desktop and web with ONE STACK. Its like FLutter in this regard. And if you are old enough the Java "write once run everywhere" mantra :)

Gio also supports chinese and arabic text automatically where you need the GUI to be RTL ( right to left ).
It also now has support for IME, and so can display chinese and arabic text.

There are many many apps being built with it, that are at various stages of maturity. https://github.com/search?l=Go&o=desc&q=gioui.org&s=indexed&type=Code

The team behind it are dedicated to open source. This is why they don't use github but instead SourceHut actually. Its not a bait and switch scenario !!

If you want i can show you full apps built with it. I have been using it a fair bit. I am no expert though.
Compiling of course is easy because its Write once run everywhere. "go run ." is all you need to desktop - nothing else.
For Web and Mobile, you just pass in it in. 

Because it can compile to web, you can run tutorials in web. For example this is running gio as a tutorial for how to use gio.
https://eliasnaur.com/blog/immediate-mode-gui-programming.

The way you use it is insanely simple. Everything is an OP.

**Comment by binwiederhier** [comment]
Please don't take this the wrong way, but I don't think I'll be using gio any time soon. This may of course change in the future, but right now it looks unpolished and slow, and it doesn't render native browser text even. I just released the web app which has a design in line with the Android app and material design.

Closing this for now. Thank you for the ticket. Please keep the ideas coming and don't take this the wrong way.

**Comment by gedw99** [comment]
@binwiederhier all good :)

related : https://github.com/gioui-plugins/gio-plugins/tree/main/share

This allows sharing from a GUI, and taps into the OS level share URL schema.  
For example it will pop up telegram, whatsapp, etc etc if you have it installed.

Ironically it also runs in a browser as wasm.
