### ISSUE TITLE
using Liftbridge  for HA

### ISSUE THREAD

**Issue by gedw99** [binwiederhier/ntfy#129]
There is a 2nd nats server option that sone people prefer 

https://github.com/liftbridge-io

it is a GRPC api with NATS either embedded or as a separate server.

Sone devs prefer this because it hides many of the nats things and is simpler . 

Being GRPC is can be load balanced .

Nats Jetstream for example requires the client and server to use the nats client. 

I am only raising this issue in case we want to scale out nifty easily !

**Comment by gc-ss** [comment]
Some of the WHY's behind LiftBridge/NATS

Reliability: https://github.com/binwiederhier/ntfy/issues/78#issuecomment-1031911712
HA: https://github.com/binwiederhier/ntfy/issues/78#issuecomment-1030638013

**Comment by gedw99** [comment]
deleting this because we are discussing it in the main issue...
