### ISSUE TITLE
Android client: Subscribe to topic dialog doesn't scroll

### ISSUE THREAD

**Issue by arminus** [binwiederhier/ntfy#131]
Just tried to test the new 1.8.0 - can't enter much in the Subscribe to topic dialog (I'm using MS Swiftkey, didn't have this problem in previous versions and the same happens with the default Samsung keyboard):

![2022-02-06_131813](https://user-images.githubusercontent.com/683680/152680465-8e053efc-58c8-4f01-bc4a-ded493854681.png)

**Comment by binwiederhier** [comment]
> can't enter much in the Subscribe to topic dialog 

Oh my. So this is just that it doesn't scroll, but the fields are active? Or are the text fields also deactivated?

**Comment by arminus** [comment]
I briefly see the lower fields, but when the keyboard slides in, it resizes the modal and then there's no way to get to the fields lower down, i.e. wiping up or down inside the modal has no effect. Guess my old Samsung A5's screen resolution is too low ;-) 

![BadKeyboard](https://user-images.githubusercontent.com/683680/152687084-7cfc9aae-4299-416b-b6cf-2a38e4c6e2a3.gif)

**Comment by binwiederhier** [comment]
I'll be fixing this urgently before continuing the Google Play rollout of 1.8.0. Thank you very much for reporting.

**Comment by binwiederhier** [comment]
Fixed in 1.8.1. Will release soon.
