### ISSUE TITLE
Add action buttons to notifications to allow for user response to ntfy message

### ISSUE THREAD

**Issue by mrherman** [binwiederhier/ntfy#134]
Add the ability to add clickable responses to a ntfy message.  This is allowed in android notifications (called notification actions: https://developer.android.com/training/notify-user/build-notification.html#Actions).  To make it consistent across all the ways to view a message I think it would also need to be added to the ntfy app's list of messages (adding clickable buttons under the message) and to web push notifications.

The action taken when a button is pushed could be a message published on a topic determined by a header set in the original notification and text indication which button.  In this way the server that sent the actionable notification can just listen on a determined topic for a reply and to take action.  The number of buttons and their text could be set in the same way.

Action buttons in a android notification (concept):
![image](https://user-images.githubusercontent.com/1773927/152996787-6aefd65c-0c3f-4271-b1e0-cc8f30b08335.png)

**Comment by RasHas** [comment]
Would love to have this feature. 

Not sure how it is implemented but HomeAssistant has a feature like that: https://companion.home-assistant.io/docs/notifications/actionable-notifications/

Maybe the client does a POST to the server?

**Comment by binwiederhier** [comment]
I'm going to work on this next. I am still brainstorming, but this is the idea so far:

```
curl \
  -H "Action: Show Tweet; view; https://twitter.com/binwiederhier/status/1467633927951163392" \
  -d "Somebody tweeted about ntfy" \
  ntfy.sh/tweet-alerts
  
curl \
  -H "Action: Open HomecamApp; open; org.homecamapp" \
  -H "Action2: Call police; http-post; https://police.com/..." \
  -d "Garage door sensor motion alert" \
  ntfy.sh/garage-door-alert
```
My thoughts are that I can provide a limited syntax via HTTP headers, and then if you really want to pass more details, you can pass the message as JSON (https://ntfy.sh/docs/publish/#publish-as-json), something like

```
curl -d '{
  "message": "garage door alert",
  "actions": [
    { 
      "action": "open",
      ...
```

**Comment by RasHas** [comment]
Let us know if you need any help testing

**Comment by binwiederhier** [comment]
📢  **User actions: Request for testing**

- Server binary (amd64): https://phil.nopaste.net/ntfy-am64-actions?d=1&f=ntfy&a=vcbWyfDPkw
- Android apk: https://phil.nopaste.net/ntfy-actions-android.apk?d=1&f=app-play-debug.apk&a=IkjnamhB0I

**How to test**

Server: 
- Run server binary with `ntfy serve --cache-file cache.db` (a db upgrade is required, so you may want to not use your prod db)
Android: 
- Back up current settings via Settings -> Back up to file
- Uninstall ntfy from phone
- Download .apk to phone and install it
- Subscribe to local ntfy test server

Then navigate to https://<testserver>/docs/publish/#action-buttons and play with it.

**Comment by binwiederhier** [comment]
@RasHas @mrherman This is ready for testing :-D

**Comment by binwiederhier** [comment]
:loudspeaker: **Updated test binaries:**

Server:  
- https://phil.nopaste.net/t7XjlVBntr?d=1&f=ntfy&a=qsyn9vej8g
- `wget -O ntfy-actions-amd64 "https://phil.nopaste.net/t7XjlVBntr?d=1&f=ntfy&a=qsyn9vej8g"`

APK: 
- https://phil.nopaste.net/T7d7JOvNRH?d=1&f=app-play-debug.apk&a=uVxXKVl4wn

**Comment by binwiederhier** [comment]
Will be in the next release
