### ISSUE TITLE
Integrate Android "Share with topic" dialog

### ISSUE THREAD

**Issue by binwiederhier** [binwiederhier/ntfy#136]
[emptymatrix](https://www.reddit.com/user/emptymatrix/) suggested this [on Reddit](https://www.reddit.com/r/selfhosted/comments/s5jylf/my_open_source_notification_android_app_and/ht1bxfd/):

"to replace pushbullet in my phone, it requires to be able to share items from any android app to a ntfy topic. I mean: while browsing a URL in my favorite browser (Firefox, opensource, of course ;)) and I want to send it to a ntfy topic, I just would need to click on Share button, select ntfy, then ntfy would show a list of target topics, so I could pick one.

"target topics" would be a list of topics (editable in the ntfy UI in the app) to which I'm not subscribed but I would like to share often. Each topic would represent a device."

**Comment by binwiederhier** [comment]
This actually sounds like fun to work on, so I'll do this next.

**Comment by cmeis** [comment]
That's the way to do it, Phil. Forget test driven development - fun driven development rules! :-P (SCNR)

**Comment by binwiederhier** [comment]
This is done and will be released with the next app release; see https://github.com/binwiederhier/ntfy-android/pull/16
