### ISSUE TITLE
PowerShell Examples in Docs

### ISSUE THREAD

**Issue by hl2guide** [binwiederhier/ntfy#138]
Please add powershell examples to docs.

https://ntfy.sh/docs/publish/

e.g.

```
$message = "message"
$topic = "topic"
$messagePost = Invoke-WebRequest -Method Post -UseBasicParsing -UseDefaultCredentials -URI "ntfy.sh/$topic" -Body $message
```

**Comment by binwiederhier** [comment]
Thanks for the ticket. I don't really have a Windows PC at hand. Could you create a pull request against https://github.com/binwiederhier/ntfy/blob/main/docs/publish.md with the examples? Most of them will likely be straight forward, given the example you gave, but I'd rather someone who can actually test it create the PR.

**Comment by Joeharrison94** [comment]
> Please add powershell examples to docs.
> 
> https://ntfy.sh/docs/publish/
> 
> e.g.
> 
> ```
> $message = "message"
> $topic = "topic"
> $messagePost = Invoke-WebRequest -Method Post -UseBasicParsing -UseDefaultCredentials -URI "ntfy.sh/$topic" -Body $message
> ```

I have added this to the docs now for you it will be up once @binwiederhier has had chance to review the changes and merge the pull request.

**Comment by binwiederhier** [comment]
This is done and will be in the next release. Thanks to @Joeharrison94.
