### ISSUE TITLE
Display times as local date/time format

### ISSUE THREAD

**Issue by hl2guide** [binwiederhier/ntfy#140]
Please add the ability to switch between 24 and 12 hour time format and support AM/PM too.

**Comment by binwiederhier** [comment]
> Please add the ability to switch between 24 and 12 hour time format and support AM/PM too.
> Please allow us in the Android app's settings to set a Custom date-time format string to use.

I closed #139 in favor of this. 

I don't think I want to provide customizable datetime formatting or even switch between AM/PM and 24h format, though I acknowledge that the date time format is not very consistent. I'd want to provide a consistent view, using the default system locale. I believe I'm using the system locale in all places but the notification detail overview, right? 

Why would you want it to be customizable? What's missing that you need?

**Comment by hl2guide** [comment]
The main thing is 12 hour time.

**Comment by binwiederhier** [comment]
![220313 20-15-28 Selection 001](https://user-images.githubusercontent.com/664597/158085703-13164c8e-6234-467d-affc-d6ca9f8bf153.png)

One line change in https://github.com/binwiederhier/ntfy-android/commit/031f5c472d361cc731218ff953ca68a4c0d4f4c0. I hope this is good enough :-) This will be different depending on the Locale of the phone.

Will be released in the next Android release.

**Comment by DoTheEvo** [comment]
the non-mobile website [is still only in AM/PM and american date format](https://i.imgur.com/t2Ald2v.png)

**Comment by timdonovanuk** [comment]
![image](https://github.com/binwiederhier/ntfy/assets/8156439/176aa727-9714-46b2-9e6e-88fa26caec74)

![image](https://github.com/binwiederhier/ntfy/assets/8156439/c7b50741-f51c-4fe0-aa40-92b5cf1b0391)

**Comment by timdonovanuk** [comment]
Please provide at least configuration to switch to a non US centric (i.e. rest of the world) date format.

**Comment by Choque** [comment]
Yea, not seeing MM/DD/YYYY and AM/PM in the notifications would be appreciated. It shows the correct format in the android app, but in the browser I get the default format.

**Comment by timdonovanuk** [comment]
The obvious solution is for the rest of the world to adopt the incoherent American format, hence the ticket is closed ;)

**Comment by roughnecks** [comment]
👎 for closing this.

**Comment by cross** [comment]
Is there another issue open for this in the web app?  I looked for a setting to change it, but as noted here that doesn't exist.  My Mac is configured to show 24-hour time everywhere, so it is neither using the system config or allowing me to set the time format.
