### ISSUE TITLE
Sender authorization for public use

### ISSUE THREAD

**Issue by FedericoCeratto** [binwiederhier/ntfy#143]
Hello and thanks for developing ntfy. Currently the topic works as a shared secret.
If a developer publishes an application that contains an hardcoded topic anybody can extract it and use it to send notifications.
(Applications might implement signature verification but receiving a large number of spam messages would consume battery and create a DoS vulnerability).

Additionally, the application should not create a hard dependency on a single public instance of Ntfy like ntfy.sh
The application should be able to switch to a different public server to receive notification from trusted senders. The sender could simply send a notification to every Ntfy instance and should not have to monitor which instances are available, or handle user/pass pairs etc.

Would you consider adding some authorization? I could suggest stateless server-side signature verification where the topic contains a base64-encoded public key and the server rejects any message that does not have a matching "Signature: <foo>" header.

**Comment by binwiederhier** [comment]
You can see a video of the app and a discussion here: https://www.reddit.com/r/selfhosted/comments/snulj5/as_requested_a_lot_by_you_guys_i_added_auth/

**Comment by binwiederhier** [comment]
There are also some public topics you can use to test it: https://github.com/binwiederhier/ntfy/commit/218864338707a3eb7c3390c7fb09089091076347#diff-4ff92ab21f32a2846ac37bb30732d3475ed5a5c1f6a0637813e469213233d8cbR1177 (the docs for this are not live yet)

**Comment by FedericoCeratto** [comment]
@binwiederhier thanks for the answer. My question is specifically about stateless auth with public instances, so that the sender does not need to manage user/pass pairs and to trust the servers.

**Comment by binwiederhier** [comment]
Yeah in the beginning of designing auth i wanted to add topic reservations to lease topics for X hours, with auto extending, for this exact purpose. 

It definitely wouldn't be stateless, because it would have to persist through restarts.

**Comment by binwiederhier** [comment]
Another thought i had was shadow topics, basically allow basic auth user with user `shadow:somepass` where every password was allowed, and every topic+password combination effectively makes a new topic. So everyone could use mytopic as a topic, but you'd have to use your own key to publish/subscribe to see it

**Comment by binwiederhier** [comment]
Alright here are two ideas:

### Temporary reservation
On a first come first serve basis, you define the auth mode and key you like in the POST of the first message, and then only you can write to it with the key you give. e.g.

```
curl -d "message 123" -H "Reserve: read-only hunter2" ntfy.sh/jay

# Alternative syntax idea:
curl -d "message 123" -H "Key: hunter2" -H "Everyone: read-only" ntfy.sh/jay
```

And then for 12 hours or whatever, that topic would be reserved to you, with others being able to read, but only you with `Key: hunter2` being able to write, or until you publish another message.

### Shadow topics
That'd be when you just pass a "Key: abc" header and your topic ntfy.sh/jay is essentially ntfy.sh/jay:abc under the hood. So you have a short topic "jay", but others can use it too with a different key.

**Comment by FedericoCeratto** [comment]
@binwiederhier I updated the initial description. Maybe I should create a dedicated issue around redundancy/failover.

**Comment by dcousens** [comment]
Alternatively, following the "shadow topic" idea by @binwiederhier,  you could support publishing to 

- `https://ntfy.sh/shadow/foobar`,  with only way to subscribe to it through `https://ntfy.sh/c3ab8ff13720e8ad9047dd39466b3c8974e592c2fa383d4a3960714caef0c4f2`.

That hex represents the `sha256` of `foobar`.
This read/write position is enforce by the server,  and maintains the same security considerations as before (easy to guess topics are still low security).

**Comment by binwiederhier** [comment]
Given that we now have username/password + access tokens, I don't think I want to create another way of authenticating against the server. So I'm closing this.
