### ISSUE TITLE
Poll all messages since message $id

### ISSUE THREAD

**Issue by nachotp** [binwiederhier/ntfy#151]

**Comment by binwiederhier** [comment]
This is incredibly annoying to work around in all the clients; I am implementing this now as part of the web UI.

**Comment by binwiederhier** [comment]
Noooo. Why did I pick 10 as the message ID length. Now it's indistinguishable from a unix timestamp, which is also 10 characters long

**Comment by binwiederhier** [comment]
Done, will be released as part of v1.16.0
