### ISSUE TITLE
[FR] Custom parsing of data for topic

### ISSUE THREAD

**Issue by 12nick12** [binwiederhier/ntfy#154]
I have many different locations that push data via NTFY. It would be nice if we could parse data on the server side to specify which data is sent to the clients. This is example data sent from rundeck json

    {
      "trigger": "success",
      "status": "succeeded",
      "executionId": 179,
      "execution": {
        "id": 179,
        "href": "https://rundeck.domain.com/project/git-project/execution/follow/179",
        "permalink": null,
        "status": "succeeded",
        "project": "git-project",
        "executionType": "user",
        "user": "USER",
        "date-started": {
          "unixtime": 1646766495415,
          "date": "2022-03-08T19:08:15Z"
        },
        "job": {
          "id": "13f3cc36-6830-4bcb-add7-9d56102a915c",
          "averageDuration": 185386,
          "name": "apt-update",
          "group": "",
          "project": "git-project",
          "description": "",
          "href": "https://rundeck.domain.com/api/40/job/13f3cc36-6830-4bcb-add7-9d56102a915c",
          "permalink": "https://rundeck.domain.com/project/git-project/job/show/13f3cc36-6830-4bcb-add7-9d56102a915c"
        },
        "description": "Plugin[com.batix.rundeck.plugins.AnsiblePlaybookWorflowNodeStep, nodeStep: true]",
        "argstring": null,
        "serverUUID": "ff7afb2e-56a8-4ca4-a181-bce45674d1ef"
      }
    }

**Comment by binwiederhier** [comment]
I like this idea a lot, though I think it's kind of hard to implement in a generic way. There was a discussion on this in #104, which may be a duplicate. Do you have any ideas of how to generically implement this?

**Comment by binwiederhier** [comment]
Actually, let's call this ticket a duplicate. @12nick12 feel free to comment in #104
