### ISSUE TITLE
per-subscription settings (min priority, mute, delete after, icons, ...)

### ISSUE THREAD

**Issue by mztiq** [binwiederhier/ntfy#155]
A feature to set custom icons per subscription would be much appreciated, makes identifying push notifications on mobile easier.

Thanks in advance and greetings from a fellow german :D

**Comment by binwiederhier** [comment]
Is this the same as #126? Maybe not since #126 asks for per-notification icons and this one asks for per-subscription icons.

**Comment by mztiq** [comment]
per-subscription icons are enough for me, both would be fine tho.

**Comment by binwiederhier** [comment]
I'm updating this ticket to extend the scope: I'll use this to do per-subscription settings for what already exists in the global settings, plus the originally requests icons.

Subscription settings:
- Min priority
- Mute 
- Delete after
- Icon

**Comment by binwiederhier** [comment]
https://github.com/binwiederhier/ntfy-android/pull/28

**Comment by binwiederhier** [comment]
![220508 23-07-31 Selection 001](https://user-images.githubusercontent.com/664597/167334170-ec6c389e-c7ee-4dfe-9403-196601d96721.png)

![image](https://user-images.githubusercontent.com/664597/167334191-e0738bec-98eb-4a14-b040-ef68c75c6d33.png)

![image](https://user-images.githubusercontent.com/664597/167334273-b03c65d8-9cb1-44fb-8f07-b881c81e1a66.png)

![220508 23-12-49 Selection 001](https://user-images.githubusercontent.com/664597/167334340-08b56cbb-611e-44f9-9b64-6b889969c9e6.png)

![220508 23-14-35 Selection 001](https://user-images.githubusercontent.com/664597/167334501-7f5a0515-691f-4850-b99f-1da92625e46a.png)

![220508 23-14-08 Selection 001](https://user-images.githubusercontent.com/664597/167334522-11636829-c3fd-4754-a113-f4abdd980d48.png)

**Comment by binwiederhier** [comment]
:loudspeaker: **Request for testing**

- .apk download: https://phil.nopaste.net/ntfy-155.apk?d=1&f=app-play-debug.apk&a=6vBnnSTo15
- Please test all subscription settings (your topic -> Subscription settings)

⚠️ **Important note** for the above .apk file: Please backup subscriptions and notifications before testing (Settings -> Backup to file). Also, if you had a previous debug .apk installed, please uninstall that first as you'll otherwise experience crashes

**Comment by kaiwei** [comment]
Any chance this feature will come to the iOS app as well eventually?
