### ISSUE TITLE
WebApp v.1.17.0: TypeError: crypto.subtle is undefined - messages not loaded in running session

### ISSUE THREAD

**Issue by arminus** [binwiederhier/ntfy#157]
First of all, thanks for the new web app, great job!

I do have an issue, though (v.1.17.0 installed on a Pi4), Firefox 97 on Win10, topic with auth enabled).

Messages only arrive in the browser after a page reload, and then with some delay (until the first [Poller] log message appears), same message arrives immediately on Android and in a Python listener I have running on the same box as my Firefox.

Here's the console output with the error I get on page load:

![2022-03-12_123251](https://user-images.githubusercontent.com/683680/158016494-b73e8e22-2160-48b5-b4f4-19048787b40c.png)

( -> quick google revealed [this](https://github.com/cypress-io/cypress/issues/14600) - some Firefox peculiarity?)

With Brave, the situation is slightly different, there's also a delay until the messages appear (after a page reload), but the JS errors are different:

![2022-03-12_124320](https://user-images.githubusercontent.com/683680/158016677-85f17a2c-99cf-49af-9dc2-458ff32183a6.png)

**Comment by binwiederhier** [comment]
Thank you very much for reporting this. I'll get it fixed asap.

**Comment by binwiederhier** [comment]
Fixed in https://github.com/binwiederhier/ntfy/commit/3699464947fd9ec186278c8a9ce4a7c7478cd708, I'll release this shortly. 

Thank you for reporting.

**Comment by binwiederhier** [comment]
This is deployed now. Feel free to test.

**Comment by arminus** [comment]
Works now, thanks for the quick fix!
