### ISSUE TITLE
`curl -s` doesn't work

### ISSUE THREAD

**Issue by DUOLabs333** [binwiederhier/ntfy#16]
I can successfully push a message to, but I can't get it in a GET request with `curl -s`

**Comment by binwiederhier** [comment]
Can you give a concrete example? Remember that the GET requires that you add /json or /raw or /sse at the end. Check out the examples on https://ntfy.sh/#subscribe

**Comment by DUOLabs333** [comment]
Do `curl -d "long process is down" ntfy.sh/duolabs333`, then `curl -s ntfy.sh/duolabs333`. Nothing returns.

**Comment by binwiederhier** [comment]
Oh I see the confusion. The GET is a connection that stays open forever. If you open the GET first and then PUT/POST you'll see your messages in the GET. I should make a video...

You can also poll using ?poll=1 

I'm not on my computer, otherwise I'd give you a detailed example.

**Comment by DUOLabs333** [comment]
Ok, I see that now.

**Comment by DUOLabs333** [comment]
Is there a way to get the last `n` messages?

**Comment by binwiederhier** [comment]
Long polling (connection stays open forever (: 
```
# In window 1 (do this FIRST)
curl -s ntfy.sh/duolabs333/raw

# In window 2
curl -d "long process is down" ntfy.sh/duolabs333
```

Polling: 
```
# In window 1
curl -d "long process is down" ntfy.sh/duolabs333

# In window 2
curl -s ntfy.sh/duolabs333/raw?poll=1
```

Check out the since= param to message since a timestamp.

**Comment by binwiederhier** [comment]
Since: https://ntfy.sh/#fetching-cached-messages

**Comment by DUOLabs333** [comment]
Ok, thank you.
