### ISSUE TITLE
Jellyfin and other app webhook integration request

### ISSUE THREAD

**Issue by Joeharrison94** [binwiederhier/ntfy#169]
Please can you add webhook integration for the following;

- Jellyfin - https://github.com/jellyfin/jellyfin-plugin-webhook
- Overseerr - https://docs.overseerr.dev/using-overseerr/notifications/webhooks
- Sonarr - https://github.com/Sonarr/Sonarr/wiki
- Radarr - https://github.com/Radarr/Radarr/wiki
- Uptime Kuma - https://uptime.kuma.pet/docs/Notification-Methods
- Diun - https://crazymax.dev/diun/notif/webhook/

Thank you

**Comment by nickexyz** [comment]
I made a few shellscripts here, works with Sonarr and Radarr if you use "Custom scripts". They aren't perfect, but works. https://github.com/nickexyz/ntfy-shellscripts
Bash is needed though.

**Comment by Joeharrison94** [comment]
Damn I didn't see those! So are they designed to be run in the container?

**Comment by nickexyz** [comment]
Sure, if you are using Docker, then just place them in a volume where the service can access them. The /config folder probably works.

**Comment by Joeharrison94** [comment]
> Sure, if you are using Docker, then just place them in a volume where the service can access them. The /config folder probably works.

Do you call them with cron what's the method you use

**Comment by nickexyz** [comment]
Sonarr -> Connections -> Add -> Custom Script ->Choose the script path :)

**Comment by Joeharrison94** [comment]
> Sonarr -> Connections -> Add -> Custom Script ->Choose the script path :)

Thank you had no idea that was an option

**Comment by nickexyz** [comment]
Glad to help!

**Comment by binwiederhier** [comment]
@nickexyz This is great. Could I trouble you to create a pull request against the examples page in the docs and describe and link to this? I could try to describe it, but I don't know what half of these tools do :-D

**Comment by Joeharrison94** [comment]
I'll push my scripts and JSON examples too!

**Comment by nickexyz** [comment]
@binwiederhier Sure thing!

**Comment by axelsimon** [comment]
This got closed but AFAICT both Jellyfin and Diun still have no examples, either in the docs or in the repo. It's a shame, as Jellyfin is a pretty popular project and could really benefit from neat ntfy integration.

**Comment by binwiederhier** [comment]
@axelsimon I would be thrilled if you could provide an example, preferably with screenshots and such. I do not use either myself, so feel free to provide a PR or instructions here so I can add it.

**Comment by sudo-kraken** [comment]
@Fallenbagel can you grab your screenshots and dump them here for the jf webhooks for ntfy please, I moved back to plex so cant post mine.

**Comment by binwiederhier** [comment]
`<sidebar>`
@sudo-kraken Joe!! I used your app review as the focus quote on the [ntfy.sh](https://ntfy.sh) website! I wanted to ask your permission first, but at the time I couldn't for the life of me find your GitHub username. Anyway, is this okay with you? If not, I can take it down obviously!

![image](https://github.com/binwiederhier/ntfy/assets/664597/1c866519-697e-4f75-8ecd-143bc8854759)
`</sidebar>`

**Comment by sudo-kraken** [comment]
@binwiederhier yeah man its no problem at all its because I swapped my username lmao should still have me on discord. I saw it the other day was like hell yeah! I remember writing the powershell examples many moons ago!

**Comment by binwiederhier** [comment]
Discord search is garbage, I tried looking without success.

**Comment by sudo-kraken** [comment]
No worries im still using ntfy, moved to ios now so lost my testing status though.

**Comment by Fallenbagel** [comment]
> @Fallenbagel can you grab your screenshots and dump them here for the jf webhooks for ntfy please, I moved back to plex so cant post mine.

Will share, hopefully tonight
