### ISSUE TITLE
Android app: divider between notifications or displaying notifications as cards

### ISSUE THREAD

**Issue by cmeis** [binwiederhier/ntfy#175]
The idea is to create a better visual hint between notifications. See this mockup (left is current app, right some kind of suggestion):

![image](https://user-images.githubusercontent.com/1850168/158999836-6b5ccb3c-f217-45f9-bf2a-b7ca9c5e2a04.png)

**Comment by binwiederhier** [comment]
WIP https://github.com/binwiederhier/ntfy-android/pull/27

**Comment by binwiederhier** [comment]
![Screenshot_20220429-195743](https://user-images.githubusercontent.com/664597/166081976-3056755a-fe78-412c-97a8-157af3ccf947.jpg)
![Screenshot_20220429-195750](https://user-images.githubusercontent.com/664597/166081980-af1886f6-b2cf-409b-acd1-ca5081d7857c.jpg)
![Screenshot_20220429-195817](https://user-images.githubusercontent.com/664597/166081982-1935abad-6fb5-4012-a42f-b46ff5015087.jpg)
![Screenshot_20220429-195824](https://user-images.githubusercontent.com/664597/166081986-42763623-6dc7-4634-b1fc-dc59e9ce9bad.jpg)

**Comment by binwiederhier** [comment]
Done. Will be in next release.
