### ISSUE TITLE
Daily Summary Notification

### ISSUE THREAD

**Issue by dwmccheyne** [binwiederhier/ntfy#18]
I would like to schedule a summary notification, daily at 8am with minimal content something like:
```
Last 24 hours:
New: 24 messages
Unread: 3 messages (2 /topic1, 1 /topic2)
```
This would let me see at a glance if any hot topics had come in overnight on say, a chatty release/testing night and be more comfortable turning off my notifications.

**Comment by binwiederhier** [comment]
I honestly don't think I'd want to do this any time soon or ever. Mayyyybe I'll add some stats in the Android app itself, but likely that does seem like it's out of scope.

Closing for now. If anyone else feels like this is a must have, please comment here; maybe I'll consider re-opening at a later date. Sorry Dave.
