### ISSUE TITLE
Android app: Untranslatable strings

### ISSUE THREAD

**Issue by StoyanDimitrov** [binwiederhier/ntfy#192]
The second value of [`settings_notifications_min_priority_summary_x_or_higher`](https://github.com/binwiederhier/ntfy-android/blob/bf52b3ba8a76db9d13ce5a06cbc6a06211f80750/app/src/main/res/values/strings.xml#L241) is not available for translation. The values comes from [`toPriorityString`](https://github.com/binwiederhier/ntfy-android/blob/8339bc9c2a385d5ee685deaba8bb0eef4be80c7c/app/src/main/java/io/heckel/ntfy/util/Util.kt#L87) via [`minPriority?.summaryProvider`](https://github.com/binwiederhier/ntfy-android/blob/fbf2a75e0d8a3f8dd37e065c7ddc3b2a291beb4d/app/src/main/java/io/heckel/ntfy/ui/SettingsActivity.kt#L197).

**Comment by binwiederhier** [comment]
Good catch. Will be easy to fix too.

**Comment by binwiederhier** [comment]
Done in https://github.com/binwiederhier/ntfy-android/commit/f35c598ae8e58d4f7b772b83bbba2fdc911e27b6
