### ISSUE TITLE
Android app: Validate server URLs

### ISSUE THREAD

**Issue by StoyanDimitrov** [binwiederhier/ntfy#193]
Make proper URL validation of the user input in:
- default server
- new user for new server

Currently one can add invalid characters in those server URL fields.

**Comment by binwiederhier** [comment]
Solved in https://github.com/binwiederhier/ntfy-android/commit/fc27b0ce99c47f0e73b8b811e2ad1aa022a2bdc0

**Comment by binwiederhier** [comment]
Note: I opted for keeping a very simple URL validation (basically anything starting with `http?://...`), because it's too hard and not worth it to do anything else.
