### ISSUE TITLE
Expose port 80 so traefik can pick it up automaticlly

### ISSUE THREAD

**Issue by RasHas** [binwiederhier/ntfy#195]
Currently traefik needs to be specifically told to which port to forward the traffic. Adding `EXPOSE 80` to docker file allows traefik to automatically detect the port. And it is a good practice anyways.

**Comment by binwiederhier** [comment]
Done in https://github.com/binwiederhier/ntfy/commit/611894fd05133dc2e32ca29a2fed73d5269f94ea, will be in next release.

**Comment by zombiehoffa** [comment]
I apologize for commenting on this closed issue but github doesn't seem to have any way else to contact shard. Shard, can you share your working traefik config? I'm trying to get this going now and can't seem to get it to work.
