### ISSUE TITLE
Android app: Allow translation of fastlane metadata

### ISSUE THREAD

**Issue by StoyanDimitrov** [binwiederhier/ntfy#198]
[Sample configuration](https://hosted.weblate.org/projects/catima/fastlane/#information). Keep in mind that there are [issues](https://github.com/WeblateOrg/weblate/issues/5522) with some language codes.

**Comment by binwiederhier** [comment]
As requested https://hosted.weblate.org/projects/ntfy/android-fastlane/

It's only 3 strings though. Not sure why the changelogs don't show up. But the changelogs would be pretty tedious anyway I think.
