### ISSUE TITLE
Opening ntfy.sh link in a browser on Android opens the app and subscribes to the topic if the app is installed

### ISSUE THREAD

**Issue by Copephobia** [binwiederhier/ntfy#20]
A scenario may be:

- I have the ntfy.sh app installed on my Android device
- A browser page or application (like Slack) has a URL to a ntfy.sh topic

If I click on the ntfy.sh link, it will attempt to open the app and subscribe to the topic, so that I can view it from there.

If I do not have the ntfy.sh link, it will display the web page for that topic.

**Comment by binwiederhier** [comment]
I like this idea. Nad it should not be hard to implement.

**Comment by binwiederhier** [comment]
Re-opening this, since I removed the feature in the latest commit. Android is not allowing me to register reg-ex patterns of URLs and the wildcard stuff seems incredibly buggy. I spent two+ hours with it yesterday and it's not worth it for now.

**Comment by gc-ss** [comment]
Let's simplify it first?

1. Instead of handling http(s) links, let the app respond to `ntfy` links and the app registers to handle `ntfy` links
2. Have a little text template that spits out the http(s) links and the `ntfy` link to send to people (instead of just http(s) link)

Is this a possibility?

**Comment by binwiederhier** [comment]
I wrote a whole long paragraph about why that's difficult and then I read your comment again. You just want a Share button that prints two links, one of which will open the app?

I don't know if Android will highlight and let you click ntfy:// links, probably not, but it's worth a try definitely. 

And we'd still need a solution for the web UI.

**Comment by gc-ss** [comment]
> I wrote a whole long paragraph about why that's difficult and then I read your comment again

Philipp, then I did a poor job of conveying my intention. In case you happen to have that paragraph, I would really appreciate reading it. If it's gone, can you just type in the highlights so I can figure out what disconnect existed (before you read my comment again)?

> You just want a Share button that prints two links, one of which will open the app?

Right. My thought is that the app can register itself with `ntfy://` links and have greater control

> And we'd still need a solution for the web UI.

I believe we can still use `ntfy://` links or something similar (the client app can register itself with `ntfy://` links)

**Comment by 12nick12** [comment]
I'm not a dev, but going from what has been spoken in the issue and my limited knowledge of stuff, you could just add a ntfy: link in the web page if you can get ntfy app to open ntfy: links. Kind of link how tel: opens the dialer and mailto: opens email.

**Comment by binwiederhier** [comment]
That would be easy to do, but then it looks horribly broken for people that don't have the app installed.

**Comment by 12nick12** [comment]
You could word something like "if you have the app installed hit THIS link"

**Comment by jhotmann** [comment]
For me, having the app able to handle `ntfy://` links would be enough as I mainly just want to be able to open the app to a specific topic via Tasker. But having a `ntfy://` link show up if you open a topic when opened in a mobile browser could also be handy.

I wrote a custom Owntracks server implementation and part of it includes device configuration generation. It creates an `owntracks://` links with the configuration data base64 encoded and is clickable from the Android and iOS browsers. The links aren't highlighted/clickable in messaging and other apps, though.

**Comment by binwiederhier** [comment]
Sorry I never responded to this. This sounds easy enough. I should be able to whip that up at some point. There are just so many tickets :-D

**Comment by binwiederhier** [comment]
(I'm starting work on this)

So if I implement `ntfy://ntfy.sh/mytopic` that opens the topic in the Android app and subscribes to it, that would be enough?

I wonder if I should structure the link differently, so that other actions are supported in the future, like `ntfy://ntfy.sh/mytopic?action=subscribe`, or `ntfy://subscribe/ntfy.sh/mytopic`, ...

I suppose I could iterate on it, so I think I'll just start with `ntfy://ntfy.sh/mytopic`.

**Comment by binwiederhier** [comment]
Done. Will be in the next Android release. Added docs too, which will be in the next server release:

![220412 20-09-42 Selection 001](https://user-images.githubusercontent.com/664597/163074449-a66deba4-2090-47ff-addf-f031cc802cc6.png)

**Comment by adebisi-fa** [comment]
Hi @binwiederhier,

Thanks for this great piece of work. ntfy is awesome!

Could we have the subscription's appearance setting (e.g. name and icon) configured via ntfy: // protocol, also? 

Something like this:

`ntfy://<hostname>/<topic>?name=<SubscriptionName>&icon=<IconUrl>&secure=<true|false>`

It would be a great addition!

Thanks once again for this great project.

**Comment by e0548965** [comment]
Did you manage to do this  @reslin ? We'd like to be able to set the subscription name to something more user friendly.

**Comment by reslin** [comment]
> Did you manage to do this [@reslin](https://github.com/reslin) ? We'd like to be able to set the subscription name to something more user friendly.

Sorry, I did not pursue the topic further.
