### ISSUE TITLE
Web App: Strings with issues

### ISSUE THREAD

**Issue by StoyanDimitrov** [binwiederhier/ntfy#203]
- `notifications_loading` aren't we talking about *messages* everywhere in the web app UI?
- `publish_dialog_attachment_limits_quota_reached` missing space after the comma
- what are the gotchas when translating `publish_dialog_delay_placeholder`?

**Comment by binwiederhier** [comment]
> notifications_loading

It's a horrible mix of "message" and "notification". I see that now. 

The pubsub protocol calls it message, but the UI typically calls it notification. But a notification has a message in the JSON, so :shrug: Let me review it all.

> publish_dialog_delay_placeholder

"tomorrow, 9am" -- Only English is supported, so I'd leave that.

**Comment by binwiederhier** [comment]
I think I fixed the notification/message thing and your other comments, as per https://github.com/binwiederhier/ntfy/commit/d2f933e15f51d6852af8af44ddadc2c90b3ac108

"Message" only appears now when the message body is referenced.

**Comment by StoyanDimitrov** [comment]
I feel like `prefs_notifications_min_priority_title` - "Minimum priority" needs some explanation. It's not immediately clear where this setting applies. The Android app has brief description that gives the needed context.

**Comment by binwiederhier** [comment]
> "Minimum priority" needs some explanation.

Hmm. You may be right. I'd have to add some detailed description text for each of the settings. Let me think about how to do that in the UI :thinking:

**Comment by binwiederhier** [comment]
![220409 19-16-25 Selection 001](https://user-images.githubusercontent.com/664597/162594677-2a07b20a-da07-456b-bcd9-94949fdf7cc2.png)

What do you think?

**Comment by StoyanDimitrov** [comment]
Looking good. It's nice addition.

**Comment by StoyanDimitrov** [comment]
Is it possible on `notifications_no_subscriptions_description` (Click the "Add subscription" link to create or subscribe to a topic. After that, you can send messages via PUT or POST and you'll receive notifications here.) to use placeholder with the actual button label - `nav_button_subscribe`? The text of the button already changed to "Subscribe to topic".

**Comment by binwiederhier** [comment]
Done.

**Comment by binwiederhier** [comment]
I'll close this for now, but you can keep adding if you find more issues.
