### ISSUE TITLE
Web app: Sending test notification doesn't create proper 403 error

### ISSUE THREAD

**Issue by cmeis** [binwiederhier/ntfy#205]
When trying to send a test notification to a topic where the user has no write access, there's no error message at all in the GUI.

The browser console shows the 403 error not being processed:

![image](https://user-images.githubusercontent.com/1850168/162538358-88823c05-330e-48fa-9770-10a589073a40.png)

There should be some kind of error message to the user.

**Comment by binwiederhier** [comment]
Good catch. Should be easy to add a snack bar message.

**Comment by binwiederhier** [comment]
Fixed inhttps://github.com/binwiederhier/ntfy/commit/448444eccfbba647084625cced770efa30ee7968
