### ISSUE TITLE
Optionally propagate message deletions

### ISSUE THREAD

**Issue by arminus** [binwiederhier/ntfy#207]
Suppose I'm subscribed to a topic form several devices and I've read some message on one of them. 

Now it would be nice to be able to "globally" delete the message - as an option to the local delete for the device I've read the message on.

As it is, I have to manually clear the message(s) from other devices, too.

**Comment by binwiederhier** [comment]
This is a dup (or at least closely related) to #159, #43 and #17. 

I had started work on this and it got quite complex. If people really want deletes and updates I'll do it...

**Comment by arminus** [comment]
Sorry, missed that. Feel free to close. For now, I'm using to_<device> topics to avoid that.

**Comment by binwiederhier** [comment]
It comes up every now and then, so I think it's unavoidable. Maybe upvote the other tickets to show you're interested. That's how I sometimes figure out what to do next

**Comment by arminus** [comment]
Closed in favor of #159
