### ISSUE TITLE
Android app: Error in sending test notification

### ISSUE THREAD

**Issue by StoyanDimitrov** [binwiederhier/ntfy#209]
The error is `Unexpected char 0x41f at 0 in X-Title value: ...`. The actual value is the test titlе `detail_test_title` (Проба: Ако желаете можете да сложите заглавие). There seems to be no related info in the logs.

The error does not occur every time, but quite regularly.

Steps to reproduce:
- switch to Bulgarian
- subscribe to topic
- send several test notifications

**Comment by binwiederhier** [comment]
Ah yes. I know how to fix this. Thanks for the bug report.

**Comment by binwiederhier** [comment]
(Note to self. This is in the Android app, not the web app! Drove me crazy just now trying to reproduce this.)

**Comment by binwiederhier** [comment]
Fixed in https://github.com/binwiederhier/ntfy-android/commit/e600d1550509b0e48c77e2473b45855b263534a8
