### ISSUE TITLE
Use Dockerfile from scratch

### ISSUE THREAD

**Issue by genofire** [binwiederhier/ntfy#213]
You deploy an golang application, it is not necessary to use a complete alpine in it.

https://chemidy.medium.com/create-the-smallest-and-secured-golang-docker-image-based-on-scratch-4752223b7324

It makes the image more secure and smaller.

**Comment by binwiederhier** [comment]
Closing this as per https://github.com/binwiederhier/ntfy/pull/270#issuecomment-1139889432
