### ISSUE TITLE
healthchecks.io like webUI needed

### ISSUE THREAD

**Issue by pinkworld123** [binwiederhier/ntfy#218]
Hello,

https://healthchecks.io/ like web UI needed for monitoring notification on demand bases so no need to read notification all the time. 

so nfty can be used as replacement of healthchecks.io.

thanks

**Comment by binwiederhier** [comment]
If I understand you correctly, you want a different UI that looks like this? If so, what's so special about this UI that ntfy doesn't have? If you don't want to receive the "OK" notifications, then make the "OK" messages low priority, and the "NOT OK"  messages high priority, and set the "minimum priority" in the settings to ">= default". That way you'll only receive the bad stuff.

Also, healthchecks.io is a vastly different tool, and has more features (it can detect things like "down for x minutes", or "failed x checks"). ntfy cannot do that. 

![image](https://user-images.githubusercontent.com/664597/164516950-43dfc533-6fb5-44a4-938d-2e1fb7086400.png)

(There is another ticket about healthchecks.io (#49), though I believe it's an entirely different ask.)

**Comment by binwiederhier** [comment]
I'm going to close this, because I didn't get a response in a while and I don't think it seems like a thing that ntfy should do anyway. Feel free to comment or reopen if you feel differently.
