### ISSUE TITLE
ntfy notifications are grouped together with the sticky one

### ISSUE THREAD

**Issue by s-h-a-r-d** [binwiederhier/ntfy#219]
Currently all ntfy notifications are grouped together with the sticky notification. Because of that it is not possible to clear all ntfy notifications at once.

Looks like this bit of documentation may have a solution to that problem: https://developer.android.com/training/notify-user/group

**Comment by binwiederhier** [comment]
After many hours of trying to figure out how to group topics together, and many frustrations, I found a way to _just_ put the sticky notification in its own group, which ultimately makes it possible to clear the others all at once.

**Comment by binwiederhier** [comment]
Fix in https://github.com/binwiederhier/ntfy-android/commit/a04c1790eccae369c276344ccb63fd5eeeef4a14

Will be in next release.
