### ISSUE TITLE
ntfy GitHub org

### ISSUE THREAD

**Issue by binwiederhier** [binwiederhier/ntfy#22]
Hey @ntfy, if you're reading this, would you be willing to give up your username, so I can create a GitHub org for this project. Looks like you're not using the GitHub account anyway. I'd be willing to buy you a coffee or the like for your troubles.

**Comment by aslmx** [comment]
ntfy.sh seems free :thinking: not?
Or are dots not allowed in orgnames?

**Comment by binwiederhier** [comment]
Yeah dots are not allowed. `ntfysh` maybe, but idk...

**Comment by aslmx** [comment]
notify-ish :D

**Comment by binwiederhier** [comment]
I registered https://github.com/ntfysh and https://github.com/ntfy-sh, but I think for now I won't move the project. I don't like either org names particularly.

**Comment by binwiederhier** [comment]
I reached out to GitHub support regarding @ntfy and they said they don't respond to name squatting requests anymore. It's rather unfortunate, but I think we're out of luck.

**Comment by binwiederhier** [comment]
I have reached someone who knows someone at GitHub and they're gonna look at in in January when they're back from PTO.

**Comment by binwiederhier** [comment]
I have reached out to 2 people at GitHub without success. They all direct me to support which I've already tried. Sadly I think this is a lost cause. Closing this for now.
