### ISSUE TITLE
Android app: parameter "clear" for action button doesn't work with action "view"

### ISSUE THREAD

**Issue by cmeis** [binwiederhier/ntfy#220]
Android app (test build from Discord / https://phil.nopaste.net/T7d7JOvNRH?d=1&f=app-play-debug.apk&a=uVxXKVl4wn) is not behaving correctly with "view" action and the "clear" parameter set to true.
In this case my app clears the notification, but does NOT execute the "view" action.

Example request:
```
{
    "topic": "transfer",
    "message": "I got a new pickup point",
    "actions": [
      {
        "action": "view",
        "label": "meet me here",
        "url": "geo:47.421087468386155, 10.985437463216053",
        "clear": true
      }
    ]
  }
```
If the "clear" parameter is set to false (or not set at all, as false is the default), the action is executed.

**Comment by binwiederhier** [comment]
Fixed in https://github.com/binwiederhier/ntfy-android/commit/e4255212effc2865fbdfc77b637e7b43a2fa0b97
