### ISSUE TITLE
Android app: action button with action "http" and method GET produces incorrect error

### ISSUE THREAD

**Issue by cmeis** [binwiederhier/ntfy#221]
The Android test app (test build from Discord / https://phil.nopaste.net/T7d7JOvNRH?d=1&f=app-play-debug.apk&a=uVxXKVl4wn) is behaving incorrectly with an action button of type "http" and method set to "GET". 
The notification is sent to the app.
When clicking the action button in the notification the request is not sent and an error message is displayed: "unlock door failed: method GET must not have a request body" - but there is no request body defined.

This is an example notification request:
```
{
    "topic": "transfer",
    "message": "pizza delivery arrived",
    "actions": [
      {
        "action": "http",
        "label": "unlock door",
        "url": "https://my.door.lock/open-sesame",
        "method": "GET",
        "clear": true
      }
    ]
  }
```

**Comment by binwiederhier** [comment]
Fixed in https://github.com/binwiederhier/ntfy/commit/b805d49cfd4ca66c37c1a857035a27abcf1e3ccf and https://github.com/binwiederhier/ntfy-android/commit/4ad68468023d84fb147582b814fa64f06702936c
