### ISSUE TITLE
Remove permanent notification when all notifications are paused

### ISSUE THREAD

**Issue by shadow00** [binwiederhier/ntfy#224]
Would it be possible to disable the permanent notification when all topic subscriptions have their notifications paused? Either globally or individually (ie. notifications are not globally paused, but all subscribed topics have been individually paused). This would help reduce notification clutter when ntfy is effectively not doing anything.

**Comment by binwiederhier** [comment]
You can manually hide the sticky notification. There are instructions here: https://ntfy.sh/docs/subscribe/phone/#instant-delivery

When you pause a subscription, ntfy will still listen for incoming notifications. It'll just not display them. So ntfy is definitely not idle. That's a misunderstanding on your part. 

I hope this helps.

**Comment by shadow00** [comment]
Oh, I did not expect the app to keep listening for notifications on paused topics...

What if the app only listened in the background for non-paused topics, and fetched notifications for paused topics only when the user manually opens the app (or maybe even the actual topic)?  
That way, you don't even need to start the background service if all topics are paused (in the spirit of "don't do something unless the user explicitly asks for it"), and the app's behaviour matches the user's (or maybe just mine? 😄 ) expectation of "paused" (ie. "stop listening to this topic").

(Just thinking out loud - perhaps going this far isn't really worth the effort?)

**Comment by shadow00** [comment]
I agree, "mute" would be an accurate description of the current behaviour.

**Comment by binwiederhier** [comment]
https://github.com/binwiederhier/ntfy-android/commit/0a446545dd436d9bf8743b8a193fe2cb4162979e
https://github.com/binwiederhier/ntfy-android/commit/835ace34cd94463f243b51a04349f178ef9ba07d

I'm closing this for now. Thank you for reporting!

**Comment by Elu43** [comment]
> You can manually hide the sticky notification. There are instructions here: https://ntfy.sh/docs/subscribe/phone/#instant-delivery

@binwiederhier Hi. It's probably a stupid question, but if you do that, will the notifications still be in "Instant delivery" mode ?

Thank you for your amazing software.

**Comment by binwiederhier** [comment]
> @binwiederhier Hi. It's probably a stupid question, but if you do that, will the notifications still be in "Instant delivery" mode ?

Notifications will still be instant yes. It just hides the sticky notification. Sorry for the super late reply.
