### ISSUE TITLE
Add VPN-only settings option

### ISSUE THREAD

**Issue by dcousens** [binwiederhier/ntfy#241]
When using a self-hosted server, for many configurations it may only be accessible when connected to your VPN.

Rather than relying on DNS resolution to fail (for example, if using `.home.arpa` for your domain names), there could be a settings option that prevents the foreground service from connecting unless a VPN is active.
This isn't fool-proof, especially if you use multiple VPN's, but it could prevent/reduce any DNS requests until the device is ready.

In addition to providing a CA certificate for authentication as in https://github.com/binwiederhier/ntfy/issues/215, this would reduce your device from making unnecessary outgoing connections.

**Comment by MuratovAS** [comment]
I have not met such a function in other applications. I think she is excessive.
If you want your DNS provider does not see requests when the VPN disconnected, use the firewall.
It allows you to configure the application only to work through VPN.
https://f-droid.org/en/packages/dev.ukanth.ufirewall/

**Comment by dcousens** [comment]
@MuratovAS you're probably right,  this may just be a manifestation of my frustration at the Android ecosystem.
Happy to close if you think this is out of scope @binwiederhier.
