### ISSUE TITLE
Cannot `make web` from release tarball 1.22.0

### ISSUE THREAD

**Issue by oddlama** [binwiederhier/ntfy#253]
This is the output of `make web` on my system after extracting the 1.22.0 release tarball. There seem to be two separate issues.

Firstly, something complains about the extracted contents not being a git repository (doesn't seem to cause any failure though, I guess it's from the first line in the Makefile).

Secondly, the build fails as the `react-scripts` executable cannot be found. Is this a dependency that isn't listed in the documentation, or am I missing something else?

```
fatal: not a git repository (or any of the parent directories): .git
cd web && npm install
cd web \
	&& npm run build \
	&& mv build/index.html build/app.html \
	&& rm -rf ../server/site \
	&& mv build ../server/site \
	&& rm \
		../server/site/config.js \
		../server/site/asset-manifest.json

> ntfy@1.0.0 build
> react-scripts build

sh: line 1: react-scripts: command not found
make: *** [Makefile:92: web-build] Error 127t:ctor Completed in 1ms
make: *** Waiting for unfinished jobs....
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.

added 1413 packages, and audited 1414 packages in 31s

183 packages are looking for funding
  run `npm fund` for details

6 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
npm notice 
npm notice New minor version of npm available! 8.8.0 -> 8.10.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.10.0
npm notice Run npm install -g npm@8.10.0 to update!
npm notice 
# If this fails for .svg files, optimizes them with svgo
```

**Comment by binwiederhier** [comment]
I haven't done a clean install in a while, so it is definitely possible that I missed something. I do think that the last time I tried it it was working nicely even with the new web app.

`react-scripts` is "Create React App", which I thought was gonna be installed when you do "npm install". Maybe I was wrong. Thanks for the bug report.

**Comment by binwiederhier** [comment]
I tried it in a Docker and it seems to work: https://asciinema.org/a/494722

I hate to say it, but this must be your environment. Let me know if you figure it out so I can adjust the docs, or join the Discord/Matrix. Maybe someone there can help with your specific problem. We're always happy to help.

It's not a bug though, so I'm going to close the ticket. Thank you for using ntfy. :-D

**Comment by oddlama** [comment]
I respectfully disagree with this not being a bug and would be happy if you could review #257.

**Comment by binwiederhier** [comment]
I agree with your assessment that my assessment of the situation was incorrect. ;-)

**Comment by binwiederhier** [comment]
This was released yesterday. Thanks for the contribution.
