### ISSUE TITLE
Unable to host on a subdirectory.

### ISSUE THREAD

**Issue by pollen00** [binwiederhier/ntfy#256]
Despite the base url option, when hosting somewhere that isn't the root directory, it will still load resources as if it was in the root directory.

**Comment by binwiederhier** [comment]
Thank you for reporting.

I have tried semi-hard (may an hour of trying) to make the React app work with relative paths, when not all resources are embedded via JS import statements, nad it drove me up the wall. I figured nobody was asking for it yet so I shrugged it off. 

I suppose I'll have to try again.

**Comment by binwiederhier** [comment]
Honestly I don't think I'll do this. It's tricky to know what will break with this and I think honestly it's not worth it. People have been fine so far, so I don't think it'll be too bad not to do this.

**Comment by terrytw** [comment]
Just want to leave a note that people can make do but it is definitely not fine....

**Comment by falkheiland** [comment]
> Just want to leave a note that people can make do but it is definitely not fine....

what purpose has your post, if you do not provide a way to do it?

**Comment by terrytw** [comment]
> > Just want to leave a note that people can make do but it is definitely not fine....
> 
> what purpose has your post, if you do not provide a way to do it?

First of all, I'm not here to argue with you, I am just going to answer your question as is, and move on. 

From my understanding, an issue or a ticket is where people discuss about a feature or a bug, and all kinds of people can participate as long as they provide feedback that positively contributes to the progression of said issue. This feedback is not necessarily limited to "provide a way to do it", just like in a normal project, PM, QA, dev, and marketing can all chime in from their perspective. 

My post is just my feedback on the importance of this issue. I am not trying to force anything upon anyone, I just hope maybe when the maintainer got some free time and he may or may not think about this and give it another go. Maybe the possibility of him giving it another go increases a little bit based on my feedback. 

I always have great appreciation towards people who work on open source projects. English is not my first language, so if my post came out wrong, it is not my true intention.
