### ISSUE TITLE
Android Notification not opening the right topic

### ISSUE THREAD

**Issue by SMAW** [binwiederhier/ntfy#261]
I think this is a bug, but when I leave the Android app in /topic1 and receive an notification for /topic2 and click on the notification, the app opens in /topic1 and not /topic2 as expected.

**Comment by wunter8** [comment]
I was not able to reproduce this. Can you send a video/screencast showing the problem @SMAW?

**Comment by binwiederhier** [comment]
It happens to me too. It's definitely real. Not sure what's going on. I'll try to send you some details later.

**Comment by binwiederhier** [comment]
I tried this too in the emulator but I couldn't reproduce it there either. I've definitely seen this happen.

**Comment by wunter8** [comment]
After some testing today, it seems like whenever you click on a notification, it will open whatever topic that received the most recent notification. It doesn't seem to care about what topic you were looking at before or what notification you clicked on.

For example, after running `curl localhost:8000/topic1; curl localhost:8000/topic2; curl localhost:8000/topic3`, the app will open to `topic3` when you click on any of the three notifications, even if you dismiss the `topic3` notification before clicking on one of the other notifications.

I'm going to try digging into the code to figure out why this is

**Comment by binwiederhier** [comment]
I can confirm that this happens in the SDK 33 emulator.

**Comment by binwiederhier** [comment]
Fixed here: https://github.com/binwiederhier/ntfy-android/commit/3d1d062f4d392516068e607586c4d413f71948b8
