### ISSUE TITLE
deeper deep links don't work

### ISSUE THREAD

**Issue by Curid** [binwiederhier/ntfy#271]
When the link is clicked the app briefly opens then closes.

`ntfy://my.domain.com/topic` Works.

`ntfy://my.domain.com/api/topic` Doesn't work.

`ntfy://my.domain.com/api/ntfy/mytopic` Doesn't work.

**Comment by binwiederhier** [comment]
Where'd you get the idea that the other two links should work. The docs only describe the first link as valid: https://ntfy.sh/docs/subscribe/phone/#ntfy-links

**Comment by Curid** [comment]
Sorry, I forgot the `//` part in the third link.

Why shouldn't it work? Putting `https://my.domain.com/api/ntfy/mytopic` in manually works.

**Comment by binwiederhier** [comment]
I saw your PR, but I am sorry to say, I have no interest in making these links extend to support relative paths like that, at least not until I have official support for relative paths in ntfy (which I am also not really sure I want).

Right now I am focusing my energy on iOS and I won't merge this any time soon.
