### ISSUE TITLE
iOS: Support auth

### ISSUE THREAD

**Issue by binwiederhier** [binwiederhier/ntfy#277]

**Comment by binwiederhier** [comment]
I've begun work on this here: https://github.com/binwiederhier/ntfy-ios/pull/6

Screenshots in Discord

**Comment by binwiederhier** [comment]
This is done

**Comment by mikniche** [comment]
This is fantastic - will a new version of the app be pushed to the app store/test flight to test this?

**Comment by binwiederhier** [comment]
I have a bunch of other things in the milestone (https://github.com/binwiederhier/ntfy/milestone/1), nad I was gonna see if I can at least do some of them before doing another TestFlight release. Couple of days
