### ISSUE TITLE
xcode compatible for Version 12.4 (12D4e) and below. 

### ISSUE THREAD

**Issue by Nllii** [binwiederhier/ntfy#283]
Can the ios app get a compatible turned on for Xcode  Version 12.4 (12D4e). 

Reason: for people who I can't upgrade Xcode due to Apple planned obsolescence. The last time I upgraded my MacBook pro I had to revert back to Catalina, the kernel hang, the light ambient sensors turn my computer off and on. 
I called Apple and the Rep told me this " Buy a new MacBook".  A good Intel Core i7 with 8GB can't upgrade it. 
I can just use patches and hacks in  Xcode projects.

**Comment by binwiederhier** [comment]
Hi @Nllii, thanks for thinking about contributing to ntfy. I don't know if I can make it compatible, but I can't submit with it afaik, because of this: https://developer.apple.com/news/?id=2t1chhp3. Don't know if the two are mutually exclusive.

**Comment by Nllii** [comment]
Thanks, please make it compatible for hobbyist if you can. No way, I am buying a new MacBook for Xcode. Thats insane.

**Comment by binwiederhier** [comment]
You are of course welcome to contribute code yourself to make it compatible. If it looks like a reasonable change I'm more than happy to merge it. I won't, however, dedicate any time on this myself. I've got so much other stuff to do. :-D

**Comment by Nllii** [comment]
Its okay. I am in the beta and can use iOS 14.  Thanks again.
