### ISSUE TITLE
Web, iOS, Android: Allow hiding topic names in UI

### ISSUE THREAD

**Issue by artemislena** [binwiederhier/ntfy#291]
L: Given topic names are meant to be secret, it would be nice if they could be hidden from the UI via a button or the like. I mean, of course you can use access controls to require a user/password combination for certain topics, but that doesn't work for everything, e.g. when you're using Unified Push, you need to allow all UP users read access to `up*` (and everyone write access), because there's no way to know the topic name beforehand. So some button/setting to hide all or some topic names would be pretty helpful, I guess. Perhaps even some alias functionality, so you could still tell from the UI what it is, without revealing to others (e.g. shoulder surfers or people you share screenshots with where you forgot to redact something) how to access it.

**Comment by Mikaela** [comment]
I have this issue with iOS notifications as when it's configured to show Ntfy notification content even during locked screen, the topic is visible at first and while mine is long enough to get cut, 4/5 of it is visible and the end may be guessable.

I am using the topic in question for SSH login notifications.

**Comment by artemislena** [comment]
L: I'll have to respectfully disagree with closing this issue. Firstly, the PR only "solved" it for Android, secondly, it didn't really solve it, I think, because there's no way to apply this to Unified Push topics on Android, afaik, because you can't access their settings (unless that was changed with the update, too).

**Comment by binwiederhier** [comment]
This was auto-closed by GitHub because it mentions "fixes TICKET NUMBER" in the commit or comment.

**Comment by binwiederhier** [comment]
I'm closing this since you can now have display names in the web app, Android (including UP topics). I added a follow-up ticket for iOS: https://github.com/binwiederhier/ntfy/issues/357
