### ISSUE TITLE
Missing Accessibiltiy Label for Checkbox

### ISSUE THREAD

**Issue by mhameed** [binwiederhier/ntfy#292]
Hi Phillip

Sorry for the delayed response, I finally managed to get a screen a shot of the screen that has a missing label, please see attached
From my friend's description this is a delete/clear form button can we please label it with something descriptive.

Thanks
Mesar

**Comment by binwiederhier** [comment]
Did you by any chance also try the web app. I didn't really know what to do but I gave it my best.

**Comment by binwiederhier** [comment]
Closed in https://github.com/binwiederhier/ntfy-android/commit/eabb163fde0a6ad3dbe7a5c8e4e4224b5dc4db1d and will be in the next release

**Comment by binwiederhier** [comment]
@mhameed I turned on TalkBack on Android to test this, and it drove me nuts. I guess it's just getting used to, and if you have no other choice. I hope it's a better experience for you as it was for me. Or at least I hope there are other options...
