### ISSUE TITLE
iOS: Header font size flickers when viewing the list of messages

### ISSUE THREAD

**Issue by prabirshrestha** [binwiederhier/ntfy#293]
If the topic in the title bar is long, the header flickers when initially viewing the list of the messages. It feels as if the font size start small and when the loading completes the fontsize is bigger.

Even better if you can make the title bar in two lines one for topic and one for server. Currently my selfhosted domain is a bit long so usually I see `ntfy.home.mydomain.com/abcd...` Notice how I only see 4 characters for the topic.

**Comment by binwiederhier** [comment]
@prabirshrestha Is it still flickering in v1.2? I am pretty sure I fixed it.
