### ISSUE TITLE
iOS: Ability to remember servers

### ISSUE THREAD

**Issue by prabirshrestha** [binwiederhier/ntfy#295]
My domain is a bit long `ntfy.home.mydomain.com` and it is not fun to type on an ios device. Please add the capability to remember `Use another server` and `Server URL`.

Even better if there is a capability to add/remove server as I see myself using ntfy in home server and on the cloud.

It would be good if there was an opt-in option to sync the list using [cloudkit](https://developer.apple.com/documentation/coredata/mirroring_a_core_data_store_with_cloudkit/syncing_a_core_data_store_with_cloudkit). (can probably be a different issue)

**Comment by binwiederhier** [comment]
Thank you for the feature request.

The Android app has that feature, and even the ability to select a "Default server" in the settings. I plan on implementing it the same way. I will not implement any other services (such as cloudkit) though. That feels a little too much.

**Comment by binwiederhier** [comment]
Done (default server, not other servers).
