### ISSUE TITLE
add support for making a topic as listed or unlisted similar to youtube

### ISSUE THREAD

**Issue by prabirshrestha** [binwiederhier/ntfy#298]
add support for making a topic as listed or unlisted similar to youtube https://support.google.com/youtube/answer/3127309?hl=en. 

Feature | Unlisted | Private | Public
-- | -- | -- | --
Can share URL | Yes | No | Yes
Can be added to a channel section | Yes | No | Yes
Shows up in search, related videos, and recs | No | No | Yes
Posted on your channel | No | No | Yes
Shows in Subscriber feed | No | No | Yes

All I have to tell my family members now is download ntfy app, add the server and susbscribe to whatever topics you are interested in. Will probably want to support capability to add/remove servers first - https://github.com/binwiederhier/ntfy/issues/295

**Comment by binwiederhier** [comment]
While this is an interesting concept, it doesn't really fit into ntfy's model well. All interactions in the apps are topic specific. We do not log into a server or or add servers to the app. I'd have to change the paradigm to make it more server-centric. 

The one appeal this would have is that I could much more easily promote the stats and announcement topics on the ntfy.sh server. For now I will close this as "wont do". Thanks for the idea.
