### ISSUE TITLE
UTF8

### ISSUE THREAD

**Issue by manson** [binwiederhier/ntfy#3]
Is it possible to process utf-8 encoding? Say, I've sent russian strings and gets bad symbols. Take a look at [ntfy.sh/manson_alerts ](https://ntfy.sh/manson_alerts) channeln you'll see it.

**Comment by binwiederhier** [comment]
UTF-8 and even emojis are supported so I'm a little confused how that happened. Can you tell me what command you ran exactly, and what terminal and OS?

**Comment by manson** [comment]
You're right. Under linux it works fine but failed as said above under windows 10 terminal

**Comment by binwiederhier** [comment]
@manson Can you tell me the exact command you ran under the Windows 10 terminal? If I can reproduce I'm sure I'll be able to help you out or fix it.

**Comment by manson** [comment]
@binwiederhier This is command from example, I've just changed the message.
curl -d "проверка" ntfy.sh/manson_alerts
Exactly this command later I've copied into the my remote linux box bash terminal and it sent message as it should.

**Comment by binwiederhier** [comment]
@manson So I will eventually try to replicate this on Windows, but I can only do that after work likely. 

In the meantime, here are my initial thoughts:

* I have had trouble with certain emojis when combining them with `curl -d`, e.g. `curl -d "⚠️ Warning" ntfy.sh/mytopic` does not work, but `echo -en "⚠️ Warning" | curl -T- ntfy.sh/mytopic` does. So it could be a "curl issue"
* I am also wondering if it could be the Terminal encoding in Windows. If that's not UTF-8 then you may get garbled text like that. I don't know how to check that on Windows, but that could be a good starting point for you.

**Comment by manson** [comment]
@binwiederhier thank you. Actually I dont care about windows - I just have temporary work here, but mostly work under linux so its ok for me

**Comment by binwiederhier** [comment]
I'll keep the ticket open then for now. I may get to it.

**Comment by binwiederhier** [comment]
Please reopen if there are more Windows UTF-8 issues
