### ISSUE TITLE
docs: clarify what actually is transferred to public servers such as Firbase/APNS and upstream server when using selfhosted server for ios

### ISSUE THREAD

**Issue by prabirshrestha** [binwiederhier/ntfy#300]
This is a bit confusing.

> The ntfy.sh server publishes the message to Firebase, which forwards it to APNS, which forwards it to your iOS device
Your iOS device receives the poll request, and fetches the actual message from your server, and then displays it

The ntfy.sh server publishes the message to Firebase. What is a message here? Is it just the poll id and topic hash?

Might be a sequence digram would be the best here?

**Comment by binwiederhier** [comment]
Thanks. 

(Hopefully) done in https://github.com/binwiederhier/ntfy/commit/17eabed11c453b8db5c03245d0451dd4deb4fe86
