### ISSUE TITLE
brew-Package would be nice

### ISSUE THREAD

**Issue by Grunerd** [binwiederhier/ntfy#309]
As suggested in the docs (https://ntfy.sh/docs/install/), I would love to see ntfy being installable through brew. The tinkering itself is not an issue, but it would of course safe people like me some time when setting up new systems, as well as while maintaining awesome tools like this. :) 

Thanks for the awesome work!

**Comment by binwiederhier** [comment]
I think this is a dup for #286, no?

**Comment by Grunerd** [comment]
Oh, my bad. I just searched the issues fro 'brew' and nothing showed up, hence I opened this. Yes. You are right, my bad, it's a dupe and can be closer.

**Comment by binwiederhier** [comment]
@Grunerd Happy to accept contributions :-)
