### ISSUE TITLE
Android: Display name

### ISSUE THREAD

**Issue by SingingDwarf** [binwiederhier/ntfy#313]
Given the topic name is supposed to be both unique and unguessable (UUID anyone?) it would be nice to be able to rename the topic to something meaningful within the Android UI.

i.e. the actual topic name used for the subscription could be a UUID, but the display name used with the Android app could be short, sweet and meaningful to the user (e.g. Laptop Backups)

**Comment by binwiederhier** [comment]
Indeed @Mikaela. This has been suggested before, by @SMAW I believe. I dismissed it the last time, but with now a total of 3 people suggesting it, I think it could be a good and easy addition.

**Comment by binwiederhier** [comment]
Will be in the next Android release. Screenshots in https://github.com/binwiederhier/ntfy-android/pull/35.

Thank you @wunter8
