### ISSUE TITLE
Add server version to web ui

### ISSUE THREAD

**Issue by poblabs** [binwiederhier/ntfy#314]
I had a thought today that it may be a good idea to show the server version somewhere. Maybe on the sidebar of the web ui?

**Comment by binwiederhier** [comment]
This is typically bad security practice, because in case there are security vulnerabilities, it makes it easy for an attacker to find vulnerable instances. What is the actual reasoning behind this? You want to make sure you're up to date? In that case, maybe set up `unattended-upgrades` or something similar for Docker?

**Comment by poblabs** [comment]
Good point and I had considered that before submitting the ticket. Yes just
a reference to always stay up to date. I'm currently not running this in
docker but rather as the standalone binary. Would it be possible maybe to
put the version once the binary starts up on console?

If not no worries.

**Comment by Mikaela** [comment]
I am not sure security by obscurity is that great practice and it may make clientside debugging/troublesholting more difficult if e.g. third party server by a friend gets used.

**Comment by binwiederhier** [comment]
It is best practice and part of layered security. Apache and nginx and Lal the others have settings to hide the version number in their response headers. 

I think @poblabs's problem is a different one and has been solved by packages (rpm/deb) or docker. 

If y'all really feel strongly I can add it and make it configurable, but I don't really think it's necessary. 

Adding it to the `ntfy serve` output though is not a problem.

**Comment by poblabs** [comment]
Adding it to ntfy serve console output would work just fine. Thanks!

**Comment by binwiederhier** [comment]
Done as part of https://github.com/binwiederhier/ntfy/commit/cf0f002bfa32eedb5ef4264a6c18ac3f2beecfa4

```
$ ntfy serve                              
2022/06/12 11:49:09 INFO Listening on :2586[http] :1025[smtp], ntfy v1.25.2-next, log level is TRACE
```
