### ISSUE TITLE
Self hosted behind NGINX Proxy Manager w/ Cloudflare Origin Certs

### ISSUE THREAD

**Issue by dafinga** [binwiederhier/ntfy#318]
Hi,

Hoping to get some help troubleshooting as I have reached the end of my ability to do so on my own. 

I am pretty inexperienced with some of the finer points of getting this up and running (am desperate to though, so cool!)

TLDR: Messages are not hitting my selfhosted server. 

Running the ntfy server behind Nginx Proxy Manger (NPM) on an Ubuntu 22.04 VM in Proxmox. 
Both nslookup & ping show the subdomain is reachable. 
SSL is configured using a Cloudflare Origin Certificate. 

I cant for the life of me get the server to receive messages via curl (all of my other hosted, exposed services are reachable outside of LAN). Setting Server log level to DEBUG confirms that it is not receiving the messages. 

I suspect it is something to do with cloudflare's certs/proxying, and adding custom config to NPM - but this is beyond my pay grade and I haven't found anything useful in GitHub/reddit/website.

Any help/pointers would be much appreciated!

server.yml config:

```
base-url: "https://medianotify.example.com"
listen-http: ":8090"
cache-file: "/var/cache/ntfy/cache.db"
cache-duration: "12h"
behind-proxy: true
upstream-base-url: "https://ntfy.sh" [planning on using with iOS app - amazing thats live in app store!]
log-level: DEBUG
```

**Comment by binwiederhier** [comment]
I'm sorry you're having a hard time. This is not the right place for troubleshooting issues with your setup though. I suggest you either ask in the ntfy chat (https://github.com/binwiederhier/ntfy#chat), or in the selfhosted subreddit. 

It is usually helpful to include output from commands you rand that fail, or logs of some kind. Without that, it's pretty much impossible to diagnose these problems.
