### ISSUE TITLE
FAQ docs iOS reference -> Why is there no iOS app (yet)?

### ISSUE THREAD

**Issue by milksteakjellybeans** [binwiederhier/ntfy#321]
A friendly reminder in case you want to update this documentation section:

https://ntfy.sh/docs/faq/#why-is-there-no-ios-app-yet

**Comment by binwiederhier** [comment]
Done in https://github.com/binwiederhier/ntfy/commit/eb2262d06e3308f85ba615ae1ba97a0f86691c41
