### ISSUE TITLE
Web UI with Ubuntu+Firefox - Web UI frozen after clicking view action with http link

### ISSUE THREAD

**Issue by milksteakjellybeans** [binwiederhier/ntfy#324]
When viewing a ntfy notification that has a view action button with http link, when clicking the action button, the appropriate link opens in a new tab.  But, upon returning to the ntfy web ui, the web is is frozen (with the hover over text still appearing regardless where the mouse pointer is) and must be refreshed to continue interactions.

This occurs with
Ubuntu (20.04.4 LTS) + Firefox (100.0.2)

I'm using default privacy / blocking options in Firefox.

But does not occur with:
MacOS (12.4 (21F79)) + Safari (Version 15.5 (17613.2.7.1.8))

**Comment by binwiederhier** [comment]
I have actually noticed this too. You are absolutely correct. Thank you for reporting.

**Comment by binwiederhier** [comment]
I have been trying to replicate it and it's not happening; it's really odd.

**Comment by milksteakjellybeans** [comment]
I'll try it again but need to upgrade my server instance to latest first, I'll reply back after I do that

**Comment by milksteakjellybeans** [comment]
Updated to ntfy 1.27.2 server, I can't reproduce this now

**Comment by binwiederhier** [comment]
I bet this was a bug in the MUI Link component. Let's close this and hope it doesn't come back. Thanks for checking.
