### ISSUE TITLE
Copyright holder is not specified in LICENSE file

### ISSUE THREAD

**Issue by ilyamikheevcoder** [binwiederhier/ntfy#33]
![изображение](https://user-images.githubusercontent.com/37904672/144754319-cfd1e723-005c-4d8c-a762-b26d13579d24.png)

**Comment by binwiederhier** [comment]
Thanks. Will fix right away.

**Comment by binwiederhier** [comment]
Fixed in https://github.com/binwiederhier/ntfy/commit/dadb6419ee3351b1a5f9aa6f87dde67b934e7b42 + https://github.com/binwiederhier/ntfy/commit/3daa590732c565a5292d840de513b216d9ad1c9e
