### ISSUE TITLE
`since` query parameter on subscription with multiple topics

### ISSUE THREAD

**Issue by karmanyaahm** [binwiederhier/ntfy#336]
From the chat:

What happens when there are multiple topics subscribed to, and since=id is used? For example, I'm requesting, `https://ntfy.sh/uptopic1,uptopicB,uptopicC3/json?since=myid1`. Now myid1 is of course only part of one topic. Will it be treated as a cutoff based on the time the messages arrived? or will it only filter messages from that one topic?

@binwiederhier wrote some tests and found some bugs in the implementation of this?
This issue exists to track that.

**Comment by binwiederhier** [comment]
Thank you! Fixed in https://github.com/binwiederhier/ntfy/commit/d05211648d4cd7115dc9be1b733102f30bddf675. Will be in v1.27.0.
