### ISSUE TITLE
Support Web Push + PWA, for background notifications

### ISSUE THREAD

**Issue by Mikaela** [binwiederhier/ntfy#346]
I am not sure what running as progressive web app requires, but I understand they should be able to support receiving notifications in the background even without the tab/app open as long as browser is running.

I think currently at least webapp manifest is missing.

* https://developer.mozilla.org/docs/Web/Manifest
* https://developer.mozilla.org/docs/Web/Progressive_web_apps
* https://caniuse.com/web-app-manifest (add to homescreen)

~~Somewhat unrelatedly, iOS is also receiving support for web push sometime next year, https://webventures.rejh.nl/blog/2022/06/25/the-biggest-thing-from-wwdc22/~~

Update 2023-04-02: iOS 16.4 supports web push when the PWA has been added to the homescreen.

**Comment by wunter8** [comment]
I've thought about trying to make this work. I think it might solve #199, too

**Comment by WebKenth** [comment]
Just thought i would leave my 2 cents

You can create a shortcut with chrome and have it opened as a separate window
![image](https://user-images.githubusercontent.com/13419123/178659286-8eda0e78-db7c-4f2e-8f84-ab54336d4304.png)
![image](https://user-images.githubusercontent.com/13419123/178659317-3fa2243c-9c87-4f5f-ad00-63e887ba8922.png)

This will give it a sorta PWA like feel, although it is still a chrome instance just running in a separate window

![image](https://user-images.githubusercontent.com/13419123/178659441-b13e91d4-408f-4678-862d-bc0cb941d2e3.png)

**Comment by MaximilianGaedig** [comment]
The browser asks me if I want to receive notifications, it works in the foreground but after closing the page it does not work anymore. Service workers need to be implemented.

**Comment by liamstojanovic** [comment]
Made progress in making the react web app fulfill install-ability requirements on the `pwa-background-push` [branch](https://github.com/liamstojanovic/ntfy-webApp/tree/pwa-background-push) of my forked repo.

No custom service workers are hooked up yet, nor have I managed to successfully install the PWA version so far. 

[Next steps...](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Re-engageable_Notifications_Push)

- Request permission,
- Generate notification,
- Push.

![Lighthouse PWA report](https://f002.backblazeb2.com/file/share-liam/lighthouse_pwa_report.png)

**Comment by gedw99** [comment]
> Made progress in making the react web app fulfill install-ability requirements on the `pwa-background-push` [branch](https://github.com/liamstojanovic/ntfy-webApp/tree/pwa-background-push) of my forked repo.
> 
> No custom service workers are hooked up yet, nor have I managed to successfully install the PWA version so far.
> 
> [Next steps...](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Re-engageable_Notifications_Push)
> 
> * Request permission,
> * Generate notification,
> * Push.
> 
> ![Lighthouse PWA report](https://camo.githubusercontent.com/f88e3dbe2e4e3f4816b63c6c5e161916bd0252ccd7d8474e9b45e31ccfddc95d/68747470733a2f2f663030322e6261636b626c617a6562322e636f6d2f66696c652f73686172652d6c69616d2f6c69676874686f7573655f7077615f7265706f72742e706e67)

Nice work !!

**Comment by BuckarooBanzay** [comment]
> Made progress in making the react web app fulfill install-ability requirements on the pwa-background-push [branch](https://github.com/liamstojanovic/ntfy-webApp/tree/pwa-background-push) of my forked repo.

Where are you planning to store the subscriptions from the client? Those have to be somewhere on the backend side :thinking:

**Comment by liamstojanovic** [comment]
I've hit a blocker with this endeavor.

I've made the web app install-able, and added appropriate views / preferences for enabling background notifications, but am lost when it comes to actually delivering notifications from the service worker itself, or how to go about listening for events that trigger a notification.

None of the classes in the `app/` directory can be imported into the service worker. Additionally, all of the examples I have seen online for enabling push notifications to be delivered from the service worker seem to leverage [PushManager](https://web.dev/push-notifications-subscribing-a-user/#subscribe-a-user-with-pushmanager) / [web push protocol](https://web.dev/push-notifications-web-push-protocol/). I do not know how to configure / incorporate this server logic into the existing web app code; plus, all the class instances in `app/` will cease to run once the PWA is closed.

**Comment by binwiederhier** [comment]
So I know nothing about PWA, but I looked at web push and the service worker stuff for a while (not sure if that's the same thing), and the more I looked, the more confused I got. 

It's been a while, so my memory is fuzzy, but luckily I can ping some experts, that can hopefully shed some light :-D

Pretty please, @p1gp1g @karmanyaahm (sorry for pinging you on two tickets :-))

**Comment by BuckarooBanzay** [comment]
> It's been a while, so my memory is fuzzy, but luckily I can ping some experts, that can hopefully shed some light :-D

(background: i've done this before and switched from my own webpush-~~spaghetty~~-app to ntfy, it is an awesome tool btw 😉 )

For webpush to work you need to generate a keypair, the public key is for the frontend and the private key is backend-only.
You also need to save the `subscriptions` from the frontend in the backend (somewhere in a database usually)
A subscription can be obtained by the `pushManager` in the browser.

This is a rough overview how a `subscription` is obtained on the frontend/browser side:
```js
if (navigator.serviceWorker){
	// service-worker registration (snippet below)
	navigator.serviceWorker.register('service-worker.js');

	// ready event
	navigator.serviceWorker.ready
	.then(function(registration){
		return registration.pushManager.getSubscription()
		.then(function(subscription){
			if (subscription)
				// already subscribed
				return subscription;

			// new subscription
			// public key from the backend
			return fetch("api/push/pubkey")
			.then(function(res){ return res.text(); })
			.then(function(vapidPublicKey){
				return registration.pushManager.subscribe({
					userVisibleOnly: true,
					applicationServerKey: vapidPublicKey
				});
			});
		});
	})
	.then(function(subscription){
		// TODO: store subscription object in the backend for later notification
	});

} else {
	//no push
}
```

A `subscription` looks like this:
```json
{
 "endpoint": "https://browser-dependent-url.com/xy",
 "keys": {
    "auth": "abcde--",
    "p256dh": "efgh=="
}
```

For the sending part in the backend you should really use a library, i can suggest this: https://www.npmjs.com/package/web-push

Sent notifications arrive in the `service-worker.js` and get dispatched to the user here:
```js
self.addEventListener('push', function(event){
	var payload = event.data ? event.data.text() : null;
	if (!payload)
		return;

	var data = JSON.parse(payload);
	event.waitUntil(
		self.registration.showNotification(data.label, {
			body: data.text
		})
	);
});
```

Side-note: pwa != webpush, both can be developed undependently

**Comment by gedw99** [comment]
> > Made progress in making the react web app fulfill install-ability requirements on the pwa-background-push [branch](https://github.com/liamstojanovic/ntfy-webApp/tree/pwa-background-push) of my forked repo.
> 
> Where are you planning to store the subscriptions from the client? Those have to be somewhere on the backend side 🤔

I would suggest nats.

you can embed nats or run it as a separate service.

Nats is 100% golang.

**Comment by karmanyaahm** [comment]
> hopefully shed some light

PWAs and WebPush are related but separate. One does not require the other.
I agree with @BuckarooBanzay's comment. The frontend is simple, an extra JS file that handles push, notifies, and stores it into the indexed DB.

The backend could get complicated, however. First, you need a way to register. Perhaps `POST ntfy.sh/mytopic,topic2/push` with the subscription:
```json
{"endpoint": "https://browser-dependent-url.com/xy", "keys": {"auth": "abcde==","p256dh": "efgh=="}}
```

Then, ntfy needs to store `mytopic:subscription, topic2:subscription` in the database.

Just like there's a `sendToFirebase` function, there will have to be a `sendToPush` function. On every message, `sendToPush` will look up the subscriptions associated with that topic, and then run the WebPush library on each of those.

The library encrypts the payload and POSTs it to the endpoint.

Details:
1. I'd recommend allowing ignoring encryption when `keys` is `null` (POST raw notification to the server).
3. The ntfy server will have to generate VAPID keys. It can be saved to the DB on the first run. (https://pkg.go.dev/github.com/AbdullahDiaa/govapid#GenerateVAPID).
4. There needs to be a config option for the email of the server host or something similar (for VAPID).
5. Make sure the endpoint cannot point to the ntfy server itself, preventing loops.

**Comment by pinpox** [comment]
Any plans for when this will be released?

**Comment by binwiederhier** [comment]
@gedw99 @pinpox You can help test it. It's deployed on https://staging.ntfy.sh -- Docs are here: https://docs.ntfy.sh/subscribe/pwa/

We found some small issues, but nothing major. It's almost ready for prime time.

**Comment by nimbleghost** [comment]
specifically here: https://staging.ntfy.sh/app :D

and the self-hosting config docs are here: https://docs.ntfy.sh/config/#web-push

**Comment by binwiederhier** [comment]
:loudspeaker:  **Request for testing:** 

The next ntfy server release will contain a **progressive web app (PWA) with Web Push support**, which means you'll be able to **install the ntfy web app on your desktop or phone** similar to a native app (__even iOS!__ :partying_face:), and get basic push notification support (without any battery drain).

Installing the PWA gives ntfy web its own launcher (e.g. shortcut on Windows, app on macOS, launcher shortcut on Linux, home screen icon on iOS, and launcher icon on Android), a standalone window, push notifications, and an app badge with the unread notification count.

The (hopefully) production ready version of the PWA is currently deployed on https://staging.ntfy.sh/app -- Install instructions with screenshots can be found in the docs (https://docs.ntfy.sh/subscribe/pwa/). 

Please report bugs or issues on Discord/Matrix/Lemmy. **PLEASE HELP TEST**

Huuuuge thanks goes to @nimbleghost for developing this entire feature top to bottom. If you throw donations my way, I'll share them with him. He certainly deserves it for all this great work. :clap:
