### ISSUE TITLE
Self hosted HTTP - Notification panel translation key(?) visible

### ISSUE THREAD

**Issue by milksteakjellybeans** [binwiederhier/ntfy#349]
With the 1.27.2 ntfy server, while self hosting and using HTTPs, the notification prompt panel in the upper left shows:

> Notifications not supported
> alert_not_supported_context_description

looks like the second line is localization key or similar

**Comment by binwiederhier** [comment]
This is very odd. I just tested with the exact same binary and it doesn't happen for me.

Which browser? 
Which OS?
Can you try to hard-refresh your browser cache (Alt-F5 on Linux/Windows)

![image](https://user-images.githubusercontent.com/664597/176901355-252b96f0-78e5-4078-95a1-48acf6da94b6.png)

As for why you are seeing this error: Notifications are only supported via HTTPS or on localhost. That's a browser restriction.

**Comment by milksteakjellybeans** [comment]
looks like a caching issue, I can't repro after emptying caches in safari

**Comment by binwiederhier** [comment]
:+1:
