### ISSUE TITLE
Cross compiled version for OpenWrt / libreCMC?

### ISSUE THREAD

**Issue by riverside6** [binwiederhier/ntfy#350]
Is it possible to compile or even offer a ntfy version for above mentioned OSs / platforms? This way people could run their ntfy instance even on routers, which would be awesome. Of course, as long as the device provides enough flash, which is true for some of them.
I only found a [thread on turris forum](https://forum.turris.cz/t/guide-cross-compiling-packages-for-turris-omnia-with-tos-3-xx-using-nginx-as-example/12920), describing roughly what i mean. Unfortunately, it looks a bit tricky to me and I don't know if it'll even work out. Yep, I'm more a rookie when it comes to compiling at this level:)
Curious to hear what you think.
Thanks for this great project!

Regards
riverside6

**Comment by daxcore** [comment]
https://github.com/daxcore/ntfy-openwrt
