### ISSUE TITLE
"Pop" and "Pop Swoosh" files are swapped in the Web App

### ISSUE THREAD

**Issue by coma-toast** [binwiederhier/ntfy#352]
https://github.com/binwiederhier/ntfy/blob/e8953aea3b06f59c7f93d72d1c8cc6d63de929ad/web/src/app/utils.js#L176

In settings, go to the notification sound drop-down and play the files. Pop seems to have a "swoosh" at the end, and pop swoosh seems to be a short pop

**Comment by binwiederhier** [comment]
Fixed in https://github.com/binwiederhier/ntfy/commit/d8ce68b2cb828b74410f826ac50ec8b331507d22
