### ISSUE TITLE
Android: Allow per-subscription settings for subscriptions created by apps

### ISSUE THREAD

**Issue by opk12** [binwiederhier/ntfy#355]
When the Matrix client [SchildiChat](https://f-droid.org/de/packages/de.spiritcroc.riotx/) is opened, it creates a subscription in ntfy automatically. A short tap shows a toast message that the subscription was made by SchildiChat, and a long tap allows to delete. So it would be nice if the per-subscription settings introduced in #155 were also available for this one.

**Comment by binwiederhier** [comment]
Whoa. @wunter8 literally just did that in https://github.com/binwiederhier/ntfy-android/pull/37.  Though only a subset of settings are available. In fact I don't think any of them (other than display name) are applicable. What setting specifically are you looking for?

**Comment by opk12** [comment]
@binwiederhier Hello, I just started using ntfy and I want to mute the chat notifications for the weekend. Schildi and Element do not implement it yet, but maybe I could do it in ntfy? Thank you for linking the PR from two days ago, I had not seen it and just had a cursory glance.

**Comment by binwiederhier** [comment]
For UnifiedPush, ntfy is the delivery mechanism of messages. Muting a topic in ntfy for a UP topic is not the right way, and similar to just cutting the cord on your TV to turn it off. You are assuming that all messages that chat applications receive at chat messages, which is not correct. 

We won't implement anything but the display name for UP subscriptions. Hope you understand. If in the future there are other settings that make sense, we'll make them available too.

**Comment by opk12** [comment]
Yes, the intention is to block all communication (including metadata) as some notifications arise from state changes (such as room invites).
