### ISSUE TITLE
file server.yml do not exists [Docker]

### ISSUE THREAD

**Issue by barart** [binwiederhier/ntfy#361]
Hello, after create the docker container with default values and volumes mapped to `/etc/ntfy` and `/var/cache/ntfy` there are neither `/var/cache/ntfy/cache.db` or `/etc/ntfy/server.yml` files

The only way that the `cache.db` file is created is if i specify it with `--cache-file /var/cache/ntfy/cache.db` option but the `server.yml` is not created

Do i need to manually create the `server.yml` file? (i could not find this on docs)
Does the `cache.db` file is not created by default when the volume is mapped and it is only created with the `--cache-file` option?

**Comment by binwiederhier** [comment]
For docker you need to manually create the server.yml file. One you specify cache-file in the config it'll be created just like when you pass the command line arg. 

At the top of the config guide (https://ntfy.sh/docs/config/) you can find a link to the skeleton server.yml file. 

This is not the first time somebody asked, so maybe we should update the docker docks.

**Comment by binwiederhier** [comment]
I added this info box at the top of the Docker install instructions. Hope that makes it clearer.

![image](https://user-images.githubusercontent.com/664597/188284945-bad82208-e635-486b-87b7-c3972d764ed4.png)
