### ISSUE TITLE
IOS app: Poll self-hosted server setting

### ISSUE THREAD

**Issue by WebKenth** [binwiederhier/ntfy#363]
To resolve the slow response time of up to 20minutes for notifications to come through via iOS app

Would it not be possible for the iOS app to simple do a GET request to the self-hosted server to fetch any new notifications?

I know next to nothing about the iOS app limitations, but a background GET request every minute doesn't seem like the biggest resource draw

The reason i focus on self hosting is to avoid bombarding https://nfty.sh/

but would offer developers the advantage of boosting their own service without having to rely to heavily on the 20 minute delay

**Comment by WebKenth** [comment]
Well that isn't great at all :-/ 

I guess the only way is to create your own firebase application ?

https://ntfy.sh/docs/config/#ios-instant-notifications

I tried adding the `upstream-base-url: "https://ntfy.sh"` but i get no notifications at all :-/ 

sucks having to pay 99$ a year just for notifications

**Comment by binwiederhier** [comment]
Try adding the upstream URL and then also enabling trace mode via the log-level setting. Then publish a test message to a test topic and post it here. 

The base URL you define in server.yml and the one you enter in the iOS app have to match exactly.
