### ISSUE TITLE
Trailing slash in base URL matters

### ISSUE THREAD

**Issue by tfheen** [binwiederhier/ntfy#370]
In my iOS app, I have https://example.com set as the base URL for my own server, in the `--base-url`, I had https://example.com/. It seems like there is no URL normalisation going on, which led to notifications not happening immediately (I presume due to the sha-ing of the ntfy.sh notification channel leading to different results).

It would be useful if the URLs were treated the same instead.

**Comment by binwiederhier** [comment]
> It would be useful if the URLs were treated the same instead.

Agreed. Should be easy to fix.

**Comment by binwiederhier** [comment]
Fixed in https://github.com/binwiederhier/ntfy/commit/b15ecd785e801c9553be4e05039b2609f3adf3da
