### ISSUE TITLE
401 for attachements behind web proxy with basic auth

### ISSUE THREAD

**Issue by YaBoiMax** [binwiederhier/ntfy#371]
I have setup ntfy.sh behind Nginx Proxy Manager with basic auth for security since It is public facing.
It works fine for notifications but doesn't download local attachments, I think it's because it only uses the basic auth/user for the topics and not the entire base url.

**Comment by binwiederhier** [comment]
If you turn on debug logging in ntfy you can see the detailed error. `log-level: DEBUG` in the server.yml or `--debug` on the command line.

**Comment by YaBoiMax** [comment]
The logs don't say anything since the app can't download the attachments.
In the app I get a 401 error if I am using basic auth behind a proxy for the attachments, the notifcations arrive just fine

**Comment by binwiederhier** [comment]
I'm going to close this for inactivity and lack of info. Happy to re-open if you can provide more details.
