### ISSUE TITLE
[Question] Sending messages from commandline with docker

### ISSUE THREAD

**Issue by phirestalker** [binwiederhier/ntfy#375]
I have ntfy running via docker-compose. I have set up authentication and access control for my topics. What is the recommended way to allow the root user of the docker image to publish to a topic?

**Comment by binwiederhier** [comment]
I'm not sure I follow. If you've set up user/ACLs then why don't you just use one of them to publish? There is no magic back door for local users or inside of docker, if that's what you're asking

**Comment by phirestalker** [comment]
No, not really. I guess the easiest way is to set some environment
variables. I was skimming the help and realized that it accepts them for
the username and pass.
