### ISSUE TITLE
👶 Baby break - Baby girl was born 8/30 :partying_face: 

### ISSUE THREAD

**Issue by binwiederhier** [binwiederhier/ntfy#387]
Hey folks, my daughter ~~is about to be born~~ was born 8/30/22, so I'll be taking some time off from working on ntfy. I'll likely return to working on features and bugs in a few weeks. I hope you understand.   

![image](https://user-images.githubusercontent.com/664597/188283677-8aff17fb-2c1d-47dd-a0da-9260a666cf30.png)

**Comment by BeardedTek** [comment]
Congrats my man!  This project is absolutely amazing.  Wish you had sponsors enabled, I'd throw a donation your way!

I'm running a server of this as well for users of my project [frigate Event Video Recorder](https://github.com/beardedtek-com/fevr) at [https://ntfy.fevr.video](https://ntfy.fevr.video).  Love what you're doing!  When I hit a lull in development I'll see if I can help out anywhere in your project I can as I believe having high quality self-hosted communication and notification platforms is extremely important.

Cheers!
 The Bearded Tek

**Comment by binwiederhier** [comment]
Much appreciated. Regarding donations, see https://ntfy.sh/docs/faq/#where-can-i-donate (TLDR: Nowhere :-)), though I may actually start looking into it. I really just don't want to feel obligated. I had that with another open source project and that really made me feel bad when I took a break or eventually shut it down.

**Comment by BeardedTek** [comment]
100% understand.  I struggled with this for a while but if you keep all your feelings and intentions out there, as you already have, it doesn't hurt to give people the options.  GitHub Sponsors make it fairly easy.

I have my instance up and running to help spread the load.  I'll add it to my linode swarm and once I have it up and running how I'd like you are more than welcome to add it to the list of available servers out there.  For now though, it is very much a testing server for the next month or so while I start integrating ntfy.sh into my project.

Good luck with the little one!  She'll take lots of your time, but it is WELL worth the hugs, high fives, and fun that comes!

**Comment by binwiederhier** [comment]
> 100% understand. I struggled with this for a while but if you keep all your feelings and intentions out there, as you already have, it doesn't hurt to give people the options. GitHub Sponsors make it fairly easy.

I'll check it out tonight. Maybe I'll give it a go.

> I have my instance up and running to help spread the load. I'll add it to my linode swarm and once I have it up and running how I'd like you are more than welcome to add it to the list of available servers out there.

I recently created this page (https://github.com/binwiederhier/ntfy/blob/main/docs/integrations.md), which includes a list of public servers. If you you like, you can add yours. The page is not live yet. It'll be with the next release.

> Good luck with the little one! She'll take lots of your time, but it is WELL worth the hugs, high fives, and fun that comes!

Thanks. My 3yr son is eagerly awaiting his little sister. He said he wants to call her "construction site", which my wife and I don't really agree with. :smile:

**Comment by BeardedTek** [comment]
Most certainly.  I'll do a pull request once I feel it's ready.

**Comment by BeardedTek** [comment]
Most certainly.  I'll do a pull request once I feel it's ready.Yeah, pretty much any financial institution.  If you  do Bitcoin there's a service called tallyco.in which accepts Bitcoin and lightning payments, PayPal, Buy me a coffee, etc.

**Comment by chain710** [comment]
Congrats! Thank you for your amazing project!

**Comment by iointerrupt** [comment]
Spent about an hour now to evaluate ntfy on android (as an alternative to gotify).  Saw this post and couldnt help but say thank you and congrats!!!!

**Comment by mylesbarros** [comment]
Congratulations, she's adorable!

**Comment by Monstrik** [comment]
Mazal Tov!

**Comment by awaitsync** [comment]
Congratulations!

**Comment by thesniper710** [comment]
Congratulation ! Enjoy every moment as it will pass really fast :)

**Comment by brettinternet** [comment]
Congratulations! Happy for you!

**Comment by unixfg** [comment]
"Will not fix."

**Comment by letshin** [comment]
Congrats!

**Comment by NightMachinery** [comment]
Thank you! I have wanted exactly this for around two years.

**Comment by JexPY** [comment]
Congrats!!, I don't know you but as you decided to share your happiness with us, anonymous people, I assume that you are a kind person. So again wish you and your girl all best!

**Comment by rfyiamcool** [comment]
😁，恭喜恭喜. 

😁，Congrats  !!!

**Comment by ba9f11ecc3497d9993b933fdc2bd61e5** [comment]
congrats on your daughter (cute baby!), ready to pay for ntfy as as service here!

**Comment by pablodz** [comment]
Congrats :D

**Comment by Nirvanalist** [comment]
Congratulations!

**Comment by 9terz** [comment]
congrats!

**Comment by bonfy** [comment]
congrats!

**Comment by bradparks** [comment]
congrats! hope things are going well!

**Comment by enrichman** [comment]
That's super cute! It has been a while but now you're getting visitors thanks to the TLDR newsletter I guess!
Congratulations, and enjoy these months! ,As a dad of a young toddler I know the feeling! :heart:

**Comment by fadetobash** [comment]
Congrats and take your time man! Family is everything. 🙌🏻

**Comment by inkstain** [comment]
Congratulations! 

I just discovered nfty.sh via HN. 

Wishing you and your family joy!

**Comment by ServishSaber** [comment]
Congratulations!

**Comment by DxxxxY** [comment]
Congratulations!

**Comment by jmeri** [comment]
Congratulations! She is beautiful! 🌹
And thank you for a great project.

**Comment by tawfekov** [comment]
Congratulations! She is very beautiful! rose

**Comment by otnansirk** [comment]
We're really happy to hear that. 🥰 She is beautiful.
**Congratulations!**

**Comment by lidedongsn** [comment]
Very cute

**Comment by carloshdez90** [comment]
She is beutiful, congratulations man.

**Comment by m2acgi** [comment]
Congratulations!

**Comment by binwiederhier** [comment]
Thank you all for your congratulations. I figured I should close this ticket eventually, but I'm not going to lie: getting all these congratulations makes me feel warm and fuzzy inside. :smile: 

So here's another random picture of me in full dad mode: Using my son's toy trash picker grabber thingy to give our daughter her pacifier. Not sure if she likes that, hehe.

![image](https://user-images.githubusercontent.com/664597/202338138-4489949d-5031-47d4-8061-913836615f9f.png)

**Comment by Robokishan** [comment]
Congrats man

**Comment by Howard3** [comment]
Congratulations @binwiederhier! My baby girl just hit 1 month old yesterday!

**Comment by binwiederhier** [comment]
Congrats to you @Howard3 :heart:

**Comment by lvwxx** [comment]
Congratulations
