### ISSUE TITLE
feature request: add material design icons

### ISSUE THREAD

**Issue by condemil** [binwiederhier/ntfy#388]
It would be great to be able to provide material design icon name the same way as emoji icons. To prevent accidental overlap with already used tags I propose to add `mdi:` prefix to those icons.

**Comment by binwiederhier** [comment]
Could you clarify what's happening with the overlap? Are you saying that you'd like to use a tag that maps to an emoji already, or that you'd like to include an additional set of icons (material icons)?

**Comment by condemil** [comment]
I would like to have another, way bigger, set of icons and use it the same way as it is already done for emojis - though tags. Many emoji names will overlap with material design icons. To prevent that we can add `mdi:` prefix, for example to use existing emojis you specify `email` tag and to use meterial design icon it will be `mdi:email`.

**Comment by binwiederhier** [comment]
Honestly, right now, I don't think I'd like to expand the tag-to-icon mapping further. The standard emojis are very expressive and the soon-to-be-available per-notification icons will help customize the notifications even further.

I'll leave this ticket open for a while. Please upvote :+1: if you want this done.
