### ISSUE TITLE
[New Feature require] Tutorial update.

### ISSUE THREAD

**Issue by CreatorZZY** [binwiederhier/ntfy#390]
Windows Nottify with powershell script:
```
[reflection.assembly]::loadwithpartialname("System.Windows.Forms")
[reflection.assembly]::loadwithpartialname("System.Drawing")
$notify = new-object system.windows.forms.notifyicon
$notify.icon = [System.Drawing.SystemIcons]::Information
$notify.visible = $true
$notify.showballoontip(10,"Script Completed!","Your script ran succesfully!",[system.windows.forms.tooltipicon]::None)
```

**Comment by binwiederhier** [comment]
I'm confused what you are suggesting? You've provided PowerShell code to display a notification bubble. What do you think should be updated in the docs? Or: Alternatively, I'm happy to accept pull requests to update the docs.

**Comment by binwiederhier** [comment]
> What do you think should be updated in the docs?

You haven't answered the question. Please provide details on what you think is missing from the docs and where exactly you think I should provide more detail.
