### ISSUE TITLE
ios app does not receive notifications

### ISSUE THREAD

**Issue by mollerhoj** [binwiederhier/ntfy#394]
It seems that the app does not work? I have notifications enabled for the app, and the notifications are received in the web UI. Iphone simply does not receive anything?

**Comment by milksteakjellybeans** [comment]
iOS app notifications work consistently for me for more than three months without issue, (outside of the double notifications  mentioned in https://github.com/binwiederhier/ntfy/issues/316)

**Comment by mollerhoj** [comment]
iphone 11, ios 15.6.1, public server

**Comment by mollerhoj** [comment]
just tested again, it works now.. Not sure what was going on..
