### ISSUE TITLE
Mobile app setting - defer notification from/to (night time)

### ISSUE THREAD

**Issue by plamenjm** [binwiederhier/ntfy#395]
I guess the notifications will be received during the night time also.
A configuration option to skip/defer the notifications could be useful.

In the mobile application: skip/defer from 0:00h to 7:00h when the priority is 'high' or lower.

---

Nice, simple and useful service and application.
Here why I found it and how I use it: https://github.com/plamenjm/git-simple-notifier

Thank you.

**Comment by binwiederhier** [comment]
Honestly I think this is probably solved by your Do Not Disturb (DND) mode on your phone. If you set your phone to DND over night, you won't be annoyed by notifications until the morning. 

Alternatively, you can use Scheduled Delivery (https://docs.ntfy.sh/publish/#scheduled-delivery) to delay notifications server side until a certain time in the future.

I don't think I'll implement this. Thank you though for your suggestion. Keep them coming.
