### ISSUE TITLE
Battery consumption: F-Droid vs Google Play Services

### ISSUE THREAD

**Issue by iointerrupt** [binwiederhier/ntfy#396]
I have both google play and fdroid on my android (running LineageOS 19.1 w/ gapps).  I am just wondering if I should use the Google play version or the f-droid version?  I believe the Play version uses firebase so am wondering if using it leads to less battery consumption.

Thanks

**Comment by iointerrupt** [comment]
Just answered my own question.  Uninstalled the Fdroid version and installed Play version.  There is an option now in the Google Play version called "instant delivery".  Keeping it DISABLED will use Firbase - that will consume less battery but delay the notification.

**Comment by binwiederhier** [comment]
Firebase is only used if 
- you use ntfy.sh (not your selfhosted server)
- AND you use the Google Play variant of the app

In all other cases, Firebase is not used. Even then, you may still disable Firebase for individual messages. See https://ntfy.sh/docs/publish/#disable-firebase
