### ISSUE TITLE
auth-file does not exist

### ISSUE THREAD

**Issue by gabrielrm** [binwiederhier/ntfy#401]
Hi and congrats for your daughter!

I try using access control with `auth-file: "/var/lib/ntfy/user.db"` in `server.yml` while file `user.db` exists and is owned by the ntfy user and group, but still get the message `auth-file does not exist; please start the server at least once to create it` when try to add user with `ntfy user add --role=admin someuser`.

Checked on a raspberry pi 3 (selfhosted server) and on pc with debian, installed both from repository.

Any advice?

Thank you.

**Comment by wunter8** [comment]
I think the issue is that when you run the command, it's running as your logged in user, not as the `ntfy` user, so the process doesn't have permission to read the `user.db`

Try this: `sudo -u ntfy ntfy user add --role=admin someuser`

**Comment by gabrielrm** [comment]
Yes, that's it. No more error if command is run as user ntfy.
Thank you.

**Comment by gabrielrm** [comment]
Yes, that's it. No more error if command is run as user ntfy.
Thank you.
