### ISSUE TITLE
Feature request: Change notification sound in mobile apps

### ISSUE THREAD

**Issue by BeFs** [binwiederhier/ntfy#404]
Requesting feature to change notification sound in iOS and Android-apps. Would also be super nice to have different sounds based on priority.
Would it be possible to implement a feature where the notification sound repeats x-times (or until its read)?

**Comment by binwiederhier** [comment]
@BeFs You can already define a per-priority sound through Android notification channels. If you long-press on the ntfy icon and then select "App info" -> "Manage notifications", you can define behavior per priority.

> Would it be possible to implement a feature where the notification sound repeats x-times (or until its read)?

I don't think this is technically possible, though I suppose alert apps like OpsGenie can do that too. :thinking:

**Comment by JuDa-FR** [comment]
It would also be cool to implement specific notifications on the presence of keywords or regular expressions.

**Comment by binwiederhier** [comment]
Very related #6

**Comment by leokennis** [comment]
> @BeFs You can already define a per-priority sound through Android notification channels. If you long-press on the ntfy icon and then select "App info" -> "Manage notifications", you can define behavior per priority.
> 
> > Would it be possible to implement a feature where the notification sound repeats x-times (or until its read)?
> 
> I don't think this is technically possible, though I suppose alert apps like OpsGenie can do that too. 🤔

On iOS the only alert currently offered is the basic “pinggg” sound. 

Many apps offer a range of alert sounds, if not their own at least the iOS built in ones. 

Perhaps Ntfy can do the same.

**Comment by binwiederhier** [comment]
I think I'm closing this in favor of the duplicate ticket #6.
