### ISSUE TITLE
mipush support

### ISSUE THREAD

**Issue by danmo66** [binwiederhier/ntfy#405]
Hello, I am a Chinese Xiaomi mobile phone user. Xiaomi mobile phone has its own push system, called Mipush，This is the official website https://dev.mi.com/console/appservice/push.html, Can I add support?

**Comment by binwiederhier** [comment]
What would adding support entail? Would we have to change the server and the Android app? Would we have to bring in new dependencies?

**Comment by binwiederhier** [comment]
Closing for lack of response. I'll re-open if there is a response.

**Comment by chengnan049** [comment]
Need to add SDK
