### ISSUE TITLE
Web UI: Clickable links

### ISSUE THREAD

**Issue by erickhavel** [binwiederhier/ntfy#406]
I haven't been able to figure out a way to do this... Neither HTML nor markdown works (they're both output as-is). Is there any way to get hyperlinks to work in the web UI?

**Comment by erickhavel** [comment]
I also tried with the "Click" header, didn't seem to do anything.

**Comment by binwiederhier** [comment]
This creates a clickable link in the web UI and in Android:

```
curl -d "this is a link: https://google.com" ntfy.sh/mytopic
{"id":"VGC6XqplEFIw","time":1663948323,"event":"message","topic":"mytopic","message":"this is a link: https://google.com"}
```

Markdown and HTML are not supported.

**Comment by binwiederhier** [comment]
I'm going to close this ticket since links are already clickable as demonstrated above, and markdown support is requested in #310. Let me know if you have more questions.

**Comment by erickhavel** [comment]
Doesn't work for me: 

![image](https://user-images.githubusercontent.com/47182697/197007020-807bbd1d-618c-4bf7-838e-d5390ed8bd58.png)

Oh but ok, there's a UI update/revamp that I've missed (I've just patched the binary in my Docker setup)... that explains it.

**Comment by binwiederhier** [comment]
The screenshot you posted is from a UI that's many months old. I highly suggest you update your image frequently.

**Comment by erickhavel** [comment]
Yeah I think I've forgotten to rebuild the container and instead just restarted after putting the new binary in place. 🤦 Working now!
