### ISSUE TITLE
UnifiedPush duplicate entry

### ISSUE THREAD

**Issue by Tealk** [binwiederhier/ntfy#408]
I have newly switched to UnifiedPush and have two entries for tusky, why?

**Comment by binwiederhier** [comment]
That would be a big in tusky likely. Also i removed your screenshot because it includes the topic URL and that's private.

**Comment by Tealk** [comment]
Ok I did not think that the URL is relevant, on the web interface I have seen no entries

Then I'll ask tusky why that is, thank you

**Comment by Tealk** [comment]
the solution is that each logged in account gets its own entry
