### ISSUE TITLE
Swedish characters generates attachment

### ISSUE THREAD

**Issue by PAYload1976** [binwiederhier/ntfy#412]
When using swedish characters åäöÅÄÖ, ntfy generates an attachment.txt instead of an notice..

**Comment by binwiederhier** [comment]
UTF-8 is fully supported, so this is likely a problem with your terminal or code not sending a different character set.

**Comment by PAYload1976** [comment]
ahh, should say it's when i use curl. not the ntfy client and this is on windows.

**Comment by binwiederhier** [comment]
Charset problems are always Windows, hehe. It's probably your terminal.

**Comment by binwiederhier** [comment]
Hoping you got this fixed. Closing this issue for now. Let me know if the problem persists.
