### ISSUE TITLE
Topic list doesn't scroll top with new notifications (Android)

### ISSUE THREAD

**Issue by cmeis** [binwiederhier/ntfy#413]
When I'm subscribed to more topics than fit on the screen, and the topic list is scrolled down: When a new notification is received, the topic list is not scrolled up, so you have to manually scroll to the top to see the topic with new notifications.

I'd consider this a minor GUI bug, or call it UI enhancement if you want ;-)

**Comment by binwiederhier** [comment]
I am debating whether this is even a desired functionality. If I'm in WhatsApp in the list of contacts/chats, and a new message comes in, WhatsApp won't scroll up for me. I think it'd be pretty unexpected if it did that. 

We are talking about the main screen (subscription list, topic list), not the notifications list, right?

**Comment by cmeis** [comment]
It's a matter of taste, indeed.

Naturally I would have expected it to jump to the top in order to make newly arrived notifications visible at once.

I see your side, too. So do whatever you want with this ticket (including declining it) 😉.

**Comment by binwiederhier** [comment]
> I see your side, too. So do whatever you want with this ticket (including declining it) 

Well in that case, I'm going to close it. With love. :grimacing:
