### ISSUE TITLE
Double base-url when using "Attach local file"

### ISSUE THREAD

**Issue by demogorgonz** [binwiederhier/ntfy#416]
![chrome_cSnKilEaRN](https://user-images.githubusercontent.com/5041776/193051014-732f6627-bfa5-44ef-9c58-aab514495fe0.png)

Uploaded file have double `base-url` for some reason, probably a bug?

**Comment by binwiederhier** [comment]
Can you reproduce this with ntfy.sh? I tried there and I cannot reproduce it. 

Can you share your censored server.yml `base-url`? Does it end in a slash? Can you remove the slash? Wild guess...

**Comment by demogorgonz** [comment]
# grep "^[^#]" server.yml

```
 base-url: "ntfy.example.com"
 listen-http: ":9000"
 cache-file: "/var/cache/ntfy/cache.db"
 behind-proxy: true
 attachment-cache-dir: "/var/cache/ntfy/attachments"
 attachment-total-size-limit: "5G"
 attachment-file-size-limit: "20M"
 attachment-expiry-duration: "24h"
 smtp-server-listen: ":25"
 smtp-server-domain: "ntfy.example.com"
 smtp-server-addr-prefix: "ntfy-"
 upstream-base-url: "https://ntfy.sh"

```

@binwiederhier thank you for reply, base-url doesn't have a slash in it, this is whole config, can't reproduce it on ntfy.sh.

Just a pointer, it is behind proxy `behind-proxy: true` and using `upstream-base-url` for notifications which i doubt is a case for ntfy.sh

**Comment by binwiederhier** [comment]
The base-url has to start with http:// or https://

**Comment by demogorgonz** [comment]
> The base-url has to start with http:// or https://

Indeed, that solves it. Thank you :)
