### ISSUE TITLE
Unable to send from curl when behind reverse proxy

### ISSUE THREAD

**Issue by danmed** [binwiederhier/ntfy#419]
I've got everything set up and working great in docker.

If i run the below command without a reverse proxy, it all works great

`curl -u user:pass -H "X-Priority: 4" -T porch.jpg -H "Filename: /root/porch.jpg" -H "Title: Someone is at the door!" -H "Actions: view, Open Camera, https://user:pass@cameraurl domain.co.uk:82/doorbell`

However if i use my reverse proxy and give it a url like ntfy.domain.co.uk (i'm using NginxProxyManager)

when running the above command, i get  "301 permanently moved" error in html 

My server.yml is : 

```
base-url: https://ntfy.domain.co.uk
listen-http: ":82"
auth-file: "/var/lib/ntfy/user.db"
auth-default-access: "deny-all"
behind-proxy: true
attachment-cache-dir: "/var/cache/ntfy/attachments"
```

**Comment by binwiederhier** [comment]
Sounds like your proxy isn't proxying, but rather redirecting. Look at `curl -v` to see what's happening. Doesn't seem like a ntfy issue though. Feel free to close the ticket.

**Comment by sandreas** [comment]
For everyone running into this, here is what the sample is like:

```bash
curl -d "Hi" mydomain.org/sandreas
```

If you are behind a proxy, this might not work. Instead you just have to fully qualify the URL:

```bash
curl -d "Hi" https://mydomain.org/sandreas
```
which made it work in my case. 

Maybe this could be added to the example, if `NTFY_BEHIND_PROXY=true`...?
