### ISSUE TITLE
Allow IP CIDRs in `visitor-request-limit-exempt-hosts`

### ISSUE THREAD

**Issue by karmanyaahm** [binwiederhier/ntfy#423]
For example, `visitor-request-limit-exempt-hosts=matrix.me.org,1.1.1.1,172.0.18.0/16`. Then, all of 172.0.18.0/16 will be exempt in addition to matrix.me.org and 1.1.1.1.

This will help with https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/2135, where there is no way to exempt requests from a whole network.
Is this feature fine with you? If so, I can make a PR within the next few weeks.

**Comment by binwiederhier** [comment]
This looks like a good feature and should be easy enough to implement I think.
