### ISSUE TITLE
Rundeck - publish via email - EOF

### ISSUE THREAD

**Issue by demogorgonz** [binwiederhier/ntfy#426]
```
Diagnostic-Code: smtp; 554 5.0.0 Error: transaction failed, blame it on the
    weather: EOF
```

Seems like it is parsing problem for smtp server.
To replicate problem, setup email notification on any job status to send email to ntfy-$channel@ntfy.sh
For example i have tried public instance and sent email to `ntfy-aaab@ntfy.sh`

**Comment by binwiederhier** [comment]
Emails from other systems work, so I wouldn't say it's necessarily a problem on ntfy side. Can you enable debug mode in ntfy and capture the full email?

**Comment by demogorgonz** [comment]
Sure thing, i have edited sensitive information like domain/username.

[trace.ntfy.log](https://github.com/binwiederhier/ntfy/files/9715591/trace.ntfy.log)

**Comment by demogorgonz** [comment]
By the way i have fiddled with custom email templates too [more info](https://docs.rundeck.com/docs/administration/configuration/email-settings.html#custom-email-templates), added just 1 line html/md.. same result.

**Comment by binwiederhier** [comment]
Rundeck seems to send a double-multipart HTML-only email, without a `text/plain` part. Only HTML, which is why it cannot be parsed. I don't want to get into the HTML parsing business. If you can make Rundeck send plain text emails it'll likely work.

**Comment by demogorgonz** [comment]
I will leave config which works for Rundeck:

```
# Template
rundeck.mail.template.file=template.html
rundeck.mail.template.log.formatted=false
```
Template is from this [source](https://gist.github.com/gschueler/5ce7320c4ecdc0047551)

These settings should be set on email on rundeck side:

![image](https://user-images.githubusercontent.com/5041776/194073924-15146ab0-568e-413e-8144-e62fee80bdd6.png)

**Comment by binwiederhier** [comment]
If you like, you can leave this as an example in the example docs: https://github.com/binwiederhier/ntfy/blob/main/docs/examples.md

Just create a short section and include the screenshot. It'll help others in the future.
