### ISSUE TITLE
cannot unsubscribe/remove topic

### ISSUE THREAD

**Issue by raining1123** [binwiederhier/ntfy#428]
I made a mistake of typing an extra slash at "Use another server" from "Subscribe to topic",
then I cannot reach the topic and remove it from the list.
![image](https://user-images.githubusercontent.com/17892238/194159923-3a44efdf-2c5d-4988-9a2e-fba63530cc83.png)
![image](https://user-images.githubusercontent.com/17892238/194160040-3a00a4a8-f27b-4b2c-aad8-15c7f8c4a64a.png)

is there a way to unsubscribe/remove the topic via CLI or API?

**Comment by binwiederhier** [comment]
Well that's "fun", aka a bug. I tried it myself and the web app crashes too when you add an additional slash

**Comment by binwiederhier** [comment]
I'm going to re-open this because it's actually a bug that should be addressed.
