### ISSUE TITLE
Shoutrrr Auth

### ISSUE THREAD

**Issue by h4wwk3ye** [binwiederhier/ntfy#439]
How to pass username and password to shoutrrr generic webhook example 

https://ntfy.sh/docs/examples/#watchtower-shoutrrr

https://containrrr.dev/shoutrrr/v0.5/services/generic/

**Comment by binwiederhier** [comment]
I just documented the `?auth=..` query parameter, so it's not in the official docs yet, but you can find it here: https://github.com/binwiederhier/ntfy/blob/main/docs/publish.md#query-param

![Selection_048](https://user-images.githubusercontent.com/664597/195113215-467cd94f-ef15-42de-b5a6-18cf38e03b63.png)
![Selection_049](https://user-images.githubusercontent.com/664597/195113234-5a5531e2-8649-4bcc-8f19-2d130bd6d78a.png)

**Comment by scottini** [comment]
Hi,

I tried configuring notifications in my Watchtower docker container like this, but I keep getting this authentication error:

time="2024-01-22T16:44:50+01:00" level=fatal msg="Failed to initialize Shoutrrr notifications: error initializing router services: auth is not a valid config key [actions at attach cache click delay email filename firebase icon in priority scheme tags title]\n"

I added 2 env parameters:

```
- WATCHTOWER_NOTIFICATIONS=shoutrrr
- WATCHTOWER_NOTIFICATION_URL=ntfy://my_ntfy_instance/updates?auth=my_base64_key
```

I've obtained my_base64_key with

echo -n "Basic \`echo -n 'testuser:fakepassword' | base64\`" | base64 | tr -d '='

and if I use curl with the same string, everything is fine.

Did I do something wrong?

**Comment by wunter8** [comment]
Try this format for recent versions of shoutrrr

`ntfy://username:password@host/topic`

**Comment by scottini** [comment]
It works, thank you!
