### ISSUE TITLE
Configuration not reload on systemctl restart. 

### ISSUE THREAD

**Issue by Microwave-WYB** [binwiederhier/ntfy#446]
When received a link to an attachment, the port number is missing and must be manually added. 

For example the topic is at "example.com:8000/ntfy"

The file link will appear to be "example.com/files/hash.png"

**Comment by binwiederhier** [comment]
Can you be more specific where you see this? Android app, web app?

The generated attachment URL is based on the `base-url` configured in the `server.yml` file. If that does not have the correct port, then your generated attachment URL will be incorrect.

**Comment by Microwave-WYB** [comment]
> Can you be more specific where you see this? Android app, web app?
> 
> The generated attachment URL is based on the `base-url` configured in the `server.yml` file. If that does not have the correct port, then your generated attachment URL will be incorrect.

I have the port number in the basement url. This is not a problem about android or web app, it's the back-end sending the wrong url. I restarted the server to make sure the configuration is reloaded.

**Comment by Microwave-WYB** [comment]
![Screenshot_20221021-135448](https://user-images.githubusercontent.com/68882116/197287090-f31e023f-a126-415f-8c03-7caf9e950d4b.png)
From here it seems like the base url should be used, but I've tested multiple times that this is not including the port number

**Comment by Microwave-WYB** [comment]
I found the problem here. `systemctl restart ntfy` does not reload configuration. I had to do `systemctl stop ntfy; systemctl start ntfy`

**Comment by binwiederhier** [comment]
> I found the problem here. `systemctl restart ntfy` does not reload configuration. I had to do `systemctl stop ntfy; systemctl start ntfy`

This is the second instance of this that I'm hearing about. I use `systemctl restart ntfy` when I deploy a new version and it works nicely. What system are you on? What does journalctl say when you issue a restart? Are you using the .deb/.rpm or something custom?

**Comment by binwiederhier** [comment]
Closed due to inactivity
