### ISSUE TITLE
Message correct sent, but got internal server error 50001

### ISSUE THREAD

**Issue by Microwave-WYB** [binwiederhier/ntfy#448]
```
$ curl -d "test" example.com:8000/ntfy
{"code":50001,"http":500,"error":"internal server error"}
```
However the message is successfully sent.

**Comment by Microwave-WYB** [comment]
![Screenshot_20221021-142216~2](https://user-images.githubusercontent.com/68882116/197290859-a4fd6d5a-621f-4454-8284-30aa8dcf6a3a.png)

**Comment by binwiederhier** [comment]
Closed for inactivity. I'm happy to reopen if there is more info.

**Comment by arichiardi** [comment]
For posterity, in my case it was a permission issue on the attachment dir:

```
{"time":"2024-11-10T18:27:01.22-06:00","level":"INFO","message":"Connection closed with HTTP 500 (ntfy error 50001)","error":"open /var/cache/ntfy/attachments/wmjZWfhjFd1d: permission denied"...
```
