### ISSUE TITLE
Attached Images are always public even for private topics

### ISSUE THREAD

**Issue by OHDMax** [binwiederhier/ntfy#449]
Hello!

First thank you creating and maintaining this really helpful program (and congrats on your newest family member!). 

I run a private instance for sending messages between my devices which means every topic needs a user and password to be able to subscribe to them. However when I directly push an image (using curl with POST and a local image) to a private topic I can copy the link to that image and view it without authenticating myself.

Is this a bug or intended? Did I miss a configuration option to make the images private by activating basic auth for files or something? I've skimmed the documentation and the server.yml but could not find anything related.

Related information:
The instance runs on a Synology NAS inside a Docker container. Access to the internet is possible through the built-in NGNIX which acts as reverse proxy.

**Comment by binwiederhier** [comment]
> Is this a bug or intended?

Intended. Attachment links are based on the message ID, which is a randomly generated string of 12(?) upper+lowercase characters and numbers and only lives for 3 hours. There's virtually no chance someone can guess the URL. Google and such use the same concept of a secret URL.

**Comment by OHDMax** [comment]
I see, thanks for clearing that up!
