### ISSUE TITLE
Discord/Slack bot

### ISSUE THREAD

**Issue by binwiederhier** [binwiederhier/ntfy#45]
Send messages to topics
```
/ntfy send mytopic This is a message
/ntfy send myserver.com/mytopic This is a message
/ntfy send --tags=warning,skull mytopic This is a message
...
```

Subscribe to messages (much cooler) to forward messages to channel
```
/ntfy subscribe ntfy.sh/mytopic
```

**Comment by binwiederhier** [comment]
I have WIP code here: https://github.com/binwiederhier/ntfy-bot
But I kinda stopped working on it for now.

**Comment by binwiederhier** [comment]
Closing this for now, though I think this would be really cool. I think I'll pick it up again eventually but right now I have my hands full.

**Comment by c33s** [comment]
@binwiederhier any chance to see such a bot soon? ntfy is litteraly the only app (next to the dying telegram-foss) on a google free android which can receive notifactions in time. it simply works (strangely unified push does not work at all for me. tested it with element https://github.com/element-hq/element-android/issues/7069, element-x and fuffychat). ntfy app work on the same phone without problem.

i would love to simply get a ntfy notification if i get a message in a slack channel. ideally configurable (a message in monitoring channel with contains a specific content should trigger a different message than a message in devteam, ...)
