### ISSUE TITLE
Copy functionality

### ISSUE THREAD

**Issue by L-Clem** [binwiederhier/ntfy#455]
Hi, 
I wanted to ask if adding permission to select and copy text was planned?
Thanks.

**Comment by binwiederhier** [comment]
The Android app already copies the text when you click the notification. Are you talking about iOS? If so, yes that is planned. I could swear I had a ticket for that too.

**Comment by L-Clem** [comment]
> The Android app already copies the text when you click the notification. Are you talking about iOS? If so, yes that is planned. I could swear I had a ticket for that too.

Yes it is. Thank you @binwiederhier for your answer and your work.
