### ISSUE TITLE
Example deployment

### ISSUE THREAD

**Issue by l-maciej** [binwiederhier/ntfy#457]
Hi 
I would like to add an example of kustomize-based Kubernetes deployment to the documentation.
This one is quite basic but it can be worked on.

[k8s-deployment.zip](https://github.com/binwiederhier/ntfy/files/9895463/k8s-deployment.zip)

**Comment by binwiederhier** [comment]
There's a brand new section on K8s here: https://github.com/binwiederhier/ntfy/blob/main/docs/install.md#kubernetes -- Mabye you can see if your matches or overlaps and enhance it? Look at the raw source, not the rendered md file. It'll look different when the docs are generated.

**Comment by l-maciej** [comment]
I've packed raw yaml files.
I'll take look tomorrow and create doc pages.

**Comment by l-maciej** [comment]
[install.md](https://github.com/binwiederhier/ntfy/files/9903971/install.md)
I've added a new section, my deployment is structured bit differently.  It still might need some polish and adjustments ;)

**Comment by binwiederhier** [comment]
Instead of uploading a new file, could you instead create a [pull request](https://github.com/binwiederhier/ntfy/pulls) against the main branch? If you don't know how that works, there's a video here that explains it: https://www.youtube.com/watch?v=rgbCcBNZcdQ

**Comment by l-maciej** [comment]
[PR-463](https://github.com/binwiederhier/ntfy/pull/463) 
Thanks for the link ! I've never worked with this method of creating PR's
