### ISSUE TITLE
How does the geo: URL in a view work?

### ISSUE THREAD

**Issue by jpmens** [binwiederhier/ntfy#458]
I can't get `geo:` to workd in ntfy 1.28.0, neither with the CLI program nor when posting with curl.

I'm trying the example from the documentation (though I'd like to specify `lat,lon` only):

```console
$ ntfy publish --actions '[ { "action" : "view", "label": "Jane lives here", "url":"geo:0,0?q=1600+Amphitheatre+Parkway,+Mountain+View,+CA" }]' mytopic
```

and I'm rewarded with (formatted for clarity):

```json
{
  "id": "ddIAjxyW2v4P",
  "time": 1667169268,
  "event": "message",
  "topic": "mytopic",
  "message": "triggered",
  "actions": [
    {
      "id": "wHhMdkN8Qd",
      "action": "view",
      "label": "Jane lives here",
      "clear": false,
      "url": "geo:0,0?q=1600+Amphitheatre+Parkway,+Mountain+View,+CA"
    }
  ]
}
```

The UI (here in Chrome) displays:

![rabbit-9710](https://user-images.githubusercontent.com/60706/198905083-696b7b18-e908-41b5-b613-042c5bd90172.png)

but when I click on the link, Chrome opens a new tab with `about:blank`. (For the record: the ntfy iOS app does nothing)

I'm sure I must be formatting the URL incorrectly, but how?

I've also tried this, but there's no distinct behavior:

```json
"url": "geo:48.856826,2.292713"
```

**Comment by jpmens** [comment]
In FireFox, the result of clicking on the `geo:` URL is:

![rabbit-9712](https://user-images.githubusercontent.com/60706/198960573-3e1233b0-b162-4dd8-ae42-65e7b82a5dfd.png)

**Comment by binwiederhier** [comment]
`geo:` URIs are not universally understood by all operating systems, similar to `tel:`. Android knows what to do with them, but apparently your OS does not. I'm sure there's some application you can install that will handle the `geo:` URL. If you send a Google Maps link instead, it'll likely have the same desired effect.

**Comment by jpmens** [comment]
Thanks for the clarification.

I suppose I was expecting ntfy do do the "magic" conversion to proper URLs, but what you say makes sense.
