### ISSUE TITLE
Send notification with android application

### ISSUE THREAD

**Issue by dokho33** [binwiederhier/ntfy#467]
Hello.

First sorry for my English (I am French).

Sorry if I'm not in the right place to ask this question but I'm not familiar with github.

I would like to know if it is possible to send notifications with the android application?

I would like to create a bot for my home automation (using nodered).

Thanks.

**Comment by jpmens** [comment]
I would assume sending notifications directly from Node Red (without the Android app) would easier? The [documentation describes how to](https://ntfy.sh/docs/publish/) `POST` a message: in JavaScript it's

```js
fetch('https://ntfy.sh/mytopic', {
  method: 'POST', // PUT works too
  body: 'Backup successful 😀'
})
```

But  do check out the examples.

**Comment by binwiederhier** [comment]
If you're talking about sending custom messages via the Android app, then this is a duplicate thicket #98.

If you are talking about sending messages via the ntfy app from other Android apps, then look at https://ntfy.sh/docs/subscribe/phone/#automation-apps

If you are talking about merely sending messages from your own app, then doing what @jpmens says and manually sending messages via POST/PUT is the best thing to do.

**Comment by dokho33** [comment]
Hi!

I managed to send (and receive) notifications with nodered.

My request is indeed a duplicate of ticket [#98](https://github.com/binwiederhier/ntfy/issues/98) (which I had not found).

All my excuses.

Regards,

**Comment by olvier** [comment]
> Hi!
> 
> I managed to send (and receive) notifications with nodered.
> 
> My request is indeed a duplicate of ticket [#98](https://github.com/binwiederhier/ntfy/issues/98) (which I had not found).
> 
> All my excuses.
> 
> Regards,

How did you managed to receive messages?

**Comment by dokho33** [comment]
> How did you managed to receive messages?

Hello @olvier 

With websocket node listening on wss://my.ntfy.server/my_topic/ws

**Comment by olvier** [comment]
Hm

> > How did you managed to receive messages?
> 
> Hello @olvier
> 
> With websocket node listening on wss://my.ntfy.server/my_topic/ws

Hm, I already tried, but w/o any luck.
I dont use custom server, just ntfy.sh.

Any idea for further testing?

btw: Thank you for the fast answer :)

**Comment by olvier** [comment]
It works now, just needed to add the "wss://" at beginning.
Assumed, that this is done by the node itself.
