### ISSUE TITLE
Copying a message on Android always includes the timestamp

### ISSUE THREAD

**Issue by arminus** [binwiederhier/ntfy#471]
Just sent a password to my Android device, copied it in the app and pasted in some dialog, not realizing that ntfy had copied the timestamp with it. This seems a bit "too much"?

**Comment by binwiederhier** [comment]
Interestingly this happened to me today and i felt the same. Agree that it should be removed.

**Comment by robot3498712** [comment]
Hi @binwiederhier if this was fixed years ago then it seems to have reappeared along the way. 
I'm frequently "annoyed" by this (only Android, it's fine on iOS): copy a message, it has the message AND a datetime stamp concatenated, which results for example in URL open errors when pasted into mobile web browser. It's a nuisance as well for usernames and passwords, which is my primary use case for the app bundle. 

Would you mind having another look at this when time allows? 
This literally is my only complaint about this great app. Thanks a lot
