### ISSUE TITLE
Android: Ability to copy only a part of a message (low priority)

### ISSUE THREAD

**Issue by k3a** [binwiederhier/ntfy#478]
Copying the whole message to the clipboard is nice but sometimes I need to copy only a part of it.

**Comment by binwiederhier** [comment]
This conflicts with #471. I am not sure if we can achieve both.

**Comment by k3a** [comment]
That's true... hmm, what about:
- tap to copy just the text (without timestamp because timestamp is rarely interesting for a single message)
- tap and hold to allow text selection to copy any part of it
- use [...] trippledot menu or a new  toolbar icon to switch into the multi-message selection, tap on messages to copy and get selected messages with timestamps

**Comment by binwiederhier** [comment]
I review tickets every now and then, and honestly, this seems more trouble than it's worth. There is a long-tap action already and a single tap action. It's not that big of a deal to strip out the stuff you don't need later.

If there are many more people that like this feature, I may change my mind. For now, I'm going to close this.

Thank you for reporting this. Keep these ideas coming. :-D
