### ISSUE TITLE
Android 13 Notification Icon invisible against the background

### ISSUE THREAD

**Issue by s-h-a-r-d** [binwiederhier/ntfy#480]
![tempFileForShare_20221109-121817](https://user-images.githubusercontent.com/5573972/200841563-8e08b8cc-875e-46d8-942b-5e1f1ba6c04e.jpg)

Device: Samsung Galaxy S22 Plus
OS: Android 13

My device updated to Android 13 and now the background color of the notification icon is same as the icon color itself. Which makes the icon almost invisible.

I guess the background color is configured somewhere and could be changed to a different color. BUT I think changing the notification icon to be fully white could be a better solution.

**Comment by clmbmb** [comment]
Related to the above:

Before upgrading to Android 13 (Samsung Galaxy S20+) the notification icon in the status bar was 'adaptable', white on dark background, black on light background.

At the moment the icon is green and stays green in both situations. I'm attaching screenshots.

![Screenshot_20221114_090614_Settings](https://user-images.githubusercontent.com/54553205/201598120-ac7f141a-88eb-4917-ad5f-4a2e9297ba4d.png)

![Screenshot_20221114_090555_Settings](https://user-images.githubusercontent.com/54553205/201598181-7f46679e-079f-4e8e-ae83-68ddfaf51e20.png)

**Comment by s-h-a-r-d** [comment]
I can confirm the "always green" icon as well.

**Comment by binwiederhier** [comment]
I have not been able to reproduce either case in the emulator, but it occurs on my phone as well. Very odd.

**Comment by alexhorner** [comment]
> I have not been able to reproduce either case in the emulator, but it occurs on my phone as well. Very odd.

I too have this issue on my S22. I think (from my limited android dev experience, so please dismiss me if you know better) that you can set various different icon types in some kind of manifest, and provide them as a bunch of resources, some of those resources intentionally being monochrome icons for situations such as these.

![image](https://user-images.githubusercontent.com/33007665/203869719-ea97b72e-e9ee-496a-a35d-fbe839b1e2a5.png)

As you can see, FitnessSyncer also has this issue partially, but they don't appear to have a theme colour set. The other apps such as Automate have monochrome icons correctly configured so do not exhibit this issue.

**Comment by binwiederhier** [comment]
Should be fixed in https://github.com/binwiederhier/ntfy-android/pull/46 - Please try out the .apk and let me know if it works for you, and maybe post a screenshot too.

@alexhorner @s-h-a-r-d @clmbmb 

https://drive.google.com/file/d/12Q9mejiBP1EZ84OFjvHyyPPoAklkTBPd/view?usp=share_link

**Comment by alexhorner** [comment]
@binwiederhier All tested, looking snazzy!

![Screenshot_20221126_201534_Nova7.jpg](https://user-images.githubusercontent.com/33007665/204107419-1fc1f7f1-0ef0-4677-b1d3-d64836c34728.jpg)

May I also make the recommendation that you configure the subscription service notification category to be minimised by default? As you can see in my screenshot, I have manually configured it to be minimised.

Thanks for your awesome work!

**Comment by binwiederhier** [comment]
> May I also make the recommendation that you configure the subscription service notification category to be minimised by default? 

I briefly checked and I don't think this can be toggled programatically.

> EDIT: And maybe make that notification also undismissable?

You mean make it so that it can be swiped away? That's not possible for foreground service notifications. It's desired behavior in Android.

**Comment by binwiederhier** [comment]
Done. Will be in the next release.

**Comment by alexhorner** [comment]
> > May I also make the recommendation that you configure the subscription service notification category to be minimised by default? 
> 
> I briefly checked and I don't think this can be toggled programatically.
> 

Quasseldroid, Conversations and Automate as you can see in my screenshots have it minimised by default. I believe Quasseldroid and Conversations are open source so maybe that could be of help?

> > EDIT: And maybe make that notification also undismissable?
> 
> You mean make it so that it can be swiped away? That's not possible for foreground service notifications. It's desired behavior in Android.

The opposite. Both Quasseldroid and Automate are undismissable (cannot be swiped away). Conversations and ntfy both are dismissable (can be swiped away) right now, and don't seem to reappear without killing them and starting them again.

I will open a separate issue for this.

**Comment by binwiederhier** [comment]
Interesting. Yeah please feel free to create two new issues for this.
