### ISSUE TITLE
Apple Shortcut app intergration?

### ISSUE THREAD

**Issue by macccorehenni** [binwiederhier/ntfy#485]
I am using ntfy on an iPhone. However, it lacks Apple Shortcut integration. It would be nice to have so we don't have to keep the app open to check the notifications.  Anyone who wants to help with a shortcut that uses JSON or HTTP would also be appreciated.

**Comment by binwiederhier** [comment]
The app should not have to remain open to receive notifications.

Is this ticket a dup of #302?

**Comment by macccorehenni** [comment]
Okay, true, but another use for the Shortcuts app is workflows. I don't know if you're familiar with it, but it's an app for scripting. So, widgets too would be helpful. Cameron ReapeOn Nov 10, 2022, at 11:10, Philipp C. Heckel ***@***.***> wrote:﻿
The app should not have to remain open to receive notifications.
Is this ticket a dup of #302?

**Comment by binwiederhier** [comment]
Feel free to comment on the other ticket with your workflows idea. I am not familiar. The Apple ecosystem is quite new and foreign to me.
