### ISSUE TITLE
Notifications are not appearing unless I refresh the app

### ISSUE THREAD

**Issue by 9j7axvsLuF** [binwiederhier/ntfy#490]
I started self-hosting ntfy, and notifications don't spontaneously pop up when I send them, although they do show when I manually refresh the topic in ntfy.

This behavior is consistent across android, ios, and desktop.

Thanks for your help!

**Comment by 0x111** [comment]
I started to notice some issues in the past few hours too. On the IOS app I do not get the messages, on the desktop it seems to be working, but for the app I use upstream url feature.

It was working fine until yesterday, now it seems there might be some problems.

**Comment by binwiederhier** [comment]
If the behavior is consistent across all clients then it's likely a problem with your server or proxy config. 

Logs are always helpful:
- For Android, enable logging in the Settings -> Record logs. Then you can upload them or copy/paste them to look at them.
- For Web: In Firefox/Chrome, press the F12 key and check what the console says.

**Comment by binwiederhier** [comment]
Closed due to inactivity
