### ISSUE TITLE
Self-hosted with push notifications for iOS App?

### ISSUE THREAD

**Issue by svenkubiak** [binwiederhier/ntfy#493]
I am not sure if I understood the Apple onboarding process for (instant) iOS Push Notifications correctly, but would it be possible to move the enablement for Push notification on the iOS App _after_ one has changed the Server to a self-hosted address, so the self-hosted server becomes responsible for send the notification to Apple APNS? Thus, one would avoid the poll-request through ntfy.sh for instant notifications on iOS.

**Comment by binwiederhier** [comment]
The APNS server is baked into the app. There is no way to change it at runtime of the app. This is desired by apple.

**Comment by svenkubiak** [comment]
Alright, thanks.
