### ISSUE TITLE
Android 13: status bar icon green in any situation

### ISSUE THREAD

**Issue by clmbmb** [binwiederhier/ntfy#495]
Before upgrading to Android 13 (Samsung Galaxy S20+) the notification icon in the status bar was 'adaptable', white on dark background, black on light background.

At the moment the icon is green and stays green in both situations. I'm attaching screenshots.

![Screenshot_20221114_090614_Settings](https://user-images.githubusercontent.com/54553205/201598120-ac7f141a-88eb-4917-ad5f-4a2e9297ba4d.png)

![Screenshot_20221114_090555_Settings](https://user-images.githubusercontent.com/54553205/201598181-7f46679e-079f-4e8e-ae83-68ddfaf51e20.png)

**Comment by binwiederhier** [comment]
This is a dup of, or super closely related to #480. May I ask that you post the screenshots and your description again in the other ticket?
