### ISSUE TITLE
No Notification recived in MacOS, But Chrome WebApp work.

### ISSUE THREAD

**Issue by CreatorZZY** [binwiederhier/ntfy#496]
IOS version installed in macos via AppStore.

Version: 1.2(3).

**Comment by 0x111** [comment]
Are these messages you receive sent with "Priority" header? Because then it might be related to this issue https://github.com/binwiederhier/ntfy/issues/461

**Comment by CreatorZZY** [comment]
All messages sent with default paraments, no title, no tags, no priority, and just contents...

**Comment by binwiederhier** [comment]
There's not really enough information here to help out. 

1. Are you using ntfy.sh or a selfhosted server?
2. Have you tried uninstalling and re-installing the app? For some strange reason that has helped some people. Firebase is temperamental.

**Comment by CreatorZZY** [comment]
using ntfy.sh, and i have  tried uninstalling and re-installing the app.
Note that i installed this app in MacOS 12 using AppStore, not in IOS.
