### ISSUE TITLE
UnifiedPush restrictions

### ISSUE THREAD

**Issue by bt90** [binwiederhier/ntfy#497]
A few things which are currently not covered by the documentation:

1. Does UP still work if i restrict the access by default? https://docs.ntfy.sh/config/#example-private-instance
2. What happens if i change the displayname of an active UP subscription in the app? e.g `https://ntfy.example.com/xxxxxxxc` to `tusky` ?

**Comment by binwiederhier** [comment]
1. This is covered in the UP docs: https://unifiedpush.org/users/distributors/ntfy/#limit-access-to-some-users -- Long story short: you have to allow write access to `up*` for anonymous users, or for a specific UP topic
2. The display name has no impact on the subscription. It's just displayed differently in the client

**Comment by bt90** [comment]
Thanks for the quick answer. I created #499 as i think this should be covered in the ntfy documentation.

**Comment by binwiederhier** [comment]
https://docs.ntfy.sh/config/#example-unifiedpush

**Comment by bt90** [comment]
Thanks for the adjustments. This should make things a lot clearer for UP newbies 👍

**Comment by bt90** [comment]
Should we drop the `$ ` from the examples? Just noticed the copy button which obviously won't properly work that way.
