### ISSUE TITLE
Sender column in cache.db shows `invalid IP`

### ISSUE THREAD

**Issue by binwiederhier** [binwiederhier/ntfy#503]
```
sqlite> select * from messages limit 10
   ...> ;
247|OIvQ1dqYzCYP|1668540105|aa|triggered||0||||||0|0||invalid IP||1|
248|yRmpGNK6Rtnr|1668540105|aa|triggered||0||||||0|0||invalid IP||1|
249|CYfstoAzWhx6|1668540105|aa|triggered||0||||||0|0||invalid IP||1|
250|9bqeSW4eQwL2|1668540105|aa|triggered||0||||||0|0||invalid IP||1|
251|M6jJkh3UpIWo|1668540105|aa|triggered||0||||||0|0||invalid IP||1|
252|EI39IZaXIH3Z|1668540105|aa|triggered||0||||||0|0||invalid IP||1|
253|h8lqfzT4xtrx|1668540106|aa|triggered||0||||||0|0||invalid IP||1|
254|vDrRlh3DdiJx|1668540155|aa|triggered||0||||||0|0||invalid IP||1|
255|SoomY2DjlmXU|1668540155|aa|triggered||0||||||0|0||invalid IP||1|
256|oueH0BOGr0tm|1668540155|aa|triggered||0||||||0|0||invalid IP||1|
```

**Comment by binwiederhier** [comment]
Likely related to the work in #429 
/cc @karmanyaahm

**Comment by karmanyaahm** [comment]
Are there any patterns (to help me reproduce this)? Is it happening often or rarely; for any content or just "triggered"; with no attachments?

**Comment by binwiederhier** [comment]
```
sqlite> select count(*) from messages where sender='invalid IP';
count(*)  
----------
137932    
       
sqlite> select count(*) from messages where sender<>'invalid IP';
count(*)  
----------
1239    
```

Pretty much all messages have this. I may have time to look tonight a little.

**Comment by binwiederhier** [comment]
It is worth noting that I'm behind nginx with the config mentioned here: https://docs.ntfy.sh/config/#nginxapache2caddy

**Comment by karmanyaahm** [comment]
I only ever tested with Caddy, so that might be it, I"ll try setting up nginx.

**Comment by binwiederhier** [comment]
Don't worry about it. I can probably figure it out. Unless you're eager to learn nginx hehe

**Comment by binwiederhier** [comment]
https://pkg.go.dev/net/netip#Addr.String

> String returns the string form of the IP address ip. It returns one of 5 forms:
> -  "invalid IP", if ip is the zero Addr
> ...

**Comment by karmanyaahm** [comment]
Interesting ... so I should've set the 'invalid IP's to empty strings, and validated them at parse time.
