### ISSUE TITLE
handle development dependencies using Hermit

### ISSUE THREAD

**Issue by gedw99** [binwiederhier/ntfy#504]
Hermit is golang

It allows a repo to have its own binary dependencies.
It is OS and ARCH independent.

its really awesome.

It will make dev, ci and release also much easier.

https://github.com/cashapp/hermit
https://cashapp.github.io/hermit/

The current makefile can still be used. you just add a hermit to it.

There is a registry here: https://github.com/cashapp/hermit-packages

you can make your own too.

**Comment by binwiederhier** [comment]
The ntfy build process uses [goreleaser](https://goreleaser.com/), which is pretty amazing. The Makefile is just a wrapper around it. I see no reason to change to anything else, let alone a project that is only incubating.

Thank you for the recommendation though. Keep them coming.
