### ISSUE TITLE
bug - oh no ntfy crashed on chromium 83

### ISSUE THREAD

**Issue by japharl** [binwiederhier/ntfy#505]
Ubuntu chrome says "uhoh e.replaceAll is not a function.  Note that stand alone server on an isolated network, returned a 404 error message, when trying to access /static/langs/en-US.json  Other browsers worked, so it could be a chromium quirk.  Chrome version 83, which is out of date.

**Comment by binwiederhier** [comment]
Isn't Chrome at version >100 already. Looks like Chrome 83 is from 2020, though it's odd that e.replaceAll is not there. Sorry but I can't support outdated browers like that.

**Comment by binwiederhier** [comment]
Closing this, but I'm happy to discuss further
