### ISSUE TITLE
Target certain devices

### ISSUE THREAD

**Issue by binwiederhier** [binwiederhier/ntfy#51]
See https://discord.com/channels/874398661709295626/874398661709295629/919114373992165437

I picture this very simple: 

```
curl ntfy.sh/mytopic/json?id=device1
```

And then:

```
curl -d "Hi" "Targets: device1,device2" ntfy.sh/mytopic
```

**Comment by 12nick12** [comment]
I second this. Or I was thinking of being able to create a group of multiple topics.

**Comment by binwiederhier** [comment]
So, I was actually thinking of deleting this. Because if you need to target another device, just make another topic. They are cheap, right?

**Comment by 12nick12** [comment]
I guess you have good point, For me I have 15 servers and would love each one to have their own topic and I feel it's cumbersome to have to subscribe to 15 topics in the app. If there's a way to import/export topics I guess that wouldn't be to bad. 

Does having more topics in the Android app user any more/less battery?

**Comment by binwiederhier** [comment]
I think it's super easy to add device targeting, so I may as well add it. All topics share one connection, so there is no battery difference.

**Comment by binwiederhier** [comment]
> If there's a way to import/export topics I guess that wouldn't be to bad.

There is not (yet). :-D

**Comment by binwiederhier** [comment]
I thought more about this, and I think the "target devices" feature is something that pushbullet and others may have drilled into people, but in ntfy a topic is the target. Adding target device filters would make things complicated and weird, though not hard to do. I think I'll close this for now; but I'm happy to re-open if people desperately want this.

As for an import/export feature, there's a ticket here: #115
