### ISSUE TITLE
Android: Thematic/Adaptive icons

### ISSUE THREAD

**Issue by daedric7** [binwiederhier/ntfy#513]
With Android13, Material You can theme your icons to match the theme's color.

Aparently, the only thing needed is a B&W icon to be properly themed.

[Adaptive Icons](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive)

Can this be added to the next release ? 

Sample: 

![Nonthemed](https://user-images.githubusercontent.com/4562461/202877722-37366505-6442-4331-9a8f-a5975bf05370.png)

![Themed](https://user-images.githubusercontent.com/4562461/202877724-07ef66ae-05d1-466f-991f-5c6985cdb7da.png)

**Comment by binwiederhier** [comment]
Well. I feel like I'm close :smile: 

![image](https://user-images.githubusercontent.com/664597/204117921-90a92f9a-7ed6-4c9d-a78f-eb4e29dc1f3a.png)

**Comment by binwiederhier** [comment]
Done in https://github.com/binwiederhier/ntfy-android/commit/2e7c6409ff777b48c7623c0b1fdbf5fa073b449e

![image](https://user-images.githubusercontent.com/664597/204118094-c8301765-2681-4dd8-b03f-556d56cac3f3.png)
![image](https://user-images.githubusercontent.com/664597/204118107-8c4df880-a043-45a5-9ab5-b8280736b25a.png)
