### ISSUE TITLE
sending messages with new line

### ISSUE THREAD

**Issue by redchilis** [binwiederhier/ntfy#517]
I'm feeling stupid even while I type :D but I couldn't find a way to send a message on multiple lines using `/n` 
`curl -d "Backup for a successful 😀 /n backup for b not successful" ntfy.sh/mytopic`
or 
`<br>`(html tag)  
with header
`curl -H "Content-Type: text/html" -d "Backup for a successful 😀<br>backup for b not successful" ntfy.sh/mytopic`  
couldn't find in the docs as well. 

Appreciate any help.

Trying to concatenate instead of sending multiple messages.

**Comment by binwiederhier** [comment]
https://docs.ntfy.sh/publish/ -- the third example with the dog:

```
curl -d "There's someone at the door. 🐶

Pease check if it's a good boy or a hooman. 
Doggies have been known to ring the doorbell." \
  ntfy.sh/mydoorbell
```

or

```
echo -e "hi\nthere" | curl -T- ntfy.sh/mydoorbell
```

**Comment by redchilis** [comment]
thank you kind hooman

**Comment by redchilis** [comment]
got it

`echo -e "hi\nthere" | curl -H "Title: 😀 converted 🔥" -T-  ntfy.sh/mydoorbell`
