### ISSUE TITLE
Listening notification isn't minimised

### ISSUE THREAD

**Issue by alexhorner** [binwiederhier/ntfy#520]
![Screenshot_20221126_201534_Nova7.jpg](https://user-images.githubusercontent.com/33007665/204114497-feb56205-d671-46c9-a861-280567448a5e.jpg)

Quasseldroid, Conversations and Automate as you can see in my screenshot have their notifications minimised by default. I believe Quasseldroid and Conversations are open source so maybe that could be of help for reference? As you can see, I have manually minimised the listening notification.

**Comment by s-h-a-r-d** [comment]
Could it be that you are mixing the listening notification with the regular one? In your screenshot 4th notification from the top is the one that is the listening and it seems to be minimized. The topmost is not the listening notification, but the actual notification.

**Comment by alexhorner** [comment]
> Could it be that you are mixing the listening notification with the regular one? In your screenshot 4th notification from the top is the one that is the listening and it seems to be minimized. The topmost is not the listening notification, but the actual notification.

No, I just worded it poorly last night. Please see my updated description.

**Comment by binwiederhier** [comment]
I looked again and I cannot find a way to programatically do this. I even looked at the Quasseldroid source code and I can't find anything special that they are doing. Some Stackoverflow answers even suggest that it's not possible at all.

**Comment by alexhorner** [comment]
> I looked again and I cannot find a way to programatically do this. I even looked at the Quasseldroid source code and I can't find anything special that they are doing. Some Stackoverflow answers even suggest that it's not possible at all.

Might it be this? https://git.kuschku.de/justJanne/QuasselDroid-ng/-/blob/main/app/src/main/java/de/kuschku/quasseldroid/service/QuasseldroidNotificationManager.kt#L276

**Comment by binwiederhier** [comment]
I tried it in the emulator, and `.setPriority` is deprecated and (according to the docs) is ignored. Though in actuality, `.setPriority(Notification.PRIORITY_MIN)` will just make the foreground notification not show up at all (on SDK 33), similar to when it is swiped away. 

The Android docs also discourage the use of minimum priority:

> If the action is of low enough importance that you want to use a minimum-priority notification, create a [background task](https://developer.android.com/topic/performance/scheduling#categories_of_background_tasks) instead.

> The status bar notification must use a priority of [PRIORITY_LOW](https://developer.android.com/reference/androidx/core/app/NotificationCompat#PRIORITY_LOW) or higher. If your app attempts to use a notification that has a lower priority, the system adds a message to the notification drawer, alerting the user to the app's use of a foreground service.

I think it's not entirely inconceivable that the System UI decides to minimize the Quasseldroid notification because it is low priority and you have many other ongoing notifications. 

I think I'm going to call it a day trying to minimize this by default. I'm happy to try out ideas, but I don't want to spend more time on it.

**Comment by alexhorner** [comment]
> I tried it in the emulator, and `.setPriority` is deprecated and (according to the docs) is ignored. Though in actuality, `.setPriority(Notification.PRIORITY_MIN)` will just make the foreground notification not show up at all (on SDK 33), similar to when it is swiped away. 
> 
> The Android docs also discourage the use of minimum priority:
> 
> > If the action is of low enough importance that you want to use a minimum-priority notification, create a [background task](https://developer.android.com/topic/performance/scheduling#categories_of_background_tasks) instead.
> 
> > The status bar notification must use a priority of [PRIORITY_LOW](https://developer.android.com/reference/androidx/core/app/NotificationCompat#PRIORITY_LOW) or higher. If your app attempts to use a notification that has a lower priority, the system adds a message to the notification drawer, alerting the user to the app's use of a foreground service.
> 
> I think it's not entirely inconceivable that the System UI decides to minimize the Quasseldroid notification because it is low priority and you have many other ongoing notifications. 
> 
> I think I'm going to call it a day trying to minimize this by default. I'm happy to try out ideas, but I don't want to spend more time on it.

No worries, totally understand. I'll have a play around I think and see if I can be of any further assistance but thank you very much for taking a look

**Comment by binwiederhier** [comment]
I'm gonna close this for now, but if there is any new info, please do not hesitate to comment. We can always re-open the ticket.
