### ISSUE TITLE
Listening notification is dismissable

### ISSUE THREAD

**Issue by alexhorner** [binwiederhier/ntfy#521]
![Screenshot_20221126_201534_Nova7.jpg](https://user-images.githubusercontent.com/33007665/204114578-fe84a8b3-2074-4382-a7b9-b18476f1b816.jpg)

As seen in my screenshot, both Quasseldroid and Automate are undismissable (cannot be swiped away). Conversations and ntfy both are dismissable (can be swiped away) right now, and don't seem to reappear without killing them and starting them again. I don't think this is desirable because if you accidentally dismiss ntfy you technically can't tell it's running.

**Comment by binwiederhier** [comment]
Fascinating. I tried this in the emulator and this is true. Must be new in SDK 33. I always found it annoying that it cannot be dismissed, but now I kind of agree with you, it should not be dismissable.

**Comment by alexhorner** [comment]
> Fascinating. I tried this in the emulator and this is true. Must be new in SDK 33. I always found it annoying that it cannot be dismissed, but now I kind of agree with you, it should not be dismissable.

I too used to find it annoying, until you think about it slightly differently and realise it's actually really important. I treat it like my system tray as if I was on a desktop computer. It gives me active visibility over my device and how things are going. It is of course essential that they're minimised though, because having an undismissable icon on my lockscreen and top bar of my device is infuriating.

**Comment by alexhorner** [comment]
> Fascinating. I tried this in the emulator and this is true. Must be new in SDK 33. I always found it annoying that it cannot be dismissed, but now I kind of agree with you, it should not be dismissable.

You might be correct with the SDK version, actually. I think I know why too - they added a note to the task switcher to give you visibility, see below:

![Screenshot_20221127_011018_One UI Home.jpg](https://user-images.githubusercontent.com/33007665/204114806-b0936883-0c02-4d39-af07-0a42d97c5681.jpg)

**Comment by binwiederhier** [comment]
Done in https://github.com/binwiederhier/ntfy-android/commit/1b587ab82a4cf69e676788d8089a147d491163e7
