### ISSUE TITLE
Emergency Message on iOS and custom Ringtone

### ISSUE THREAD

**Issue by SchattenWolf2008** [binwiederhier/ntfy#534]
Hey
I am suggesting the following features:
- Emergency priority
- Ability to change Ringtone
For the iOS App.

I am using this project as a warn network, its free and works good but I can't priotise a message or change the ringtone.

I think this would be a pretty cool thing to add because this app is perfect for warning purposes.

Thanks ^^

**Comment by binwiederhier** [comment]
Those are two feature requests, so I suggest creating two tickets.

**Comment by SchattenWolf2008** [comment]
> Those are two feature requests, so I suggest creating two tickets.

arl
ill close this one and open two new instead
