### ISSUE TITLE
Allow us to provide custom CSS

### ISSUE THREAD

**Issue by owenfiscus** [binwiederhier/ntfy#541]
I would love to be able to provide a custom stylesheet to change the appearance of the ntfy web app. I personally deploy with Docker so being able to do this with something like a volume mount would be great, otherwise the ability to point to a URL for the stylesheet in an environment variable could also work.

Thanks for all your hard work on this project!

**Comment by binwiederhier** [comment]
While I don't discredit the idea, I do not currently intend to provide ntfy as a white label solution. There's always the chance I'll change my mind in the future though. So for now I'm closing this.

**Comment by owenfiscus** [comment]
That's fair, thanks for your work on ntfy regardless!
