### ISSUE TITLE
IOS 14.8.x New messages do not appear on the phone's notification bar

### ISSUE THREAD

**Issue by yel-best** [binwiederhier/ntfy#544]
* already configured ``upstream-base-url`` 
--upstream-base-url https://ntfy.sh

but after sending a message to the topic, the IOS APP will refresh after a period of time and prompt that there is new information, but this information will not appear in the notification bar

**environment:**
* IOS:14.8.x
* ntfy-service version:latest
* deploy:docker
* app:latest

**Comment by binwiederhier** [comment]
Dup of #267
