### ISSUE TITLE
Webhooks: GET requests for simple pings without messages

### ISSUE THREAD

**Issue by kzshantonu** [binwiederhier/ntfy#55]
I propose allowing GET requests with no parameters to send simple ping notification without message. Quicker to type in terminal when someone wants a notification but not necessarily a message

**Comment by kzshantonu** [comment]
That does work. Can be any standard 'default' message. The goal is to type it out quickly in terminal

**Comment by binwiederhier** [comment]
@kzshantonu Boom, it's live: https://ntfy.sh/docs/publish/#webhooks-send-via-get
