### ISSUE TITLE
Deep link for register a topic

### ISSUE THREAD

**Issue by thewh1teagle** [binwiederhier/ntfy#551]
It would be amazing to have the ability to register a new topic through Deep link URL, something like `ntfy://action=register&param=some_topic`
In this way I can let people easily register my topic through URL, NFC, QR code and more.

**Comment by binwiederhier** [comment]
You mean this? https://docs.ntfy.sh/subscribe/phone/#ntfy-links

**Comment by thewh1teagle** [comment]
Indeed, thank you very much for this awesome app!
