### ISSUE TITLE
Avoid external Google fonts

### ISSUE THREAD

**Issue by bt90** [binwiederhier/ntfy#554]
Both https://docs.ntfy.sh/ and the self-hosted instances currently make use of Google Fonts.

At least for users in Germany (and probably the entire EU), this is a potential violation of the GDPR: https://thehackernews.com/2022/01/german-court-rules-websites-embedding.html

Could we bundle them as regular assets instead?

**Comment by binwiederhier** [comment]
Yeah I agree. Good catch.

**Comment by clementduveau** [comment]
I investigated this issue:

- 2743c96694c1507db7c4c788e9db745af5ea5a97 seems to have deleted all references to google fonts.
- For docs, MkDocs have a [plugin exactly for that](https://squidfunk.github.io/mkdocs-material/setup/ensuring-data-privacy/?h=priv#external-assets:~:text=The%20primary%20reason,technical%20limitations.) but its for [Insiders](https://github.com/sponsors/squidfunk?metadata_origin=docs) right now.

**Comment by binwiederhier** [comment]
The ntfy web app + website does not include Google Fonts at all.

As you correctly identified, the docs do include Google Fonts. The linked `privacy` plugin is currently only for sponsors, though it seems entirely possible to do this manually by overriding the `fonts` block manually. Any volunteers?

See https://github.com/squidfunk/mkdocs-material/issues/739#issuecomment-396045972

**Comment by ozskywalker** [comment]
Created https://github.com/binwiederhier/ntfy-docs.github.io/pull/1
Is this what you were looking for on the docs side?

**Comment by ozskywalker** [comment]
Have submitted PR #667
Let me know if this is acceptable

**Comment by binwiederhier** [comment]
Done in #667 and #668, will be in next release.
