### ISSUE TITLE
iOS app needs tweaks to build from source

### ISSUE THREAD

**Issue by rgov** [binwiederhier/ntfy#557]
To build the project you need to:

1. Remove the `DEVELOPMENT_TEAM` setting override from both targets, and
2. Create a `ntfy/Assets/GoogleService-Info.plist` file. This can also be found by downloading the Ntfy app from the App Store on an Apple Silicon Mac and rooting around in the ntfy.app bundle.

🎄

**Comment by binwiederhier** [comment]
This has been done a while ago, see https://docs.ntfy.sh/develop/#ios-app
