### ISSUE TITLE
[NEED HELP] with rate limit

### ISSUE THREAD

**Issue by olvier** [binwiederhier/ntfy#560]
for my understanding i'm not doing too much with this great service,
but maybe too many listening devices/services?

I try to just trigger some notifications when there is sth important,
but very often it doesn't send, because of rate limit.

maybe the dev can help with analysis?

**Comment by binwiederhier** [comment]
Hi there. You haven't provided any information. IP address, topics, or even an error message. That'd be really helpful. 
Generally, the Discord/Matrix server is better for trouble shooting than GitHub. See https://github.com/binwiederhier/ntfy#chat--forum
