### ISSUE TITLE
iOs 16.2 - No more instant notifications

### ISSUE THREAD

**Issue by Eridani78** [binwiederhier/ntfy#563]
already configured upstream-base-url
--upstream-base-url https://ntfy.sh/

Everything was perfectly working before.

After update to  iOs 16.2 on my iPhone, notifications push do not appear on my screen anymore.
I have to open Ntfy app to make the new notifications pop-up in the app screen on the iPhone.

**Comment by aappddeevv** [comment]
I noticed that as well.

**Comment by jduckles** [comment]
Same problem here

**Comment by attilabalazsy** [comment]
Ahh, okay, maybe it answers my question, why it is not working with my setup. I'm just testing ntfy and I'm not able to get the iOS notifications working. What is strange, if I publish the notifications directly to the ntfy.sh server, then the iOS app get's notified, but it is not working through the private instance. In the private instance log, I see, that it is publishing a poll to ntfy.sh server, but nothing happens on iOS app.
I'm running on 16.1.2 not on 16.2

**Comment by binwiederhier** [comment]
I have not tested on the latest iOS, but this may (or may not) help: https://docs.ntfy.sh/known-issues/#ios-app-not-receiving-notifications-anymore

**Comment by Eridani78** [comment]
Thank's ... it helps.

Following this advice :
"If notifications do not show up at all anymore, there are a few causes for it (that I know of):
Firebase+APNS are being weird and buggy: If this is the case, usually it helps to remove the topic/subscription and re-add it. That will force Firebase to re-subscribe to the Firebase topic."

Instant notifications have been recovered 👍

**Comment by attilabalazsy** [comment]
@binwiederhier thanks a lot, yes, it helped! The trick was, that I was setting the default server to ntfy.sh in iOS app and was also subscribing to ntfy.sh topic instead of the private server. It seems, that now everything is working as it should! Thanks again!
