### ISSUE TITLE
ntfy in windows form c#

### ISSUE THREAD

**Issue by bravery-only** [binwiederhier/ntfy#564]
When I try to call notifications in Windows Forms - C# I get an error. Can anyone help me?
![xs4otZC4Jm](https://user-images.githubusercontent.com/42680639/210138162-63aa789c-1fe8-4458-846e-9908eb92d47e.png)

**Comment by binwiederhier** [comment]
This seems to be entirely and utterly unrelated to ntfy itself. I'm sure someone would be happy to help in the Discord/Matrix offtopic room. 

I'm closing this as it is neither a bug nor a feature request.
