### ISSUE TITLE
dnf install fails and rpm partially fails because postinst.sh has syntax errors

### ISSUE THREAD

**Issue by danieldemus** [binwiederhier/ntfy#566]
On the first install attempt user and group creation fail, because the syntax of chown is incorrect:
`chown ntfy.ntfy /var/cache/ntfy /var/cache/ntfy/attachments /var/lib/ntfy`
It should `ntfy:ntfy`.
On uninstall the group is not necessarily removed, if fx. the apache user is added to it to allow reading the socket. This means that on the next install attempt
`id ntfy >/dev/null 2>&1 || useradd --system --no-create-home ntfy` fails, when useradd tries to add the group again.
The fedora packaging guidelines at https://fedoraproject.org/wiki/Packaging:UsersAndGroups suggest:
```
getent group GROUPNAME >/dev/null || groupadd -r GROUPNAME
getent passwd USERNAME >/dev/null || \
    useradd -r -g GROUPNAME -d HOMEDIR -s /sbin/nologin \
    -c "Useful comment about the purpose of this account" USERNAME
exit 0
```

In this case https://github.com/binwiederhier/ntfy/pull/565 could also do the job.

**Comment by binwiederhier** [comment]
This is wild. I didn't know the dot syntax was Ubuntu/Debian specific. Thanks for reporting this and for the PR.

You suggested something other than what you did in the PR. Can I close this issue since I just merged the PR?

**Comment by danieldemus** [comment]
The other solution is from the linked fedora document and  can see the copr rpm does use it. I had already committed a fix before I found the link, so ...
Another thing is it's only tested on fedora 37, though I would expect groupadd to be compatible.

**Comment by binwiederhier** [comment]
The groupadd works on Ubuntu too. I tested that. I'm ok with what you added. But I'm also ok with the other one if you want to change it.

**Comment by danieldemus** [comment]
I can see here https://docs.fedoraproject.org/en-US/packaging-guidelines/UsersAndGroups/, that adding a "proper" rpm spec file would be a better solution for the production rpm packaging. I assume the copr maintainer has one.
I was trying to test something else regarding letsencrypt certs and was build the rpm using the release-snapshot target in the makefile, that was causing the issues, so this is in reality a developer issue on fedora.
