### ISSUE TITLE
Modularize init and install scripts and remove hard requirement on systemd

### ISSUE THREAD

**Issue by code-kungfu** [binwiederhier/ntfy#570]
Currently init and install scripts makes the assumption you are installing ntfy on a distro with systemd present.

As the unix-like world isn't just about systemd, and it is often the case systemd is prohibited, the scripts used needs to facilitate and support the most commonly used non-systemd init systems like SysV, OpenRC, s6, runit and so on, for users who runs Alpine Linux, Devuan Linux or any other non-systemd distro as their server base.
There are several ways this could be solved, but the most straight forward way, I would suggest to have have an init script generator which can be invoked in the postinst step and output an init script based on the target system.

**Comment by binwiederhier** [comment]
Thank you for your suggestion. I understand that not all distros use systemd, and it would be great to support more init systems. However, I am not able to create an init script generator myself. You are free to create your own init script generator or use a third-party one.
