### ISSUE TITLE
Paste images from clipboard

### ISSUE THREAD

**Issue by rounakdatta** [binwiederhier/ntfy#572]
Currently NTFY supports attaching a file from a local source or via an external URL. It would be cool if one could paste from clipboard and the file uploading just worked. An use case I can think of is quickly sharing an image from one computer to another.

**Comment by binwiederhier** [comment]
On Android, if you click "Share" from any app, you can share an image or a file to a ntfy topic. There is no native dialog inside in the ntfy app itself yet (see #98) though.

On the web app, you can just drag and drop files into the web app and publish files like that.

**Comment by rounakdatta** [comment]
Thanks for getting back. Here's a situation that prompted me to create this
issue: I use Flameshot on my Linux computer to take a selected-area
screenshot and instead of saving it to a file, I copy it to clipboard.

I think it'd be great if I could just Ctrl+V instead.

(The reason I copy to clipboard or even that am willing to share over NTFY
is that the screenshot is ephemeral and quick)

**Comment by binwiederhier** [comment]
So you are talking about the web app?

**Comment by binwiederhier** [comment]
Done in #963.
