### ISSUE TITLE
Notification display

### ISSUE THREAD

**Issue by fred-gb** [binwiederhier/ntfy#573]
Hi,

Just a little suggestion for self-hosted:
See only the name of the topic and not the url plus the topic name.
Too long in the bubble.

Thanks

**Comment by binwiederhier** [comment]
You can assign a display name to each topic in the subscription settings.

**Comment by fred-gb** [comment]
Sorry, I forgot to say, on iOS app.
I don't find this option in settings.
Sorry.

**Comment by binwiederhier** [comment]
In that case, this is a dup of #357.
It'll be a loong time before I get to that. Sorry.
