### ISSUE TITLE
The nginx configuration(and the one used by ntfy.sh) leaks topic name/auth query in logs

### ISSUE THREAD

**Issue by MaeIsBad** [binwiederhier/ntfy#577]
In https://github.com/binwiederhier/ntfy-ansible/blob/eaa9b7c7ee96adc106317ddfaf07dc28e7d6bde1/roles/nginx/files/nginx.conf#L48 log_format includes $request which contains the request path, which in turn leaks topic names.
This is mitigated with the use of http basic auth, but in the case of authentication via a query parameter the credentials are also logged.

It's is not a huge issue, but potentially could end up quite bad if someone is able to see the log(via LFI? An admin accidentally forgetting they were screensharing? Idk), so maybe it's worth fixing?

The docs for setting up a reverse proxy in front of ntfy(https://docs.ntfy.sh/config/?h=nginx#nginxapache2caddy) don't explicitly set the log format themselves, but the default configuration used by most linux distributions will include the $request param

**Comment by binwiederhier** [comment]
I understand that this seems like a security concern to you, but the fact of the matter is that for debugging purposes I need to be able to group by topic to diagnose issues. The ntfy log is even more detailed when debug/trace is enabled. I will not ever betray people's trust and share the topic names or message content. If people are uncomfortable with that (which I totally understand), they can always set up their own server. 

That said, I think I'd be absolutely fine with somehow censoring the `auth` param somehow. I'm happy to accept PRs or suggestions.

**Comment by MaeIsBad** [comment]
As mentioned I don't think this is a huge issue, just something I thought was worth documenting even as an issue.
I'll look into redacting auth params in nginx logs in my spare time

Thanks for ntfy :smiley:
