### ISSUE TITLE
Clarify F-droid  battery usage in the FAQ

### ISSUE THREAD

**Issue by opk12** [binwiederhier/ntfy#581]
The FAQ [`How much battery does the Android app use?`](https://docs.ntfy.sh/faq/#how-much-battery-does-the-android-app-use) seems to imply that F-droid consumes additional battery, due to lack of FCM. Could this be made explicit, for a new F-droid user that doesn't have the common knowledge that FCM won't work and follows a direct link (so won't read the previous FAQ)?

**Comment by binwiederhier** [comment]
Sure. I'm happy to accept suggestions in docs or otherwise.

**Comment by opk12** [comment]
The bold words would make it explicit in the FAQ. The important part is the link to the doc, where Firebase is mentioned and the background story is explained.

> If you use the ntfy.sh server, and you don't use the [instant delivery](https://docs.ntfy.sh/subscribe/phone/#instant-delivery) feature, the Android/iOS app uses no additional battery, since Firebase Cloud Messaging (FCM) is used. If you use your own server, or you use instant delivery (Android only), **or install from F-droid (which [does not support FCM](https://f-droid.org/docs/Inclusion_Policy/)),** the app has to maintain a constant connection to the server, which consumes about 0-1% of battery in 17h of use (on my phone). There has been a ton of testing and improvement around this. I think it's pretty decent now.

**Comment by binwiederhier** [comment]
Done in https://github.com/binwiederhier/ntfy/commit/23c5d4e34554e69cd457080fa0a385625401d77f

I'm so sorry it took so long
