### ISSUE TITLE
clamscan reports released rpm may have coinminer (even 1.30)

### ISSUE THREAD

**Issue by aappddeevv** [binwiederhier/ntfy#585]
I'm running clamscan on ntfy binary distributed with the rpm bundle and its reporting 

```sh
/usr/bin/ntfy: Unix.Packed.Coinminer-6856324-0 FOUND
```

Not quite sure the details. But I ran this on 1.30 as well.

**Comment by binwiederhier** [comment]
This is a dup of https://github.com/binwiederhier/ntfy/issues/576.
This has been addressed and will likely not happen again in the next release.

**Comment by aappddeevv** [comment]
My apologies. This is such a rare occurrence it did not even dawn on me to search for it already :-)

**Comment by binwiederhier** [comment]
It is quite annoying. `upx` is fantastic at making binaries _a lot_ smaller. But somehow upx-compressed Go binaries have been getting flagged by virus scanners for years. :shrug:
