### ISSUE TITLE
n8n node for ntfy

### ISSUE THREAD

**Issue by raghavanand98** [binwiederhier/ntfy#592]
Hi! I've been using [n8n](https://n8n.io/), and wanted to integrate with ntfy.sh. I built a community node [here](https://github.com/raghavanand98/n8n-ntfy.sh). I'm posting here in case it's useful to anyone else, and if it's a useful addition to the docs. Any feedback is welcome

 
<img width="354" alt="image" src="https://user-images.githubusercontent.com/17361784/213761489-a5000c8c-4390-426c-b041-72165151d05c.png">

**Comment by binwiederhier** [comment]
Awesome. I love seeing projects built around ntfy! I added it to the list of projects here: https://github.com/binwiederhier/ntfy/commit/75c07221efd9d17cbd87804836fadf4ced2d98d2

https://docs.ntfy.sh/integrations/#projects-scripts
