### ISSUE TITLE
Accent issue!

### ISSUE THREAD

**Issue by entonoire** [binwiederhier/ntfy#608]
When you send a notification with accent it's adding an .txt attachement or in some cases not even send. I tried to encode it in url format but it keeped as url format, so maybe a converter to normal text on the api could be nice.

![image](https://cdn.discordapp.com/attachments/603938120509030401/1075025785963954177/Screenshot_20230214-130825.jpg)

**Comment by binwiederhier** [comment]
ntfy converts messages to attachments when you raw sending text that is not valid UTF-8. So this is an issue with whatever client you are using to send the message. 

If you share the code, we may be able to help.

**Comment by entonoire** [comment]
this is my code (kotlin)
after some test, this only happens in title

val request = Request.Builder()
     .url("https://ntfy.sh/?")
    .post(message.toRequestBody("text/html; charset=UTF-8".toMediaType()))
    .addHeader("Title", title)
    .addHeader("Priority", parsePriority(priority))
    request.addHeader("Tags", tag])

OkHttpClient().newCall(request.build()).execute()

**Comment by t4nki** [comment]
Hi!
I encountered exactly the same issue last week with Ansible and Header définitiion in uri module.
To circumvrent this, i generated a json payload directly with ansible.
After that, the title appeared normally with any special character (é, è, à, ç etc...)
eg:
`uri:
  url: https://ntfy.local
  method: POST
  body_format: json
  body:
    topic: myTopic
    message: "{{ message }}"
    title: "mise à jour"
    priority: 4
    .
    ..
    ...
`
This did the trick

**Comment by binwiederhier** [comment]
Offically, afaik, the HTTP spec does not allow UTF-8 headers, so it is quite normal for some clients or libraries to not support it. ntfy (and the ntfy server) definitely support sending UTF-8 headers. You can test it with curl, like so:

```
curl -H"Title: mise à jour 😊" -d "Hi" ntfy.sh/mytopic 
{"id":"DkV46Lwt6VbZ","time":1676389814,"event":"message","topic":"mytopic","title":"mise à jour 😊","message":"Hi"}
```

![image](https://user-images.githubusercontent.com/664597/218788717-7e19a6d0-981e-49d1-ae4c-35b1ee12f117.png)

That said, if your client does not support it, you can always [send it in the JSON body](https://docs.ntfy.sh/publish/#publish-as-json), like @t4nki suggested, or you can send it as a query parameter: 

```
curl -d "Hi" "ntfy.sh/mytopic?title=mise%20%C3%A0%20jour%20%F0%9F%98%8A"
{"id":"FIOnCAxlOEKZ","time":1676390000,"event":"message","topic":"mytopic","title":"mise à jour 😊","message":"Hi"}
```

**Comment by entonoire** [comment]
oh thanks ! i will try the query parameter!
