### ISSUE TITLE
Adding arabic language

### ISSUE THREAD

**Issue by BoFFire** [binwiederhier/ntfy#619]
Hi,

Please add arabic language in `Preferences.js`

`<MenuItem value="ar">العربية</MenuItem>`

**Comment by binwiederhier** [comment]
Awesome. Looks like it's almost done. Will do 

https://hosted.weblate.org/projects/ntfy/web/ar/

**Comment by binwiederhier** [comment]
Done. Thanks.

**Comment by BoFFire** [comment]
Thank you !

**Comment by binwiederhier** [comment]
Thank you for the translation!
