### ISSUE TITLE
[Feature] allow an anonymous "localhost user" for the Private instance

### ISSUE THREAD

**Issue by LuckyTurtleDev** [binwiederhier/ntfy#620]
Application servers  needs anonymous write access to ntfy. I am not a big fan of allowing everyone to upload data to my server.
Since ntfy is running on the same server as the application servers , I wonder if it would possible to give only localhost/docker anonymous write access to ntfy.

**Comment by binwiederhier** [comment]
> I am not a big fan of allowing everyone to upload data to my server.

I'm sure you've seen the section about access control in the docs (https://docs.ntfy.sh/config/#access-control), so you can define granular access controls based on users. 

For your specific problem, you could define default permissions as `deny-all`, and then create ACL entries to allow anonymous write access to a topic:

server.yml
```
auth-default-access: deny-all
```

Define ACL:
``` 
ntfy access everyone sometopic write-only
```

And then you could restrict access to `/sometopic` in nginx (or whatever your proxy is) to only local IP addresses.

I do not intend to add IP restrictive access to ntfy itself (for now).

**Comment by binwiederhier** [comment]
Hope this was answered. If not, feel free to comment or re-open.

**Comment by LuckyTurtleDev** [comment]
Yes it was answered. Thanks. I will try out your solution soon.
Maybe this can be keep open for the feature request?

**Comment by LuckyTurtleDev** [comment]
@binwiederhier sadly I am not allowed to reopen the issue

**Comment by binwiederhier** [comment]
I don't think I want to implement IP-based access control in ntfy. That seems like something that has to live or be solved outside it. In a proxy, as I said. You can easily solve this in nginx.

**Comment by LuckyTurtleDev** [comment]
If I restrict access to `/sometopic` would not this effect also reading the topic?

Maybe it is a better idea to add the authorization header if the request does come from localhost?

**Comment by LuckyTurtleDev** [comment]
I have now simple add a autheader at the reverse proxy for local ips. Works without any issue
`Caddyfile`:
```
push.example.com {
	respond /robots.txt 200 {
		body "User-agent: *
Disallow: /"
	}

	@local remote_ip private_ranges
	reverse_proxy @local localhost:16480 {
		header_up Authorization "Basic SomeBase64"
	}
	
	reverse_proxy localhost:16480 {
		header_down Referrer-Policy "strict-origin-when-cross-origin"
		header_down Strict-Transport-Security "max-age=15768000"
		header_down X-Frame-Options "sameorigin"
	}
}

**Comment by binwiederhier** [comment]
Very elegant. Nice.
