### ISSUE TITLE
Code 40101: unauthorized error

### ISSUE THREAD

**Issue by AliZaidi1500** [binwiederhier/ntfy#622]
I have Ntfy deployed on Docker and it had been working fine for the past few months. Recently updated to 2.0.1 and now I keep getting the following error: `{"code":40101,"http":401,"error":"unauthorized","link":"https://ntfy.sh/docs/publish/#authentication"}`. I have Traefik reverse proxy with basic auth and never enabled auth on Ntfy so I'm not sure what has changed recently.

**Comment by binwiederhier** [comment]
As part of the access token work, I changed the auth code. If the client is sending any `Authorization` header to the ntfy server, it'll consider this as an attempt to authenticate (which I think is reasonable). If you do not have auth set up in ntfy (`auth-file` set), then ntfy will reject every request.

Traefik should probably not be sending an `Authorization` header to the backend, if it doesn't need it. My apologies that the update broke your workflow, but IMHO the logic makes sense.

**Comment by AliZaidi1500** [comment]
Thanks for the explanation. It was indeed the authorization header causing issues. If anyone else comes across this problem, please ensure there isn't any authorization header being passed in the request.
