### ISSUE TITLE
High resolution app icon

### ISSUE THREAD

**Issue by nebulade** [binwiederhier/ntfy#627]
Hi there, we have just packaged and published a ntfy app package for Cloudron and it works great!
Currently we use this icon https://git.cloudron.io/cloudron/ntfy-app/-/blob/main/logo.png however that is unfortunately not very high resolution. Is there a possibility to have the original icon in svg or at least 512x512 px of sorts? The one at https://apps.apple.com/uz/app/ntfy/id1625396347 seems higher resolution, but I wasnt able to find the source image in the repo here.

**Comment by binwiederhier** [comment]
> Hi there, we have just packaged and published a ntfy app package for Cloudron and it works great!

Awesome!

> Is there a possibility to have the original icon in svg or at least 512x512 px of sorts? 

Yeah the assets stuff is very very unorganized. Somehow it's in the ntfy-android repo here: 

https://github.com/binwiederhier/ntfy-android/tree/main/assets

This is the one that I always suggest: https://github.com/binwiederhier/ntfy-android/blob/main/assets/appstore_ios.svg

This is the one you have: https://github.com/binwiederhier/ntfy-android/blob/main/assets/favicon.svg

**Comment by nebulade** [comment]
Ah awesome and thanks for the prompt reply. We will go with the one without background for the moment, as that works out better in the areas the logo is shown on Cloudron.

**Comment by binwiederhier** [comment]
On https://www.cloudron.io/store/sh.ntfy.cloudronapp.html, the version says 1.0.0. Is that maybe from the package.json? That version is never updated and wrong. You have to use the Git version instead.

**Comment by nebulade** [comment]
Thanks for the hint, but in this case this is the app package version. We also have an `upstreamVersion` field in the package manifest https://git.cloudron.io/cloudron/ntfy-app/-/blob/main/CloudronManifest.json#L4 

Tbh it is not the first time people got confused :/

**Comment by binwiederhier** [comment]
Oh my apologies. Makes sense that you have your own manifest version. 

I've had my fair share of people being confused at things in my app. Hehe.
