### ISSUE TITLE
Arch Linux instructions

### ISSUE THREAD

**Issue by binwiederhier** [binwiederhier/ntfy#63]
Hey @arjan5 I just randomly found this: https://aur.archlinux.org/packages/ntfysh-bin/
Thank you for packaging it and even keeping it up-to-date. 

You wanna add install instructions for Arch to the docs? I wouldn't know how to do that for Arch.

**Comment by arjan-s** [comment]
Sure, no problem!

**Comment by binwiederhier** [comment]
@arjan-s Awesome, this is the relevant doc: https://github.com/binwiederhier/ntfy/blob/main/docs/install.md
