### ISSUE TITLE
Query parameters accept only lowercase parameter names

### ISSUE THREAD

**Issue by bbaa-bbaa** [binwiederhier/ntfy#630]
The parameter names are described as case-insensitive in the documentation, but only lowercase is accepted when passed by the query parameters

**Comment by wunter8** [comment]
Is there a specific query parameter you're having problems with? All of the following work fine for me.

`curl "https://ntfy.sh/mytopic/publish?message=testing"`
`curl "https://ntfy.sh/mytopic/publish?Message=testing"`
`curl "https://ntfy.sh/mytopic/publish?mEsSAgE=testing"`

**Comment by binwiederhier** [comment]
As per https://github.com/binwiederhier/ntfy/pull/661#issuecomment-1458700198, I think we're not going to do this. Instead, we'll just update the docs to reflect that query params are lower-case only.

**Comment by binwiederhier** [comment]
Changed in the docs:

> The following is a list of all parameters that can be passed when publishing a message. Parameter names are **case-insensitive** when used in **HTTP headers**, and must be **lowercase** when used as **query parameters in the URL**. They are listed in the table in their canonical form.

**Comment by wunter8** [comment]
lgtm
