### ISSUE TITLE
Android: Subscription icons are messed up 

### ISSUE THREAD

**Issue by topcaser** [binwiederhier/ntfy#634]
Hi, I have set an Abo icon for two of my abos. This works fine. But my other two abos which I haven't configured are showing up randomly either the icon of the first or second abo.

**Comment by binwiederhier** [comment]
What's an "abo icon"?

**Comment by binwiederhier** [comment]
Not sure what you mean, so I'm closing this ticket. Feel free comment though, and I can re-open

**Comment by topcaser** [comment]
Hi, that's the name in the settings. I attached a screenshot. It's the left icon. The bottom two abos haven't set an icon at all but they show one.

**Comment by binwiederhier** [comment]
I don't see a screenshot. I'm happy to help. I just don't know what's up.

**Comment by topcaser** [comment]
Hi, I edited the post yesterday and provided a link to the screenshot. Hope that helps.

**Comment by binwiederhier** [comment]
Oh I see. So you are saying that the icons that you associated with the subscriptions are incorrect? 

Let me know if this is accurate: 
- You have 4 subscriptions (A, B, C and D), and only two of them have icons (let's call them A and B)
- The two subscription without icons (C and D) are showing the icons from either A or B

Correct?

--

I have a vague idea of what this could be, but I have never heard of it happening before. My thought is that the RecyclerView is reusing, but not properly resetting the ImageView component used for the icon. This should be an easy fix, if this is what it is, and it's easy to reproduce. It'll be a bit until I do Android work again, but not very long I think.

/cc @wunter8

**Comment by topcaser** [comment]
Yep, that's exactly the issue. Thanks for looking into.

**Comment by topcaser** [comment]
Yep, that's exactly the problem. I deleted the screenshot since it contained some subscriptions and other data
