### ISSUE TITLE
Healtcheck with custom `listen-http`

### ISSUE THREAD

**Issue by Andersbiha** [binwiederhier/ntfy#635]
I'm running Ntfy in a docker-compose setup with Traefik in front.

Upon upgrading from `1.31.0` to `2.0.1` I'm no longer able to access Ntfy through Traefik.

I've traced the issue down to the container health checks added in #555.
The health check doesn't take the  `listen-http` setting into account, causing issues for those of us who's not running Ntfy on `localhost:80`.

This issue is easily fixed by either disabling the health check or overriding the default health check URL (See https://docs.docker.com/compose/compose-file/compose-file-v2/#healthcheck).

**Comment by binwiederhier** [comment]
Do you suggest I remove the HEALTHCHECK in the Dockerfile entirely? Or let people override it like you did? Maybe this can be added to the docs somewhere?

I am leaning towards removal entirely, honestly. The healthcheck doesn't add much.

**Comment by Andersbiha** [comment]
I would remove it and add a section to https://docs.ntfy.sh/install/#docker describing how to configure it.

I suspect leaving it in the Dockerfile is gonna be a source of confusion and it will most likely affect more people than removing it again.

**Comment by djraw** [comment]
> I am leaning towards removal entirely, honestly. The healthcheck doesn't add much.
Deleting the healthcheck entirely gets my +1

I have a supposedly "unhealthy" ntfy because I don't run it on port 80 outside the container.
As I use watchtower to automatically update, the healthcheck disable or override using composer gets reset on the updates. So I would prefer to remove the healthcheck.
We will notice a not running ntfy container soon enough anyway when scripts fail to send notifications. ;)

**Comment by Andersbiha** [comment]
I quickly whipped together a fix [here](https://github.com/binwiederhier/ntfy/compare/main...Andersbiha:ntfy:fix-635) .

Let me know if you want me to make a PR :+1:

**Comment by binwiederhier** [comment]
@Andersbiha That looks great. I'll happily accept that PR.

**Comment by Andersbiha** [comment]
@binwiederhier Thank you for a great project and the quick merge. :+1:
