### ISSUE TITLE
Can't receive notifications on Android app

### ISSUE THREAD

**Issue by devbian7** [binwiederhier/ntfy#639]
Hi!

We are developing an application for Android and we have a problem when receiving messages. 

We have installed the ntfy server and opening the web ui, we can suscribe to topics and send messages correctly.

However in Android application, using unifiedpush, the endpoint matches correctly but when we send a message we don't receive anything on the mobile. 

Do you have any example to connect from Android to ntfy server using unifiedpush?

Thanks in advance.

**Comment by binwiederhier** [comment]
Enable debugging on the ntfy server. That'll tell you all the details.

You can use the "UP Example" app as an example.

**Comment by binwiederhier** [comment]
Troubleshooting is best done via chat in Discord/Matrix. Closing this due to lack of response. Feel free to comment if you need more help.
