### ISSUE TITLE
android: UnifiedPush unregister doesn't remove the subscription from the list

### ISSUE THREAD

**Issue by emersion** [binwiederhier/ntfy#642]
I'm using the UnifiedPush SDK.

When calling `unregister` on an existing endpoint, my `onUnregistered` callback gets triggered as expected, however the subscription remains listed in the ntfy app. This causes the list in the app to grow in an unbounded fashion, ending up with hundreds of subscriptions after a month or so.

**Comment by emersion** [comment]
> my onUnregistered callback gets triggered as expected

This sounds like a bug in the Flutter connector sadly:

https://github.com/UnifiedPush/flutter-connector/blob/main/unifiedpush_android/lib/unifiedpush_android.dart#L50

**Comment by binwiederhier** [comment]
I am always happy to help, but this seems like it should not be a bug report in ntfy, no? 

I am respectfully closing this ticket, but feel free to comment and we can discuss more.
