### ISSUE TITLE
iOS notifications repeats if ignored 

### ISSUE THREAD

**Issue by Dima-Kal** [binwiederhier/ntfy#644]
Hi, first of all thanks for such an amazing project that allows for easy notifications setup, this made a huge impact on my workflows!
There is an issue that if I receive notification on iOS and do not open it, after some time (don’t think there is an exact amount) the notification will repeat itself which causes confusion, to mitigate it I’ve added time stamps to the notifications, but would still like this not to happen, has anyone also experienced this?

**Comment by atomicangel** [comment]
I have experienced this as well. One of the things I noticed specifically was that turning off disk caching helped mitigate the issue. I was looking at the webserver logs (I use nginx) and noticed that the initial notification didn't trigger an access log, however the subsequent notification did. The access log indicated that the iOS client was doing a GET request and checking for any "old"/"unreceived" messages. After turning off the disk cache and restarting the service, I do not experience the issue any further, even if I don't acknowledge the notification.

**Comment by Dima-Kal** [comment]
> I have experienced this as well. One of the things I noticed specifically was that turning off disk caching helped mitigate the issue. I was looking at the webserver logs (I use nginx) and noticed that the initial notification didn't trigger an access log, however the subsequent notification did. The access log indicated that the iOS client was doing a GET request and checking for any "old"/"unreceived" messages. After turning off the disk cache and restarting the service, I do not experience the issue any further, even if I don't acknowledge the notification.
> 
> Edit: I'm still experiencing double notifications if another notification comes through and I haven't acknowledged the original notification.

by disabling disk cache you mean setting "cache-duration: "0"" ?

**Comment by atomicangel** [comment]
> by disabling disk cache you mean setting "cache-duration: "0"" ?

No, I just commented out all cache related sections.

`#cache-file: /var/cache/ntfy/cache.db
#cache-duration: "12h"
`

**Comment by Dima-Kal** [comment]
> > by disabling disk cache you mean setting "cache-duration: "0"" ?
> 
> No, I just commented out all cache related sections.
> 
> `#cache-file: /var/cache/ntfy/cache.db` `#cache-duration: "12h"`

these settings were not enabled the example (and so also not enabled in my config)

**Comment by binwiederhier** [comment]
iOS dup notifications are a known bug. My guess is that it's because iOS is not processing the original APNS notification until it wakes up for the regular polling, and then delivers both messages at the same time. 

I think I need to get rid of the polling. iOS is on the long list of things to do. But I'm only one guy...

**Comment by binwiederhier** [comment]
This is a dup of #316
