### ISSUE TITLE
Android: Add `Rate-Topics:` header to UnifiedPush subscriptions

### ISSUE THREAD

**Issue by binwiederhier** [binwiederhier/ntfy#652]
For UnifiedPush topic subscriptions, we need to add a header `Rate-Topics: ...` to the JSON stream and WebSocket Connection, so that the server can rate limit based on the subscriber. Right now, this is done solely based on the topic name `up<12 digits>`, which was meant to be temporary.

**Comment by wunter8** [comment]
Haha, I'll see if I can get to this over the weekend. What exactly am I doing, though?? Is there a Discord/Matrix thread I should refer to for context?

**Comment by binwiederhier** [comment]
Basically, you're listing all UnifiedPush topics in the GET request for the subscription connection, e.g. 

```
# HTTP stream
GET /mytopic,up1234567890,backups-yolo,up11231323/json HTTP/1.1
Rate-Topics: up1234567890,up11231323

# Websocket
GET /mytopic,up1234567890,backups-yolo,up11231323/ws HTTP/1.1
Rate-Topics: up1234567890,up11231323

# Polling
GET /up1234567890/json?poll=1 HTTP/1.1
Rate-Topics: up1234567890
```

This will tell the ntfy server to register visitor as a rate visitor for the UP topics, but not the others. I am happy to give more details, but this is poorly documented, as it is still be ironed out.
