### ISSUE TITLE
Support RTL layout

### ISSUE THREAD

**Issue by BoFFire** [binwiederhier/ntfy#663]
Hi,

The ntfy Web UI is not yet supporting RTL `RightToLeft`. May be it could be added later for example for arabic, farsi and hebrew.

For now, the layout is LTR `LeftToRight` only.

**Comment by binwiederhier** [comment]
This is a reasonable request. 

I would assume that this involves associating a direction with a language, and then using that in all sorts of web elements like so `dir={prefs.getDir()}`. It doesn't seem hard, albeit a little tedious.

**Comment by mmojadad** [comment]
Hello
This is my request too, Please add RTL supporting.

**Comment by mmojadad** [comment]
ntfy automatically change direction based on language set
