### ISSUE TITLE
Autentication failed in latest version

### ISSUE THREAD

**Issue by skibbipl** [binwiederhier/ntfy#675]
:lady_beetle: **Describe the bug**
I'm using ntfy since few days. I've configured few users and topics. Today I upgraded to latest 2.2.0 version and I when I added new user it cannot post topics.

:computer: **Components impacted**
ntfy server

:bulb: **Screenshots and/or logs**
In previous version:
```
ntfy user add olduser
ntfy access olduser test write-only

curl -u olduser:olduser -d "Test" https://my-url/test
{"id":"imdZq5SLPAWT","time":1679241029,"expires":1679284229,"event":"message","topic":"test","message":"Test"}
```

In current version:
```
ntfy user add newuser
ntfy access newuser test write-only

curl -u newuser:newuser -d "Test" https://my-url/test
{"code":40101,"http":401,"error":"unauthorized","link":"https://ntfy.sh/docs/publish/#authentication"}
```

:crystal_ball: **Additional context**
I enabled logs, but nothing is logged. Also users created in previous version are still working fine.

**Comment by binwiederhier** [comment]
What did you upgrade from? v1.x? 

Can you show the output of the ACL? `ntfy access`?

Try to enable debugging and see if there are any additional clues? https://docs.ntfy.sh/config/#logging-debugging

**Comment by skibbipl** [comment]
False alarm, I was pointing to different instance of ntfy server on my reverse proxy 😲
