### ISSUE TITLE
How to setup in Railway?

### ISSUE THREAD

**Issue by p-samuel** [binwiederhier/ntfy#681]
:question: **Question**

Hi there, I've trying to setup a private server on railway's website through a Dockerfile. Here is it:

```
FROM binwiederhier/ntfy
EXPOSE 80
EXPOSE 443
COPY server.yml /etc/ntfy/server.yml
ENTRYPOINT ["ntfy", "serve"]

```

And here is my server.yml:

```
base-url: "https://ntfy-server-production.up.railway.app"
```
Everything seems to be working when I send the deploy command through my terminal.

![Screen Shot 2023-03-23 at 19 07 22](https://user-images.githubusercontent.com/53358247/227376644-311e66b9-0213-4a29-ba81-4aa8675c2c50.png)

But when I try to access I'm getting a server error.

![Screen Shot 2023-03-23 at 19 15 15](https://user-images.githubusercontent.com/53358247/227376898-bda95124-d238-47ea-80ef-f64eca66330c.png)

Any suggestions on what I'm missing?

**Comment by p-samuel** [comment]
Trying by curl also happens to give the same error

```
curl -s https://ntfy-server-production.up.railway.app/test/json         
```

**Comment by p-samuel** [comment]
I found the solution: **I must to provide the port environment variable in the project's settings on Railway's dashboard**

Thanks anyway.

**Comment by binwiederhier** [comment]
If you'd like, you could provide an example with screenshots for the examples page: https://docs.ntfy.sh/examples/

**Comment by p-samuel** [comment]
@binwiederhier, is a YouTube video valid one? 

https://youtu.be/L49wM84ivzE

**Comment by binwiederhier** [comment]
@p-samuel Awesome!! I'll add it to the examples page.

**Comment by binwiederhier** [comment]
Wait, where did the video go? I watched it the other day and now it's gone.

**Comment by p-samuel** [comment]
@binwiederhier , sorry, I've uploaded again because the audio was too bad.

https://youtu.be/auJICXtxoNA
