### ISSUE TITLE
Add priority 0 without notification for intent purpose

### ISSUE THREAD

**Issue by andreapx** [binwiederhier/ntfy#683]
:bulb: **Idea**
I use NTFY to automate some tasks on Android with Tasker (apart for alerting about stuffs), but for this purpose, NTFY notifications are useless and...actually too much.
What about add a priority level 0 with no notification so that we can use those messages just with intent on other apps?

:computer: **Target components**
This should be added server side and in the smartphones app.

**Comment by binwiederhier** [comment]
You can just mute the topic and then it will not alert at all. This is documented (even with a screenshot) here: https://docs.ntfy.sh/subscribe/phone/#react-to-incoming-messages

**Comment by andreapx** [comment]
Ops...sorry about that, I've missed it
Thanks!
