### ISSUE TITLE
Consider setting FCM priority to "high" for better delivery

### ISSUE THREAD

**Issue by abrender** [binwiederhier/ntfy#70]
I noticed that [Instant Delivery](https://ntfy.sh/docs/subscribe/phone/#instant-delivery) is recommended for instant alerts because "Without instant delivery, messages may arrive with a significant delay".

A bit of snooping reveals that you can [set the priority of a message to "high"](https://firebase.google.com/docs/cloud-messaging/concept-options#setting-the-priority-of-a-message), which will "allow FCM to wake up a sleeping device when necessary".  That functionality appears to be limited/bucketted but "if, in response to a high priority message, a notification is displayed in a way that is visible to the user, then your app standby bucket quota will not be consumed by that message".

**Comment by binwiederhier** [comment]
Thank you for the suggestion. I remember seeing it, but there was some comment about not misusing it, or otherwise there will be some penalty. I forgot, but I'll read up on it again.

**Comment by binwiederhier** [comment]
Ah yes it's right there

>  High priority messages generally should result in user interaction with your app or its notifications. If FCM detects a pattern in which they don't, your messages may be de-prioritized.

**Comment by binwiederhier** [comment]
> if, in response to a high priority message, a notification is displayed in a way that is visible to the user, then your app standby bucket quota will not be consumed by that message

wait so do you think this means that if i display a notificaiton visible to the user, then the de-prioritization won't happen?

**Comment by binwiederhier** [comment]
I think it may be worth setting the FCM priority to high for ntfy priorities 4 and 5, but I think I may need to create a limiter to regulate how often it's used. I will have to do some more research.

**Comment by binwiederhier** [comment]
@abrender With the next server release, messages with priority 4+5 (high+max) will be FCM high priority messages
