### ISSUE TITLE
Using ntfy.sh, messages take hours to arrive (Android)

### ISSUE THREAD

**Issue by go-vegan** [binwiederhier/ntfy#702]
I was under the impression that the public ntfy.sh server uses FCM and does not require using the instant delivery method.
Was I wrong?

**Comment by binwiederhier** [comment]
Closing this for now. Let me know if you still have issues. Happy to re-open

**Comment by go-vegan** [comment]
I'm using LineageOS 18.1 and have excluded the app from the battery optimization.
Also tried clearing the app's data and reinstalling several times.

If I remember correctly, it started after restoring the app using Titanium Backup, but now whatever I do I can't seem to fix it :(
