### ISSUE TITLE
App subscription filters

### ISSUE THREAD

**Issue by egooner** [binwiederhier/ntfy#703]
:bulb: **Allow tag filtering in Android app**

:computer: **Android App**

I notice that the API supports tag filters but trying to subscribe on the Android app using the filter string is not permitted.

Either allow using the filter string to the subscription or allow aging filters within the subscription settings.

**Comment by egooner** [comment]
I did try using a topic of zzzz,tags=xxxx but the subscribe option doesn't allow it

I was hoping to have a general topic that could be published to and different clients filter the information based upon the tag like it's permitted in the API.

**Comment by binwiederhier** [comment]
I have given this more thought and I don't think I want to implement subscription filters. Thank you for taking the time to open a ticket.
