### ISSUE TITLE
Topic creation restricted to one user?

### ISSUE THREAD

**Issue by Zitus** [binwiederhier/ntfy#706]
:question: **Question**
Is it possible from a web script (not having Ntfy as a private server) to create a topic where only one user can be subscribed?
Or, if it's not possible, having my own Ntfy server can I know how many subscribers a topic has, and reject or delete subscriptions if more than one?

**Comment by binwiederhier** [comment]
>  Is it possible from a web script (not having Ntfy as a private server) to create a topic where only one user can be subscribed?

Pubsub generally allows many subscribers, and ntfy does not implement subscriber limits per topic either.

>  Or, if it's not possible, having my own Ntfy server can I know how many subscribers a topic has, and reject or delete subscriptions if more than one?

Topic subscriptions are kept in memory and are not exposed in any way right now. I suggest you just create a user and reserve a topic, or you update your access controls manually to allow only the authorized user to access the topic.
