### ISSUE TITLE
Clear notification history automatically in app

### ISSUE THREAD

**Issue by arjan-s** [binwiederhier/ntfy#71]
I'd like each topic in the Android app to have a setting to expire and clean up the notification history after a certain time. For some topics I would not want a history at all, for others I would want it to contain only the notification history for the last few days.

**Comment by binwiederhier** [comment]
I like this. And I actually initially wanted to auto-delete after 2 weeks or so, but I never implemented it.

I have tons of ideas for cool settings that are easy to implement, but need a per-topic settings screen (sounds, check interval, delete-after, ...), but I need to do the legwork to create a settings screen first.

Thanks for reporting this. I'll eventually get to it. I like it!

**Comment by binwiederhier** [comment]
I implemented a global setting https://github.com/binwiederhier/ntfy-android/commit/d44358f75c9cd7b27580f3f126376a43068b85c2 and I'll close this ticket for now; I have another ticket to port all global settings to per-topic settings as well. I'll make sure auto-delete is part of that.
