### ISSUE TITLE
server/topic.Subscribe can produce duplicate subscriber IDs

### ISSUE THREAD

**Issue by peterbourgon** [binwiederhier/ntfy#712]
https://github.com/binwiederhier/ntfy/blob/6ad3b2e8020082a5b7206d36d425f925354cd059/server/topic.go#L50

```go
// Subscribe subscribes to this topic
func (t *topic) Subscribe(s subscriber, userID string, cancel func()) int {
	t.mu.Lock()
	defer t.mu.Unlock()
	subscriberID := rand.Int() // <---- here
	t.subscribers[subscriberID] = &topicSubscriber{
		userID:     userID, // May be empty
		subscriber: s,
		cancel:     cancel,
	}
	t.lastAccess = time.Now()
	return subscriberID
}
```

Nothing prevents `subscriberID := rand.Int()` from producing an integer which is already present in the `t.subscribers` map. In that case, the previous subscriber is over-written.

**Comment by dropdevrahul** [comment]
can I pick this up?

**Comment by dropdevrahul** [comment]
@binwiederhier tried a fix with https://github.com/binwiederhier/ntfy/pull/713

**Comment by dropdevrahul** [comment]
Please not Just added a simple retry mechanism and added a test case to catch the edge case

**Comment by binwiederhier** [comment]
Thanks to you both. The best effort retry should be enough.
