### ISSUE TITLE
Provide minimal docker image and binaries, possibly split docs to its own package. 

### ISSUE THREAD

**Issue by jauderho** [binwiederhier/ntfy#72]
I was trying to compile my own container image using the following build command:

`go build -o ntfy -v -trimpath -ldflags="-s -w -X main.version=v1.10.0" .`

This failed with the error message of `server/server.go:116:13: pattern docs: no matching files found` which appears to be a go:embed directive for docs. Removing this line allows for the compilation to successfully complete.

Here's the line in question: https://github.com/binwiederhier/ntfy/blob/9752bd7c30d9b5620ccb610949f732fc847a8a18/server/server.go#L116

**Comment by binwiederhier** [comment]
@jauderho Ah yes, I'm sorry I had this the other day and it drove me mad, but I forgot to fix it: `make docs` will fix it.
You have to install `mkdocs`.

**Comment by binwiederhier** [comment]
My apologies this is so hard, I should make a github action that does the full build as an example. I haven't done a clean build in a while.

**Comment by binwiederhier** [comment]
```
$ pip list |grep mkdocs
mkdocs                     1.2.3
mkdocs-material            8.0.1
mkdocs-material-extensions 1.0.3
mkdocs-minify-plugin       0.5.0
```

Should be enough to do `pip install -r requirements.txt`

**Comment by jauderho** [comment]
@binwiederhier I don't suppose there is a way to avoid having to do the mkdocs step? I'm looking to build a minimal image which is why I was going with the singular build command. Removing that line seemed to allow the build to complete. 

I suppose I could use a small patch to patch that out.

**Comment by binwiederhier** [comment]
@jauderho I'm happy to accept PRs and adjust the build to fit your needs, but removing the go:embed line basically removes the docs entirely and will likely lead to horrible errors. You could create an empty folder `server/docs/`, that would probably do it.

**Comment by jauderho** [comment]
I just tried your suggestion of creating an empty `server/docs/` but still run into the same error. Any other ideas?

I suppose I could just add the necessary commands to build the docs. Brb, editing Dockerfile.

**Comment by binwiederhier** [comment]
I just pushed this: https://github.com/binwiederhier/ntfy/commit/96ad49f675b418245886f621481228948826e231

This makes `make build-simple` work again. I think you could do something similar with the other targets

**Comment by jauderho** [comment]
Having the dummy file did the trick! I ended up building the container both with and without docs and there's about 11MB in difference in the final image. 

Anyways, I now have a working image for different archs: https://hub.docker.com/repository/docker/jauderho/ntfy

Dockerfile here: https://github.com/jauderho/dockerfiles/blob/main/ntfy/Dockerfile

**Comment by binwiederhier** [comment]
I could probably build a ntfy-minimal image using the GoReleaser stuff. If that's something you desire. :shrug: Not any time soon though (too much other stuff).

**Comment by jauderho** [comment]
If you are willing to have a server/docs/dummy stub in your repo, I can create a basic .goreleaser.yml that should do the right thing.

This one should work: https://gist.github.com/jauderho/451d1ca80c7734c51ef47ea87672d1e1

I can submit as a pull request if needed.

**Comment by binwiederhier** [comment]
Thank you for the contribution. I if you can modify the existing GoReleaser file to build two images, one normal and one minimal would be fantastic.

**Comment by binwiederhier** [comment]
I've overhauled the developer documentation (see https://github.com/binwiederhier/ntfy/blob/main/docs/develop.md), but I don't think I want to provide additional minimal packages for now. I realize that 17 MB as opposed to 7 MB is not great, but I think it's fine. If you feel strongly I may change my mind though. Closing this ticket for now.
