### ISSUE TITLE
Android App - Broadcast happens immediately, not when action button is tapped

### ISSUE THREAD

**Issue by arnbrhm** [binwiederhier/ntfy#720]
:lady_beetle: **Describe the bug**
Per the documentation

> The broadcast action sends an Android broadcast intent when the action button is tapped.

I am using Tasker to launch an app when the intent action io.heckel.ntfy.USER_ACTION is broadcast. When the message notification is displayed by the ntfy app, along with the action button, Tasker fires as though it has received the intent action (without me tapping the action button).  Also, if I open the ntfy app and tap on the action button, nothing happens. 

:computer: **Components impacted**
Android app

:bulb: **Screenshots and/or logs**
none

:crystal_ball: **Additional context**
a snippet of my code:
```
    ;Create a HTTP COM object
    $oHttp = ObjCreate("winhttp.winhttprequest.5.1")
 
    With $oHttp
        ;Open POST request
        .Open("POST", "https://ntfy.sh/Broadcast-Test", False)

        ;Set request headers and options
        .SetRequestHeader("Content-Type", "text/plain")
        .SetRequestHeader("Title", "This is the title")
        .SetRequestHeader("Action", "broadcast, Open App")
```

**Comment by binwiederhier** [comment]
Logs from Android would be helpful here.

**Comment by wunter8** [comment]
It's working fine for me in Tasker. This is how I set up the `Intent Received` profile

![Screenshot_20230509-194028](https://github.com/binwiederhier/ntfy/assets/8421688/33d9fede-f865-4007-8616-a29f1665f4ed)

**Comment by arnbrhm** [comment]
This was my rookie mistake.  I mixed up io.heckel.ntfy.USER_ACTION and io.heckel.ntfy.MESSAGE_RECEIVED in Tasker.  I wasn't aware that there were two different broadcasts.
