### ISSUE TITLE
Port missing in URL for "send notification" via web gui / attachement

### ISSUE THREAD

**Issue by un99known99** [binwiederhier/ntfy#726]
Port missing in URL for "send notification" via web gui / attachement see screenshot:

![grafik](https://github.com/binwiederhier/ntfy/assets/1615207/b29d9e90-fd88-425a-b3a5-8939b7d68801)

![grafik](https://github.com/binwiederhier/ntfy/assets/1615207/cf59483a-26ff-471b-b590-aaa54fec293c)

should look like https://ntfy.example.org:9999/file/Xx7CQB4e8c25.exe, right?

BTW: is it intended that file name in link is not reflecting original filename?

**Comment by wunter8** [comment]
Do you have the port included in the `base-url` config in `server.yml`?

Also, yes, the filename will be different. It generates a random ID to prevent anyone from guessing the URL since it isn't protected by access controls. If you want the filename to be something else when you download it, you can include the `Filename` header

**Comment by un99known99** [comment]
Hi, thx, correct, stupied me, didnt include URL PORT. For the clear filename I checked Server.yml but didnt find the parameter for getting Real name, can u guide me to the correct parameter name?

Thx in advance

**Comment by wunter8** [comment]
You need to include the `Filename` header with each message you send. See https://docs.ntfy.sh/publish/#attach-local-file

I'm pretty sure the web app automatically adds the `Filename` header. The attachment link will still include a random ID, but when you download the file, it's name should be correct.

**Comment by un99known99** [comment]
ah, ok, but via the "testing"  it seems not to be possible:

![grafik](https://github.com/binwiederhier/ntfy/assets/1615207/aded6440-a1f0-4905-a5da-e4166ea9d070)

![grafik](https://github.com/binwiederhier/ntfy/assets/1615207/7d49f379-5de3-44de-8391-c9febf70db32)

**Comment by wunter8** [comment]
Did you try downloading the file? It should have the correct filename after it's downloaded even though the download URL has the random ID

**Comment by un99known99** [comment]
nope, not working:

![grafik](https://github.com/binwiederhier/ntfy/assets/1615207/473933bb-fd8a-44ed-a5f0-992cda63dcbd)

**Comment by wunter8** [comment]
How did you send the notification with the attachment?

**Comment by un99known99** [comment]
yepp:

![grafik](https://github.com/binwiederhier/ntfy/assets/1615207/d1a043a0-a214-4ab2-8526-f314330ed274)

**Comment by wunter8** [comment]
I'm sorry. You are correct. I was testing it from the Android app, not the web app. In the Android app, including the `Filename` header in the request (which the web app does) makes the downloaded file have the correct name. But when you download the file in the browser/using the web app, the downloaded file does not have the correct name (whether or not the `Filename` header was included)

**Comment by un99known99** [comment]
no worries, I still love the tool, thx for your support

**Comment by wunter8** [comment]
@binwiederhier What do you think about adding this so that when you click "Open attachment" in the web UI it will automatically download the file with the correct filename? I just tested it locally, and it seems to work.
```
diff --git a/server/server.go b/server/server.go
index c0ebc6e..fbf82eb 100644
--- a/server/server.go
+++ b/server/server.go
@@ -642,6 +642,10 @@ func (s *Server) handleFile(w http.ResponseWriter, r *http.Request, v *visitor)
                return err
        }
        defer f.Close()
+       if m.Attachment.Name != "" {
+               w.Header().Set("Content-Disposition", "attachment; filename="+strconv.Quote(m.Attachment.Name))
+       }
        _, err = io.Copy(util.NewContentTypeWriter(w, r.URL.Path), f)
        return err
 }
```

**Comment by binwiederhier** [comment]
Sounds good to me.
