### ISSUE TITLE
Subscribing to topics

### ISSUE THREAD

**Issue by RogueGhost93** [binwiederhier/ntfy#738]
Thanks for you amazing project!
Im wondering if this is a normal behaviour:

Every time I open https://my.domain.com i have to Re-Subscribe to all of my topics in order to see previous or future notifications. On android app it always stays subscribed so im wondering if that could be done on PC too. Can it be turned on in settings or somewhere so that all of the topics are always shown once I go to the webpage of my server? Thanks in advance!

**Comment by binwiederhier** [comment]
I assume this is a question about the web app. The web app is supposed to keep your subscriptions and messages stored locally in the browser's IndexedDB. Normal browsers support that, but the incognito mode does not.

**Comment by RogueGhost93** [comment]
My bad, i had automatical removal of cookies so thats why the notification topics had to be added every single time.
