### ISSUE TITLE
Rate limiting for upstream push notifications

### ISSUE THREAD

**Issue by nimbleghost** [binwiederhier/ntfy#740]
:question: **Question**

How is the upstream push notification request limit calculated? I see a message like this for every publish, but it doesn't look like the limit is being hit in the log nevertheless:

```
2023/05/23 10:02:16 WARN Unable to publish poll request, unexpected HTTP status: 429 (
	message_body_size=4,
	message_event=message, 
	message_id=<id>, 
	message_sender=<ip>, 
	message_time=<ts>, 
	topic=<topic>,
	visitor_auth_limiter_limit=0.016666666666666666,
	visitor_auth_limiter_tokens=30,
	visitor_id=ip:<ip>, 
	visitor_ip=<ip>,
	visitor_messages=442,
	visitor_messages_limit=17280,
	visitor_messages_remaining=16838,
	visitor_request_limiter_limit=0.2,
	visitor_request_limiter_tokens=59.0214558084, 
	visitor_seen=<today>
)
```

I had an Uptime Kuma check making sure that publish was working, so publishing about once a minute - but that shouldn't hit the rate limits in general, I believe?

**Comment by binwiederhier** [comment]
Once a minute is too much for the upstream server (ntfy sh). The current rate limits for the free plan is 250/day, and there are 1440 minutes in a day. 

You can purchase a ntfy Pro plan and set up `upstream-access-token` I'd you need more. Or you can compile and set up the iOS app yourself, of course.

**Comment by nimbleghost** [comment]
Oh I see, thanks. Am I reading the logs incorrectly? If not - would it be possible to make it clearer that it's hitting this 250/day limit? (Is that based on publisher and not subscriber/visitor?).

**Comment by binwiederhier** [comment]
This error happens when your selfhosted ntfy server send a "poll request" to the upstream server (ntfy.sh). So your rate limits are not affected, but the upstream rate limits are exceeded. 

You are right, I should make it clearer. I'll update the error message to make it clearer.
