### ISSUE TITLE
Typo on main website: Cloudtron should be Cloudron

### ISSUE THREAD

**Issue by distresscode** [binwiederhier/ntfy#741]
Hi. I'm not sure where I was supposed to report a typo so posting here.

On the main website, there's a typo under the "Integrate with your favorite tools" section. It's written as Cloudtron but it should be Cloudron (we all love Tron but there's no T in Cloudron).

 https://ntfy.sh/

![image](https://github.com/binwiederhier/ntfy/assets/2686608/8812fe29-f1af-445f-b6a4-e8739359791b)

**Comment by binwiederhier** [comment]
Oh. I'm an idiot. Thanks. :grimacing:

**Comment by binwiederhier** [comment]
Done.
