### ISSUE TITLE
Web app build / dev tooling - Vite, prettier, eslint?

### ISSUE THREAD

**Issue by nimbleghost** [binwiederhier/ntfy#744]
:bulb: **Idea**

I'd like to try tackling #199 / #346, but would like to make some development / build improvements first if they sound good to you.

I would switch to Vite to make [https testing easier](https://vitejs.dev/config/server-options.html#server-https) for notifications (and though not deprecated, CRA isn't recommended anymore anyway), plus would add eslint and prettier for static analysis and formatting.

:computer: **Target components**

web app

**Comment by nimbleghost** [comment]
Sounds great! I will comment on the web push issue once I get to it.

r.e. Discord/Matrix yes - will take a look later.

**Comment by binwiederhier** [comment]
> Sounds great! I will comment on the web push issue once I get to it.

It is worth noting that the PWA has been attempted before, so maybe check that code too when you get there.

**Comment by nimbleghost** [comment]
Resolved by #747, #748, #749
