### ISSUE TITLE
Enable "Webhook GET-style" publishing via POST requests (with Jsonpath support)

### ISSUE THREAD

**Issue by Fabian-G** [binwiederhier/ntfy#755]
:bulb: **Idea**
I'm thinking of using webhooks on webex (https://developer.webex.com/docs/api/v1/webhooks/create-a-webhook) to send push messages via ntfy to my phone when there are new messages, which works fine. However, the request send by webex looks something like this (some information stripped):
```
POST https://ntfy.sh/webex
```
```json
{
  "id": "<id>",
  "name": "Messages",
  "targetUrl": "ntfy.sh/webex",
  "resource": "messages",
  "event": "created",
  "orgId": "<id>",
  "createdBy": "<id>",
  "appId": "<id>",
  "ownedBy": "creator",
  "status": "active",
  "created": "2023-05-28T19:22:14.720Z",
  "actorId": "<id>",
  "data": {
    "id": "<id>",
    "roomId": "<id>",
    "roomType": "group",
    "personId": "<id>",
    "personEmail": "<email>",
    "created": "2023-05-28T19:22:58.361Z"
  }
}

```

Therefore (as expected) the notification message is the json body, which doesn't look nice. Since the only real option to modify that request that webex offers is  the `targetUrl`, I thought it would be nice to have the same options mentioned [here](https://docs.ntfy.sh/publish/#webhooks-publish-via-get), but for POST requests and therefore just ignore the body when the `?message="..."` parameter is present.

What would be even nicer, is an option to use string interpolation on the parameters, reading values from the body via jsonpath. 
For example: If I were to configure the `targetUrl` in webex as 
```
https://ntfy.sh/webex?message="New message from {{$.data.personEmail}}"
```
Ntfy would parse the json body and set the `message` of the notification to "New message from \<email\>".

:computer: **Target components**

- ntfy server

**Comment by nimbleghost** [comment]
@Fabian-G I believe what you want is simply this: https://docs.ntfy.sh/publish/#publish-as-json

**Comment by wunter8** [comment]
There has been discussion about custom mappings of JSON fields to ntfy's notification fields (e.g., `message`, `title`, etc.)

Nothing has been implemented yet, but you can see some of the discussion here: https://github.com/binwiederhier/ntfy/issues/724

**Comment by binwiederhier** [comment]
This is indeed a dup. I do like this templating approach too. I actually did implement this a year ago I think: #171 + #104

Closing as a dup in favor of #724
