### ISSUE TITLE
Notifications for android sometimes get delayed several minutes

### ISSUE THREAD

**Issue by happysalada** [binwiederhier/ntfy#757]
:lady_beetle: **Describe the bug**
Sometimes a notification sent will only be received on the android app several minute later.

:computer: **Components impacted**
 ntfy server, Android app

:bulb: **Screenshots and/or logs**
I haven't seen anything in the logs, maybe I should just increase the verbosity

:crystal_ball: **Additional context**
I'm not sure how to get additional context here, but happy to try anything.

**Comment by binwiederhier** [comment]
You're going to need to get some logs (mostly Android probably). Without logs, I cannot help. 

Are you using ntfy.sh or selfhosted?

If you are using ntfy.sh, are you using "instant delivery"?

In your Android app, are subscriptions showing "connecting ..."? If they do, you are not actually connected to your server.

**Comment by happysalada** [comment]
Self hosted, and im connected with the websocket.
Im sure im connected because im receiving 90% of the notifications instantly. Its just once in a while one takes several minutes.
Ill have a look at the logs and will paste them here next time this happens.
Thank you for this amazing software !

**Comment by binwiederhier** [comment]
If it's only every now and then it's likely Android killing the connection. It just happens. There is nothing you can do about it except disable battery optimization for ntfy. If it is this, you'll see a software abort exception in the logs. It's quite normal. But some manufacturers are worse than others. 

Also check: https://dontkillmyapp.com/

**Comment by happysalada** [comment]
Ive disabled battery optimization for the app though (which your very helpful onboarding guide helped )

**Comment by happysalada** [comment]
No worries at all, it hasnt happened since last time, next time ill only reopen if i have more info.
