### ISSUE TITLE
Message length limitation

### ISSUE THREAD

**Issue by arminus** [binwiederhier/ntfy#77]
While I'm thinking about scenarios in which I could use ntfy, I read that there is a message max length of 512 bytes (generally, or on your public instance?).

That could be a limiting factor down the road, may I ask why this limit is in place? And are there any plans to add additional payloads to messages? Right now this is purely theoretical...

**Comment by binwiederhier** [comment]
Surprise https://github.com/binwiederhier/ntfy/commit/7b37141e070bb1ad340af075d21a973885caf2a5
I increased it to 4k. It's not yet rolled out, though I will likely do that today.

**Comment by binwiederhier** [comment]
As for additional payloads, I am planning to add images + files very soon. There are tickets for it here: #25 and #15. There's so much work to do. But I don't think it'll take more than a couple of weeks until we have those features.

**Comment by binwiederhier** [comment]
Done in https://github.com/binwiederhier/ntfy/commit/7b37141e070bb1ad340af075d21a973885caf2a5

**Comment by binwiederhier** [comment]
@arminus This is released now.
