### ISSUE TITLE
Using : in default-command for subscribe leads to error

### ISSUE THREAD

**Issue by newhinton** [binwiederhier/ntfy#772]
:lady_beetle: **Describe the bug**
When using the `:`-char with the ntfy-cli tool in commands leads to errors:
`yaml: line 9: mapping values are not allowed in this context`

Example:
`default-command: notify-send -i /x/ntfy.svg --app-name "ntfy: $topic" "$t" "$m"`

:computer: **Components impacted**
ntfy-cli, linux amd64

:bulb: **Screenshots and/or logs**
See above.

:crystal_ball: **Additional context**

**Comment by binwiederhier** [comment]
I think you're just using invalid yml. Single quotes around it, or some other way to escape the value property. I'm sure Google or ChatGPT will help there.
