### ISSUE TITLE
SMTP server not accepting emails from internet

### ISSUE THREAD

**Issue by TheRealAlexV** [binwiederhier/ntfy#776]
:lady_beetle: **Describe the bug**
I'm attempting to use ntfy to receive email alerts from outside my private network. I've setup an aname and mx record, however upon sending an email using gmail, I get a bounce back(personal information censored):

```
Message not delivered
There was a problem delivering your message to test_alerts+mytokengoeshere@notify.mydomain.com. See the technical details below, or try resending in a few minutes.

The response from the remote server was:
554 5.0.0 Error: transaction failed, blame it on the weather: error: {"code":40101,"http":401,"error":"unauthorized","link":"https://ntfy.sh/docs/publish/#authentication"}
```

If I send a test email using nc, it works fine. 

:computer: **Components impacted**
ntfy server

**Comment by TheRealAlexV** [comment]
This has something to do with the token authentication when coming from the internet. I changed the topic access to write only and now it works.

**Comment by binwiederhier** [comment]
This is possibly a dup of https://github.com/binwiederhier/ntfy/issues/773

**Comment by binwiederhier** [comment]
You can try to manually modify your token in the sqlite database to be all lowercase and try if that works.

```
sqlite3 /var/lib/ntfy/user.db
select * from user_token;
update user_token set token='...' where token='...';
```

**Comment by binwiederhier** [comment]
I'm going to assume this is a dup of https://github.com/binwiederhier/ntfy/issues/773, let me know if you think it is not.
