### ISSUE TITLE
No help topic for 'shell-integration'

### ISSUE THREAD

**Issue by KillerOKPlanet** [binwiederhier/ntfy#777]
:lady_beetle: **Describe the bug**
I recently updated the ntfy package to the latest version. However, the shell-integration command is no longer working as expected. When I execute eval "$(ntfy shell-integration)", it is treating the command as if it is meant to be executed, rather than being recognized as an argument for internal logic.

:computer: **Components impacted**
ntfy server, shell integration

:bulb: **Screenshots and/or logs**
![image](https://github.com/binwiederhier/ntfy/assets/67013909/c4977ae8-59a3-4827-9838-a4fc09955216)

:crystal_ball: **Additional context**
ntfy 2.5.0 (df8b18b), runtime go1.19.9, built at 2023-05-18T18:01:45Z

I have previously added eval "$(ntfy shell-integration)" to my bashrc file for seamless integration. However, after the recent update, it no longer works correctly. The command ntfy shell-integration returns an error message saying "No help topic for 'shell-integration'."
I would appreciate any assistance in resolving this issue with the new version of ntfy. Thank you!

**Comment by binwiederhier** [comment]
I don't think that ever worked. When do you think it worked? Because I don't think I ever implemented shell completion.
