### ISSUE TITLE
Is there a way to disable instant delivery?? I don't need it

### ISSUE THREAD

**Issue by jvalrog** [binwiederhier/ntfy#796]
I'm using ntfy to just remember things, I don't need an instant service that drains my battery.
Is there a way to disable it?
If don't, do you know an alternative?

Thanks

**Comment by jvalrog** [comment]
> Related: #32, #76, #10
> 
> There is no way to disable it as of today. The only way would be to do a 15-30min interval timer in Android and poll. This is not hard to achieve, but the UX will suffer a lot, because it'll be weird to have so many options.

oh I see, thanks.

**Comment by gc-ss** [comment]
I'm assuming this is now implemented?
