### ISSUE TITLE
gui using gioui

### ISSUE THREAD

**Issue by gedw99** [binwiederhier/ntfy#797]
I prefer gio than react, so i think a gui version should be possible also.

The react app should be there for those that prefer that of course.

WIth GIOUI, it will build the Web, Desktop and Mobile app from a single golang code base.

##  Technical notes

URLS:

https://ntfy.sh/app

https://staging.ntfy.sh/app

---

GIOUI Notify package:  https://github.com/gioui/gio-x/tree/main/notify

- Has IOS, Android, Windows and MAC 
- Needs PWA ( JS )

---

GIOUI Notify example: https://github.com/gioui/gio-example/tree/main/notify

- Has Mac and IOS. 
- Needs PWA, Windows, Android Scaffold. 

- It already pulls in the GIOUI standard Component: https://github.com/gioui/gio-example/tree/main/component.

---

The GIOUI JS compiler needs some slight additions for the Service worker aspects: https://github.com/gioui/gio-cmd/blob/main/gogio/jsbuild.go

- The Services worker code is here: https://github.com/maxence-charriere/go-app

- Its generator for the JS Service worker is here: https://github.com/maxence-charriere/go-app/tree/master/pkg/app/gen

- The PWA notifications doc is here: https://github.com/maxence-charriere/go-app/blob/master/docs/web/documents/notifications-push.md

**Comment by binwiederhier** [comment]
I think we had this conversation in https://github.com/binwiederhier/ntfy/issues/128 a while back. And my views about gio have not changed. Plus, I have a web app now that is really polished, with a modern framework and UI and even a PWA. I don't want to rewrite it all. 

If others want to provide a third party client I am all for it. But that's not something that should be tracked here IMHO.

**Comment by gedw99** [comment]
No probs. Will do it elsewhere
