### ISSUE TITLE
Look at mqtt

### ISSUE THREAD

**Issue by binwiederhier** [binwiederhier/ntfy#8]

**Comment by binwiederhier** [comment]
I looked at mqtt and various Go libraries. It looks like a neat technology and specs. Long story short: I think I'm gonna pass and not implement it for ntfy. 

Reasons: It seems quite large for ntfy and for its use case. Lots to configure, lots to confuse people.

I could see implementing a MQTT client on the server side that we'd also publish to, kinda like firebase is implemented, basically just forward message to another pubsub system. But I'll only implement that of somebody really needs it. 

Libraries:
- Just a client: https://github.com/eclipse/paho.mqtt.golang
- As far as I can see not embeddable: https://github.com/fhmq/hmq
- broker lib: https://github.com/DrmagicE/gmqtt

**Comment by zoic21** [comment]
Hello,
I think it's can be a awesome idea. MQTT is more and more used especially by iot, place where ntfy.sh is used a lot. With mqtt (api and action) we can used ntfy.sh to send message from ESP32 (it's possible in HTTP but the library is very heavy compared to MQTT, when there is only 4mb or even 1mb it is not negligible).  And with the actions from the notification, you can imagine direct control scenarios without necessarily needing a home automation solution in the middle.

One can imagine when I open my garage door the module sends an MQTT frame to ask if I also need to open the gates. If I answer yes the portal module sees the request and executes

I don't see the work that it represents, especially in go, a language that I don't know, but on the other hand I can see the opening it gives in the home automation environment.

**Comment by jangrewe** [comment]
This would be awesome as lots of home automation projects use MQTT as their messaging bus! A typical use case would be openHAB just publishing its notifications to an MQTT topic as usual, and ntfy subscribing to that (user configurable) topic to ... well, notify. ;-)
Maybe even allow subscribing to multiple separate topics, to categorize where the notifications are coming from. My Frigate server would be a second candidate for a topic.

**Comment by Peptis** [comment]
For those that are interested, I have added MQTT support in my fork of ntfy: https://github.com/Peptis/ntfy
