### ISSUE TITLE
WooCommerce Push Notifications

### ISSUE THREAD

**Issue by mmojadad** [binwiederhier/ntfy#803]
I have an idea, Don't know is it possible via ntfy or not
WooCommerce  (Wordpress) Push Notifications
users subscribe to push notifications and will receive push based on events happen in WooCommerce  ( Abandoned Cart Notifications, In-Stock Notifications,Price Drop Notifications, Shipment Alert, etc )

**Comment by binwiederhier** [comment]
Publishing to ntfy is just a HTTP call, so if WooCommerce supports that an integration is easy. I do not know WooCommerce, neither do I feel responsible for investigating if it is possible to integrate. Please open a ticket with their issue tracker, or ask in their community about this.
