### ISSUE TITLE
Authencation support

### ISSUE THREAD

**Issue by johnlpe** [binwiederhier/ntfy#808]
Add support for authencation between application service -- ntfy instance and ntfy instace -- ntfy client.

**Comment by binwiederhier** [comment]
The GitHub issues have a template format for a reason. Please use it next time.

With these one sentence tickets, it's very hard to understand what you are even talking about. Please be more verbose.

ntfy has a sophisticated auth framework, see: https://docs.ntfy.sh/config/#access-control

**Comment by johnlpe** [comment]
Now notification aren't password protected and you have to order topics. I want something like this: 

I want to use mastodon.social and push notifications via ntfy.sh. I have installed Tusky and ntfy-client.

1. I register ntfy.sh with `username: example`,` passwowd: passoword1` and set follows for the application services (one for all or own for each) `username: example`, `password: password2`.
3.  I register mastodon.social and add my notification server details. They are: `URL: ntfy.sh`, `username: example`, `password: password2`.

Then when mastodon.social want send push notification to my device:
1. mastodon.social send notification according to details I gave it: `ntfy.sh, example, password2`.
2. ntfy.sh send notification to my phone with connection that is opened by ntfy client.
5. ntfy client send notification to my notification bus (e.g. Dbus).

**Comment by wunter8** [comment]
It sounds like you're describing what UnifiedPush already does. And Tusky specifically already supports UnifiedPush with ntfy (https://github.com/tuskyapp/faq/blob/main/README.md#notifications)

**Comment by johnlpe** [comment]
> It sounds like you're describing what UnifiedPush already does. And Tusky specifically already supports UnifiedPush with ntfy (https://github.com/tuskyapp/faq/blob/main/README.md#notifications)

Of course, ntfy is specifically UnifiedPush notification software (right?), but the problem is lack of authentication.

**Comment by wunter8** [comment]
ntfy supports UnifiedPush, but it can be (and often is) used without it.

When using UnifiedPush, a randomly generated ntfy topic (e.g., ntfy.sh/upbAfzAoFdCg99) is created that is used for all messages. Messages are "authenticated" by knowing the randomly generated topic. It is (practically speaking) as secure as a username/password combo.

To send/receive messages, you're talking about requiring a secret username/password combo that only you and Tusky know. ntfy/UnifiedPush is set up instead to require a secret topic that only you and Tusky know.

**Comment by johnlpe** [comment]
> ntfy supports UnifiedPush, but it can be (and often is) used without it.

Why? I think UnifiedPush is the future.

> When using UnifiedPush, a randomly generated ntfy topic (e.g., ntfy.sh/upbAfzAoFdCg99) is created that is used for all messages. Messages are "authenticated" by knowing the randomly generated topic. It is (practically speaking) as secure as a username/password combo.

Could we use username/password? And someone says that ntfy notifications is public?

> To send/receive messages, you're talking about requiring a secret username/password combo that only you and Tusky know. ntfy/UnifiedPush is set up instead to require a secret topic that only you and Tusky know.


Do you mean the mastodon instance and ntfy? Since mastodon instance like mastodon.social sends my notifications and Tusky is only client.

**Comment by binwiederhier** [comment]
> Why? I think UnifiedPush is the future.

My friend. Respectfully, I think you should do a little research and find out what ntfy actually is. And maybe check your manners in the process. 

> Could we use username/password? And someone says that ntfy notifications is public?

The UnifiedPush spec does not support this. The endpoint is the password.

--
Side note: You have opened many tickets and tried to push your agenda on this project. I am very very receptive to suggestions, as long as it is done in a respectful way. Ultimately, as project owner, though, I get to say "no" when I want to, or I don't agree with what you'd like to do. This is an open source piece of software, so you can always fork it if you don't like that.

**Comment by johnlpe** [comment]
>>Why? I think UnifiedPush is the future.
>
>My friend. Respectfully, I think you should do a little research and find out what ntfy actually is.

"ntfy (pronounced notify) is a simple HTTP-based [_pub-sub_](https://en.wikipedia.org/wiki/Publish%E2%80%93subscribe_pattern) notification service."

Yes, ntfy is publish-subscribe notification service, but is it reason to not support push notifications? And why do you think the pub-sub model is better?

> You have opened many tickets and tried to push your agenda on this project. I am very very receptive to suggestions, as long as it is done in a respectful way. Ultimately, as project owner, though, I get to say "no" when I want to, or I don't agree with what you'd like to do. This is an open source piece of software, so you can always fork it if you don't like that.

Sorry if I pressed, I didn't mean to. OFC you must have able to say no.
