### ISSUE TITLE
Is this licensed under Apache-2.0 or GPL-2.0?

### ISSUE THREAD

**Issue by johnlpe** [binwiederhier/ntfy#809]
Is ntfy licensed under Apache-2.0 or GPL-2.0?

**Comment by binwiederhier** [comment]
It is dual licensed. https://github.com/binwiederhier/ntfy#license

I suggest you join the Discord or Matrix if you have 100 questions or suggestions.

**Comment by binwiederhier** [comment]
> I suggest you join the Discord or Matrix if you have 100 questions or suggestions.

That sounded rude. My apologies. I was merely inviting you to join the chat, since it'll make it easier :-D

**Comment by johnlpe** [comment]
> That sounded rude. My apologies. I was merely inviting you to join the chat, since it'll make it easier :-D

It's ok, no worries :) Yup, but I already asked what I had to ask. Please check: https://github.com/binwiederhier/ntfy/issues/808#issuecomment-1620903144 and https://github.com/binwiederhier/ntfy/issues/806#issuecomment-1620906708
