### ISSUE TITLE
Add docker images to github packages.

### ISSUE THREAD

**Issue by tconnard** [binwiederhier/ntfy#818]
:bulb: **Idea**
Add docker images to github packages as well as docker hub
:computer: **Target components**
CI/CD

This would be a help as it is easy to get rate limited by docker hub.

**Comment by binwiederhier** [comment]
As of today, I have no intention or reason to switch from docker hub.

**Comment by JorgeLNJunior** [comment]
You don't need to switch from Docker Hub. You can publish on both registries.
