### ISSUE TITLE
ntfy widget subscription

### ISSUE THREAD

**Issue by mmojadad** [binwiederhier/ntfy#824]
A ntfy widget subscription code builder to provide an injectable ready to use code ( javascript, css ) add to header of any type web applications . visitors in this way can subscribe and receive notifications.

**Comment by binwiederhier** [comment]
I like the idea, but that is very much outside the realm what I as a single person can do. ntfy is pretty easy to integrate into web apps, so I don't think it's necessary. 

Thank you for submitting the idea, but right now I don't think I'll want to do it.
