### ISSUE TITLE
Telegram integration on android 

### ISSUE THREAD

**Issue by dskzero22** [binwiederhier/ntfy#833]
What you guys do is incredible, the integration with Tusky is perfect, and believe me, when you don't have Google services, notifications are a serious problem. Thanks to you, I was able to regain them on Mastodon. I'm also a lover of Telegram and its forks, so I was wondering, is it possible to integrate a Telegram client with Unifiedpush and work with its app? Or at least, could the user do this manually? Greetings.

**Comment by l-x** [comment]
You need to ask this question to the developer of a Telegram app. The fact is that the app developers have to implement UnifiedPush.

**Comment by binwiederhier** [comment]
As l-x said, you have to ask Telegram, not ntfy.
