### ISSUE TITLE
NixOS doesn't find "sh" in $PATH

### ISSUE THREAD

**Issue by gowallasnewpony** [binwiederhier/ntfy#837]
:lady_beetle: **Describe the bug**
NixOS doesn't find "sh" in $PATH:
Command failed: exec: "sh": executable file not found in $PATH

you can see the problem and solution from here:
https://discourse.nixos.org/t/systemd-service-not-executing-bash-script-right/31735/9?u=gemstraam

:computer: **Components impacted**
NixOS system

**Comment by binwiederhier** [comment]
There's some discussion in that thread. I am happy to incorporate any fixes locally, but I am a little lost as to how to fix this. I didn't think that `/bin/sh` would be missing from any unix-y system.

**Comment by binwiederhier** [comment]
Closing this for now. Please feel free to comment and/or submit a PR and I'll reopen.
