### ISSUE TITLE
Topic Pattern *_ matches everything

### ISSUE THREAD

**Issue by Joe-0237** [binwiederhier/ntfy#840]
:lady_beetle: **Describe the bug**
Any ACL Topic Pattern containing only underscores and stars _ * matches all topics: eg.
`_*`, `*_`, `_*_*_`, `__*__`, `_*_`

:computer: **Components impacted**
Server

:crystal_ball: **Additional context**
**To reproduce:** 
with the default permission set to read-write
 as an anonymous user 
deny access to everyone for *_  `ntfy access everyone *_ deny`
attempt to subscribe to `test`

**Comment by binwiederhier** [comment]
I see. Good catch!

**Comment by binwiederhier** [comment]
Hopefully fixed in https://github.com/binwiederhier/ntfy/pull/843

**Comment by Joe-0237** [comment]
`E_*` matches any `E*`
So I guess more generally sections of a patterns containing only `_` and `*` are equivalent to `*`

**Comment by binwiederhier** [comment]
As you saw it uses SQLite's wildcards, so there is not but I can do. 

> I looked at the commit, I'm impressed with the testing, and scared of SQL 

Yeah, ... I was not happy with this complexity-add. I am not loving the wildcard-conversion thingy...
