### ISSUE TITLE
Add Xitoring integration to Docs

### ISSUE THREAD

**Issue by s4m4n** [binwiederhier/ntfy#846]
Hello,

[Xitoring](https://xitoring.com) a provider of Server and Uptime monitoring, has already integrated ntfy as a notification channel integration so that users can get alerts and notifications on ntfy.sh apps. We'd like to get listed on Ntfy integration list [here](https://docs.ntfy.sh/integrations/)

Doc about ntfy and Xitoring integration:
https://xitoring.com/docs/notifications/notification-roles/ntfy/

This issue is created as mentioned on the website: "Feel free to [create a pull request on GitHub](https://github.com/binwiederhier/ntfy/issues) to add your own project here." However, it says to create a pull request, but the link anchor points to the issues page on Github. It needs to be fixed.

Thanks.

**Comment by binwiederhier** [comment]
Done
