### ISSUE TITLE
Restart the ntfy app if closed. 

### ISSUE THREAD

**Issue by riaanp78** [binwiederhier/ntfy#849]
:bulb: **Idea**
if the android ntfy app gets closed by a force full process .e.g memory cleaner then it should restart again so it listens to the topics. Otherwise the app stays closed until manually opened again

:computer: **Target components**
Android

**Comment by binwiederhier** [comment]
When force-closed, Android does not allow automatically reopening the app. The app restarts automatically on device restart and other reasons, but when you force stop, there's nothing we can do.
