### ISSUE TITLE
Add Blender integration to docs

### ISSUE THREAD

**Issue by NotNanook** [binwiederhier/ntfy#857]
Hello there,
im writing this pull request to inform you that i made a Blender Addon that notifies the user if their render has completed. I made this addon because there arent any open source/free addons to do exactly that. Most of them are in one form or the other, paywalled. <br>
Its [on my profile](https://github.com/NotNanook/NtfyMe-Blender) and fully working. As you stated on your website that we can request to be added to the project site which would be pretty cool.
Hope you have great day

**Comment by binwiederhier** [comment]
Done. In the future feel free to create PRs directly.

**Comment by NotNanook** [comment]
Sure thing
