### ISSUE TITLE
Camera function

### ISSUE THREAD

**Issue by do-me** [binwiederhier/ntfy#859]
:bulb: **Idea**

I was wondering why ntfy didn't offer a direct way to take a picture (yet?). It's fairly simple to integrate and would benefit the users as one could avoid going the longer way over file uploads.

It could be beneficial if a user e.g. selected "always open with..." `File Explorer` or similar and hence cannot find the option `Camera` anymore (probably until all cookies, local storage etc. are deleted). I had this situation on one of my Android phones (Android 13).

:computer: **Target components**

Client-side on the web and mobile apps. 

On the mobile apps a native solution would be best but in the web app one could use `getUserMedia()`. I just created such a simple demo with a minimal UI that sends a picture to a ntfy channel. In my case, I needed a cross-platform method to send images from the browser straight to ntfy without leaving my html page: https://do-me.github.io/js-camera-capture/

I think it would be nice to design a UI similar to standard messengers like WhatsApp/Telegram/Signal etc. where the camera icon is just next to the `send` icon. 

![image](https://github.com/binwiederhier/ntfy/assets/47481567/169afc1e-d45b-46b3-b3ea-4cdee2c0d20e)

**Comment by binwiederhier** [comment]
While this is a fascinating idea, I think this falls in the category of "not everything that can be done, must be done". I'm invoking my maintainer right to respectfully reject this idea. Thanks for submitting!
