### ISSUE TITLE
Documentation: Powershell send with token example

### ISSUE THREAD

**Issue by jimholcomb** [binwiederhier/ntfy#869]
In the doc for sending a message via PowerShell and using a token the doc uses this example:

```
# With PowerShell 7 or greater, we can use the Authentication and Token parameters
$Request = @{
  Method = "POST"
  URI = "https://ntfy.example.com/mysecrets"
  Authorization = "Bearer"
  Token = "tk_AgQdq7mVBoFD37zQVN29RhuMzNIz2"
  Body = "Look ma, with auth"
}
Invoke-RestMethod @Request

```
When I run this with my URI and Token I get the error: **"Cannot bind parameter 'Token'. Cannot convert the "tk_AgQdq7mVBoFD37zQVN29RhuMzNIz2" value of type "System.String" to type "System.Security.SecureString"."**

Changing the "Token =" line to below works for me:

`Token = ConvertTo-SecureString -string "tk_AgQdq7mVBoFD37zQVN29RhuMzNIz2" -AsPlainText -Force`

**Comment by jimholcomb** [comment]
Also, Authorization = Bearer should be Authentication = Bearer

**Comment by jimholcomb** [comment]
Per https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-restmethod?view=powershell-7.3 the parameter is Authentication.

Under the description of that parameter it says "Bearer: Requires the Token parameter. Sends an RFC 6750 Authorization: Bearer header with the supplied token." so the parameter is one thing (Authentication) but the header it sends is another (Authorization).

**Comment by binwiederhier** [comment]
@jimholcomb Would you mind creating a PR for this, or providing a fully functioning example?

**Comment by binwiederhier** [comment]
Closed due to inactivity.
