### ISSUE TITLE
Need to refresh app in IOS to see notifications

### ISSUE THREAD

**Issue by g0d1k** [binwiederhier/ntfy#872]
:lady_beetle: **Describe the bug**
 The app worked great at first on iOS but now when I send a notification I need to refresh the screen in the app for it to come through. It will not push. 

:computer: **Components impacted**
 iOS app

:bulb: **Screenshots and/or logs**

:crystal_ball: **Additional context**

**Comment by kkrieger85** [comment]
Could you post your server.yml content? 
e.g.
```
upstream-base-url: "https://ntfy.sh"
#upstream-access-token: "..."
```

**Comment by kWAYTV** [comment]
> 

exactly as you posted now

**Comment by kkrieger85** [comment]
I had two issues first:
1) misspelled my config file folder
2) set token to "..." which is wrong. As it's commented out now, the live update inside ntfy app works for me 

Works for me on 
iPhone 11
ntfy server 2.7

**Comment by binwiederhier** [comment]
Known issue - https://docs.ntfy.sh/known-issues/

Duplicate #267
