### ISSUE TITLE
Exit feature

### ISSUE THREAD

**Issue by KopiasCsaba** [binwiederhier/ntfy#874]
:bulb: **Idea**

Please add a menu entry to exit the app! Thanks!

:computer: **Target components**

**Comment by binwiederhier** [comment]
Android apps don't really have "exit" buttons. Just press the home button.

**Comment by KopiasCsaba** [comment]
But this is a foreground service that can not be easily stopped. Check out google maps or waze navigation when they are on the foreground, they all have an exit button in the notif.
