### ISSUE TITLE
Android: base URL can not be set in settings dialog

### ISSUE THREAD

**Issue by t0bixorg** [binwiederhier/ntfy#878]
Within the Android App (Version see below): when I am trying to set the default base URL in the settings menu, the "ok" option turns grey after entering the first character - and does not come back again, not even after entering the "original" ntfy URL. So there is no chance to set the base initially, the only option is to "abort" ("Abbrechen" in German).

Entering a  dedicated server while consuming a (new) theme directly works, however - so there is no urgency in that to me. I am merely wondering, why I can't set a base URL... 

Here is the log of the App, not Sure uf hat helps:
-------------------------
This is a log of the ntfy Android app. The log shows up to 1,000 entries.

Device info:
--
ntfy: 1.16.0 (play)
OS: 5.4.210-qgki-26213204-abG990B2XXS5EWG9
Android: 13 (SDK 33)
Model: r9q
Product: r9q2xeea

--
Settings:                    
{
  "autoDeleteSeconds": 2592000,
  "autoDownloadMaxSize": 1048576,
  "broadcastEnabled": true,
  "connectionProtocol": "ws",
  "darkMode": -1,
  "defaultBaseUrl": "",
  "lastSharedTopics": [],
  "minPriority": 1,
  "mutedUntil": 0,
  "recordLogs": true
}

Logs
--

1694503313015 2023-09-12 09:21:53.015 D NtfyLog Enabled log recording

**Comment by binwiederhier** [comment]
What are you trying to enter? You have to enter a full URL, e.g. `https://example.com` (without spaces around it)

**Comment by t0bixorg** [comment]
Oh, wow, that's embarrassing.  The server here must be a https, only with http it does not work. Problem solved, thanks :-)

**Comment by binwiederhier** [comment]
Hm. http should also work.

**Comment by t0bixorg** [comment]
![Screenshot_20230912_161157_ntfy](https://github.com/binwiederhier/ntfy/assets/45749266/f50374cd-5d1b-45a5-a22e-af6b219349aa)
