### ISSUE TITLE
Umlauts in tags

### ISSUE THREAD

**Issue by Nollknolle** [binwiederhier/ntfy#879]
:lady_beetle: **Describe the bug**
For the tags, umlauts are displayed as "?".

:computer: **Components impacted**
All services

:bulb: **Screenshots and/or logs**

![image](http://i.nlmyr.de/u/iz9T92.png)

:crystal_ball: **Additional context**

**Comment by binwiederhier** [comment]
There's a blue info box at the bottom of the tags section in the docs that explains how to do special characters in tags when using headers: https://docs.ntfy.sh/publish/#tags-emojis

Or you can use JSON publishing, or pass tags as URL encoded params.

**Comment by Nollknolle** [comment]
Thanks for that quick reply. Can I use auth also in JSON?

**Comment by Nollknolle** [comment]
> There's a blue info box at the bottom of the tags section in the docs that explains how to do special characters in tags when using headers: https://docs.ntfy.sh/publish/#tags-emojis
> 
> Or you can use JSON publishing, or pass tags as URL encoded params.

Thanks for your quik reply.
