### ISSUE TITLE
feature request: unix socket support

### ISSUE THREAD

**Issue by oddlama** [binwiederhier/ntfy#88]
Thanks for the great program! I was wondering whether you could add support for listening solely on a unix socket.
This would be great to run ntfy in proxied mode, as it would make permission management between nginx and ntfy a lot easier, as I'd like to restrict the rest of my system from talking to ntfy.

**Comment by binwiederhier** [comment]
That's likely trivial to add. Great idea.

**Comment by binwiederhier** [comment]
https://github.com/binwiederhier/ntfy/pull/89/files

**Comment by binwiederhier** [comment]
Done; will be in the next server release
