### ISSUE TITLE
Add Total Topics and Total Subscriptions to the `/v1/stats` API

### ISSUE THREAD

**Issue by kevinlutzer** [binwiederhier/ntfy#885]
:bulb: **Idea**
I want to expose the total subscriptions and topics on the /v1/stats API. The data will be consumed by some of the analytics tools I use to manage my Kubernetes cluster, as well as I want to display these metrics on my [Heimdall](https://heimdall.site/) Dashboard 

Looks like the total topics lives on the server struct. Subscriptions would need to be computed in the API based on the `Topic.Stats()` method pointer. 

:computer: **Target components**

ntfy server

**Comment by binwiederhier** [comment]
My apologies for not responding earlier, but I do not thing that this info should be exposed in a public endpoint due to security concerts. It leaks info. I realize that the number of messages is already questionable, but I need that to display the nice counter on the website.

**Comment by kevinlutzer** [comment]
Ahh okay no worries! Ya I thought that if you were comfortable with the total message quantity and message rate metrics being exposed via API that there wouldn't be an issue with showing the total number of topics, subscriptions etc. 

Is there another way it would be possible to expose these metrics? Maybe behind an auth'd API?

**Comment by binwiederhier** [comment]
I could see the stats API returning more stats when queried by an admin user, which should be relatively easy to achieve. Basically return the same stuff that the metrics endpoint would.

**Comment by kevinlutzer** [comment]
Are you referring to this file as the "metrics endpoint" -> https://github.com/binwiederhier/ntfy/blob/main/server/server_metrics.go

**Comment by binwiederhier** [comment]
Yeah, the prometheus endpoint is how you'd usually get metrics. It's pretty awesome.

![image](https://github.com/binwiederhier/ntfy/assets/664597/b2476942-c7eb-4724-859b-3ea955cde28f)
