### ISSUE TITLE
Feature Request: Native Windows App for Desktop

### ISSUE THREAD

**Issue by Pro2Factory** [binwiederhier/ntfy#891]
Chrome App is kinda weird, do you plan to provide a native app / tray-on app for Windows?

**Comment by binwiederhier** [comment]
I do not have any plans to write a native Windows app. I have trouble maintaining the 3-4 apps that ntfy has already :D -- I welcome third-party apps and if it's good enough I'm happy to include it as the recommended option. AFAIK there are a bunch of Windows apps listed here (https://docs.ntfy.sh/integrations/) -- You may want to check them out.
