### ISSUE TITLE
No Auto Polling of NTFY Alerts (Self hosted)

### ISSUE THREAD

**Issue by ArMaTeC** [binwiederhier/ntfy#904]
:lady_beetle: **No Auto Polling of NTFY Alerts**
I am writing to bring to your attention a critical issue we are currently experiencing with the NTFY alert system, specifically related to auto-polling and server configuration.

Currently, the system exhibits persistent challenges with auto-polling NTFY alerts. In socket mode, there is a continuous reconnection issue, while in JSON mode, no automatic notifications are displayed. Manual refresh is required to obtain any updates.

Upon conducting a thorough investigation, I performed a test using ntfy.sh alerts, which functioned seamlessly in the Android application, providing instantaneous updates. This suggests that the problem may be rooted in the server setup.

:computer: **Components impacted**
The affected components include the NTFY server and the Android application.

:bulb: **Screenshots and/or logs**
Attached is a screenshot illustrating the perpetual spinning of the section next to the topic on the self-hosted GUI, indicative of the issue. Please refer to the following link for the image:
<img width="1465" alt="image" src="https://github.com/binwiederhier/ntfy/assets/3974913/63a44644-0827-4763-8dc6-48d79185d153">

We urgently request your assistance in investigating and resolving this matter promptly. Your expertise in addressing this technical challenge is invaluable, and we appreciate your swift attention to this issue.

Should you require any additional information or assistance, please do not hesitate to reach out. Your prompt action on this matter is highly appreciated.

Thank you for your time and assistance.

**Comment by drowolath** [comment]
Hi,
I don't know if you're running NTFY behind a proxy (such as nginx), but in my case, to make the websocket mode work, I had to add the following to my `location /` block:

`proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection "upgrade";
`

Once I did so, there's no more perpetual spinning on the self-hosted GUI, and notifications are instantly shown on my Android device

**Comment by binwiederhier** [comment]
Correct, be sure to enable WebSockets. See https://docs.ntfy.sh/config/#nginxapache2caddy for more detail.
For 1:1 help with your setup, please ask on our Discord or Matrix chat.
