### ISSUE TITLE
Push notification on pixel

### ISSUE THREAD

**Issue by 2055619** [binwiederhier/ntfy#909]
:lady_beetle: **Describe the bug**
I tryied to push notification message on my pixel 7 pro, but it did not go off I need to refrwsh manualy in the app to get my notification.

:computer: **Components impacted**
Android app on pixel

:bulb: **Screenshots and/or logs**
None 

:crystal_ball: **Additional context**
Yestoday I created my ntfy server localy an then I hosted it. I pushed via postman post command a simple message. I received it with the notification instantly on the web page (even in another network) but I received nothing on my pixel 7 pro. I refresh my subscriptions and the notification + message pop up. Maybe it's not this app but the extra protection on pixels that does that. Maybe its a google problem. Idk

**Comment by wunter8** [comment]
Self-hosted ntfy is working just fine on my Pixel 7, so it should be working okay for you, too. It seems like there's an issue with your server config somewhere. I'm happy to help here, but chatting on discord/matrix might be a bit easier (links at the top of this page: https://docs.ntfy.sh/troubleshooting/)

**Comment by 2055619** [comment]
Yes I think I found the problem. It's the connection to my server probably the network
