### ISSUE TITLE
Max/High priority notifications should be able to override DND

### ISSUE THREAD

**Issue by binwiederhier** [binwiederhier/ntfy#91]
https://stackoverflow.com/questions/31862753/android-how-to-turn-on-do-not-disturb-dnd-programmatically

**Comment by 12nick12** [comment]
I second this. This would be awesome.

**Comment by binwiederhier** [comment]
I am dabbling with this now. I'm able to turn DND off/on globally, but I don't really want to do that. I just want to decide which notification make a sound, and which ones don't.

**Comment by binwiederhier** [comment]
This is quite fascinating but also interesting. 

For each of the 5 priorities, I create an Android `NotificationChannel`, for which I can set `setBypassDnd` flag. However, I can only set that if I have a certain permission, for which the user has to manually toggle a setting in the Android UI. That wouldn't be a problem, except that a `NotificationChannel`, once created, ~cannot be updated~ ...............

[Rubber ducking works](https://en.wikipedia.org/wiki/Rubber_duck_debugging), even when typing it out :duck: :duck: :duck: 

Looks like channels can be updated and when the permission to edit DND has been granted, setting `setBypassDnd` after the fact on an existing channel works.

I think I can work with this :partying_face:

**Comment by binwiederhier** [comment]
![220414 13-01-08 Selection 001](https://user-images.githubusercontent.com/664597/163437989-9865514e-e68e-41cd-bc8d-cd79b010de2a.png)

Fixed with this^^, but I'll add some documentation too, so I'll leave it open until then.

**Comment by binwiederhier** [comment]
Added docs for this: https://github.com/binwiederhier/ntfy/commit/06fd7327de5db7a6df4aa95ee762221c063ac77b
