### ISSUE TITLE
"Private instance" and ACL

### ISSUE THREAD

**Issue by sandman7920** [binwiederhier/ntfy#914]
:lady_beetle: **Describe the bug**
If we have `auth-default-access: "deny-all"` and ACL for user `test test* rw`  and `test * ro`
 It seems like the `read-only access to topic * permission` is being applied before the read-write `access to topic test*`

:computer: **Components impacted**
ACL publish API

:bulb: **Screenshots and/or logs**
![image](https://github.com/binwiederhier/ntfy/assets/3589417/d1b997d2-6308-4691-817b-835211918276)

:crystal_ball: **Additional context**
![image](https://github.com/binwiederhier/ntfy/assets/3589417/20aad2d7-e042-4bd1-835c-f09def2ac225)

**Comment by binwiederhier** [comment]
Fixed in #917. Thank you!
