### ISSUE TITLE
E-mail publishing, attachment limited to 4ko file size

### ISSUE THREAD

**Issue by adamaen87** [binwiederhier/ntfy#918]
:lady_beetle: **Describe the bug**

I'm using E-mail publishing (local only email) to send notifications from differents docker services in OpenMediaVault. The smtp server is configured with ntfy. Everything works with no problem except one bug. I have a snapraid script (snapraid-aio-script on github) configured as a scheduled task (cron) and send the output via email to ntfy. The message is more than 4k so the notification is send with an attachment as intended. But for some reason the file is always limited to 4ko size and is truncated.
:computer: **Components impacted**

ntfy server, Android app
:bulb: **Screenshots and/or logs**

:crystal_ball: **Additional context**

**Comment by binwiederhier** [comment]
The ntfy message limit is 4k for various reasons. There is a ticket around increasing it (https://github.com/binwiederhier/ntfy/pull/836), but the consequences of doing that is not known. I'll likely merge this soon, but expose the option at your own risk.

So for all intents and purposes, this is a dup of #836
