### ISSUE TITLE
Batch low priority notifs with the keepalive message

### ISSUE THREAD

**Issue by MatMaul** [binwiederhier/ntfy#92]
This should probably be exposed in the HTTP API, something like `max_priority_batch_ka`, that would allow an user to specify a priority under which the notifs will be bundled with the keep-alive packet.

My param name is bad but I can't find something meaningful and short.

Related to #76 .

**Comment by binwiederhier** [comment]
I don't hate the idea, but the question is if it's worth the effort.

**Comment by MatMaul** [comment]
Yeah probably complicated for low gains. Let's close this, the idea is tracked if we want to revisit :)
