### ISSUE TITLE
Add Github wiki

### ISSUE THREAD

**Issue by bonelifer** [binwiederhier/ntfy#920]
As a docker compose user, I think it'd be nice to have the info from this issue in a  wiki article for people to see more widely. One less question for Discord: https://github.com/binwiederhier/ntfy/issues/865#issuecomment-1707146928

**Comment by wunter8** [comment]
I agree, yes. I just haven't had time yet to update the docs. So I just keep answering the same question on discord over and over...

**Comment by binwiederhier** [comment]
I don't really want to have yet another place to add docs. I think we should have a dedicated section about Docker in the Docs.

**Comment by wunter8** [comment]
I misunderstood the request. My intent was not to create a GitHub wiki but just to add more Docker info into the existing docs
