### ISSUE TITLE
Documentation Enhancement: Add docker compose info from following issue

### ISSUE THREAD

**Issue by bonelifer** [binwiederhier/ntfy#923]
As a docker compose user, I think it'd be nice to have the info from this issue detailed the documentation for people to see more widely. One less question for Discord: https://github.com/binwiederhier/ntfy/issues/865#issuecomment-1707146928

New issued to change from adding Github wiki to instead adding it to the documentation.
closed original issue: https://github.com/binwiederhier/ntfy/issues/920

**Comment by binwiederhier** [comment]
Done in https://docs.ntfy.sh/config/#example-config. Thanks for reporting.
