### ISSUE TITLE
Any possibility of reading a topic via ntfy cli from the past?

### ISSUE THREAD

**Issue by RDKRACZ** [binwiederhier/ntfy#925]
Both Android and web app allow for reading notifications sent BEFORE subscribing to the topic. This doesn't seem to be the case for the Linux app.

**Comment by wunter8** [comment]
Are you talking about the `ntfy sub` CLI tool? If so, use the `since` flag. For example, you can do `ntfy sub --since all topic` to get the messages in the cache for that topic. The shorthand `ntfy sub -s all topic` also works. See `ntfy sub help` for more info

**Comment by RDKRACZ** [comment]
Yes, -s all did the trick, thanks. The next problem appears - is there any way to convert the unix timestamp into a human-readable time format without using external tools?
I suggest making it print both unix and regular time.

**Comment by wunter8** [comment]
Not right now, no. You could use `jq` to parse the JSON and change the value, but I recognize that's an external tool

**Comment by RDKRACZ** [comment]
Ok, at least jq seems to be installed by default on my OS.
For anyone wondering, the command I used is `ntfy sub -s all topic_name | jq '.time |= strflocaltime("%Y-%m-%d %H:%M:%S")' `
