### ISSUE TITLE
Instabilities with Megalodon

### ISSUE THREAD

**Issue by d4f5409d** [binwiederhier/ntfy#935]
:lady_beetle: **Describe the bug**

Sometimes I get the notifications and sometimes I don't. Apparently when I refresh the channels, ntfy shows there are two new notifications, but I don't get to see it as a notification.

:computer: **Components impacted**

Android app (default everything, including default server)

:bulb: **Screenshots and/or logs**

Will do sooner

:crystal_ball: **Additional context**

One time I achieved to get it working somehow, but I had to be in Megalodon and I had to enable the persistent notification.
I have battery optimization disabled, background activity enabled, and I have a stock OxygenOS 13.1, OnePlus 8 device

**Comment by d4f5409d** [comment]
It seems like to only work when Megalodon is opened.

**Comment by p1gp1g** [comment]
This is not related to ntfy. There is a NullPointerException in megalodon (cf. https://github.com/sk22/megalodon/pull/914)

**Comment by d4f5409d** [comment]
Shall I close the issue as not planned?

**Comment by p1gp1g** [comment]
You should probably (as not *related* :) )
