### ISSUE TITLE
Using PHP example from doc for publishing JSON notification sends JSON object and is not interpreted by the server

### ISSUE THREAD

**Issue by godsgood33** [binwiederhier/ntfy#942]
:lady_beetle: **Describe the bug**
I am converting my notifier from PushBullet to a self-hosted Ntfy instance.  It work great and the messages come through just like you think they should.  However, the notification received is just the JSON object and not an interpreted display.  Maybe I am doing something wrong.

:computer: **Components impacted**
all

:bulb: **Screenshots and/or logs**
Code I wrote to send the message using the example in the doc:
```php
$auth = base64_encode($_SERVER['NTFY_USERNAME'].':'.$_SERVER['NTFY_PASSWORD']);
file_get_contents(
      filename: "{$_SERVER['NTFY_BASE_URL']}/{$message->topic}",
      context: stream_context_create([
           'http' => [
               'method' => 'POST',
               'header' =>
                   "Content-Type: application/json\r\n" .
                   "Title: {$message->title}\r\n" .
                   "Authorization: Basic {$auth}",
               'content' => json_encode($message)
           ]
      ])
);
```

This is what the notification looks from the web app
![image](https://github.com/binwiederhier/ntfy/assets/1922710/d0b37d26-6ec9-4dc5-893c-42a7576f9252)

:crystal_ball: **Additional context**
I tried looking at the symfony/ntfy-notifier, but I am currently using Symfony 5.4 and that requires at least 6.4 and symfony/notifier 6.2

**Comment by wunter8** [comment]
Messages with JSON bodies need to be sent to `ntfy.domain.com` and not `ntfy.domain.com/topic`

**Comment by godsgood33** [comment]
> Messages with JSON bodies need to be sent to `ntfy.domain.com` and not `ntfy.domain.com/topic`

That didn't work.  I got a 400 error.  With and without the trailing '/'.

```
PHP Warning:  file_get_contents(https://notify.domain.com/): Failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request
```

**Comment by wunter8** [comment]
I'm guessing your JSON is malformed. Specifically, `markdown` has to be a bool, not '1', so change your PHP message array to `... ,'message' => true, ...`

**Comment by godsgood33** [comment]
That seemed to work.  Turns out the problem was in the `__set` method...it accidentally put `string` for the second parameter which cast the `true` to a string `1`.  Thanks!
