### ISSUE TITLE
Custom Sound/Ringtone

### ISSUE THREAD

**Issue by tanpoop** [binwiederhier/ntfy#950]
Like Bark provides 30+ sounds

**Comment by binwiederhier** [comment]
Please provide more context (e.g. by using the GitHub issue template.), and/or search for other open issues. If this is about Android, you can pick whatever sound you like. If this is about iOS, I'm sure there is a ticket already.

**Comment by mrdnote** [comment]
On newer Samsung models (e.g. Galaxy S25) you cannot pick custom sounds. They have hidden that option from their UI for some reason. For these phones it would be great if you could pick your own sound within ntfy.
