### ISSUE TITLE
GO Client  library v1 broken?

### ISSUE THREAD

**Issue by larscom** [binwiederhier/ntfy#952]
:lady_beetle: **Describe the bug**
`go get heckel.io/ntfy@v1.31.0 ` doesn't seem to work anymore

:computer: **Components impacted**
GO client library

:bulb: **Screenshots and/or logs**
`go: heckel.io/ntfy@v1.31.0: unrecognized import path "heckel.io/ntfy": parse https://heckel.io/ntfy?go-get=1: no go-import meta tags (meta tag heckel.io/ntfy/v2 did not match import path heckel.io/ntfy)`

:crystal_ball: **Additional context**
I've tried to find a v2 version but can't seem to find one.

**Comment by binwiederhier** [comment]
I'm sorry. There was another ticket around naming it /v2 and I tried to get that to work, but now both are broken. Any hits as to how to fix this are appreciated.

**Comment by binwiederhier** [comment]
My guess is that I have to publish a v2 with the new import pat, which I just did. So I hope it'll be resolved later. But idk.

**Comment by larscom** [comment]
Your paths seem fine, you didnt make a git tag yet for v2+ which is the problem i think.

**Comment by larscom** [comment]
> My guess is that I have to publish a v2 with the new import pat, which I just did. So I hope it'll be resolved later. But idk.

i think this will solve the problem yes.

**Comment by binwiederhier** [comment]
It did in fact not solve the problem. Here's what fixed it:

Old module (v1, at https://heckel.io/ntfy):
```
heckel.io/ntfy# cat index.html 
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<meta name="go-import" content="heckel.io/ntfy git https://github.com/binwiederhier/ntfy">
<meta name="go-source" content="heckel.io/ntfy https://github.com/binwiederhier/ntfy https://github.com/binwiederhier/ntfy/tree/master{/dir} https://github.com/binwiederhier/ntfy/blob/master{/dir}/{file}#L{line}">
<meta http-equiv="refresh" content="0; url=https://github.com/binwiederhier/ntfy">
</head>
<body>
<b>ntfy</b>, redirecting to <a href="https://github.com/binwiederhier/ntfy">GitHub</a> ...
</body>
</html>
```

New module (v2, https://heckel.io/ntfy/v2):
```
hecke.io/ntfy/v2# cat index.html 
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<meta name="go-import" content="heckel.io/ntfy/v2 git https://github.com/binwiederhier/ntfy">
<meta name="go-source" content="heckel.io/ntfy/v2 https://github.com/binwiederhier/ntfy https://github.com/binwiederhier/ntfy/tree/main{/dir} https://github.com/binwiederhier/ntfy/blob/main{/dir}/{file}#L{line}">
<meta http-equiv="refresh" content="0; url=https://github.com/binwiederhier/ntfy">
</head>
<body>
<b>ntfy</b>, redirecting to <a href="https://github.com/binwiederhier/ntfy">GitHub</a> ...
</body>
</html>
```

The `-x` flag and the `GONOPROXY` env variable also helped:
```
GONOPROXY='heckel.io/*' go get -u -x heckel.io/ntfy/v2
```

Curious: What are you using the lib for? I make no guarantees for the use as a Go lib. The client lib in particular is very rudimentary.

**Comment by larscom** [comment]
I use it in my go (private) apps, just to send notifications. I could make it myself but its nice to have something that is already ready to use ;)
