### ISSUE TITLE
Android App - Push notifications not working (Have to refresh to get messages)

### ISSUE THREAD

**Issue by Ciaran97** [binwiederhier/ntfy#955]
:lady_beetle: **Describe the bug**
I selfhost NTFY and i am not receiving notifications on Android apps. Works perfect with IOS. I can get the notification when i open the ntfy app and refresh

:computer: **Components impacted**
Android App

I am probably missing something. 

I have ntfy running in a docker container behind an nginx reverse proxy and use cloudflare tunnels to expose using my domain. 

EDIT: 
Also i changed the port of the docker container

**Comment by kron0800** [comment]
same here, using local ip works like a charm, but if i set my cloudflared tunnel as server, no notifications received unless i refresh

**Comment by Ciaran97** [comment]
> same here, using local ip works like a charm, but if i set my cloudflared tunnel as server, no notifications received unless i refresh

@kron0800 Are you also using a proxy?

**Comment by emigrating** [comment]
You guys dont happen to havea bunch of defunct ssl client ps entries do you? I ran into a similar issue (#956) which could explain why I was still getting notifications even though the web ui seemed 'dead'. As my outgoing notifications were going from the internat LAN using an apprise instance..

**Comment by Ciaran97** [comment]
> You guys dont happen to havea bunch of defunct ssl client ps entries do you? I ran into a similar issue (#956) which could explain why I was still getting notifications even though the web ui seemed 'dead'. As my outgoing notifications were going from the internat LAN using an apprise instance..

@emigrating i dont seems to have that issue. My web UI loads fine (although i notice a spinner next to my topic and android app always says 'reconnecting' to topic but i can send notifications from both).

**Comment by binwiederhier** [comment]
Please provide logs and/or screenshots. Without that, it's impossible to help.

That said, if it always says "reconnecting", that means you've never really connected to the ntfy server at all. Your Android and ntfy server logs will tell the story.

Debugging steps:
- **ntfy server:** You can turn on debugging/tracing by setting `log-level: debug` or `log-level: trace` in the server.yml file. See https://docs.ntfy.sh/config/#logging-debugging for details.
- **Android app:** To retrieve the logs from the Android app, go to "Settings" -> "Record logs", then eventually "Copy/upload logs".
- **Web app:** To view the web app logs, press "F12" and find the "Console" window.

You can find details in the troubleshooting guide: https://docs.ntfy.sh/troubleshooting/

**Comment by Ciaran97** [comment]
I have solved this. I made the assumption that because i am using a reverse proxy i did not need the port in my cloudflare tunnel. 

i just added the port of my ntfy service in the local ip address of the cloudflare tunnel and i resubscribed to the topic and it worked. @kron0800 i hope the above helps you.

**Comment by B0F1B0** [comment]
I had the same problem of not getting push notifications on Android. Yes, I am behind a nginx proxy manager. 

I was able to solve the problem. 

on Android: Settings > Connection protocol > WebSockets
on nginx proxy manager > edit proxy host > Websockets Support [x]

**Comment by JZach** [comment]
@B0F1B0 - had the exact same setup and the exact same problem - Websockets Support did the trick!

**Comment by Ativerc** [comment]
For people who doing this via the `nginx.conf` file. 

```
server {
		listen 80;
		server_name local-lan-machine.internal;

		location / {
			...
		}
		
	}
	server {
		listen 80;
		server_name ntfy.local-lan-machine.internal;
		location / { 
                        # This is the part for enabling websockets
			proxy_pass http://localhost:8080;  # set to the port that ntfy is listening on
			proxy_http_version 1.1;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "upgrade";
			proxy_read_timeout 86400; # I set this to 86400 because some people faced issues, so I set it this to be safer. 
		}
	}
}
```

Resources: 

https://stackoverflow.com/a/14969925
https://nginx.org/en/docs/http/websocket.html

**Comment by wedsa5** [comment]
For those using Caddy reverse proxy, you can use this configuration to enable websocket:
```
ntfy.example.com {
	# Websockets, if headers match
	@ws {
		header Connection *Upgrade*
		header Upgrade websocket
	}
	reverse_proxy :<your ntfy port>
}

**Comment by wedsa5** [comment]
> You don't need the whole `@ws` block for Caddy
> 
> Websockets work with just `reverse_proxy :<ntfy port>` on Caddy

I was getting the reconnecting issue without it. unless there was some other issue going on. but adding that block immediately fixed it for me.

**Comment by wunter8** [comment]
It must've been something else.

According to the Caddy docs, websocket proxying "just works" in v2 (the current version). You don't need to do anything to enable it. That has also been my experience.

And if I'm remembering what that block syntax means, you're matching requests that have a Connection and Upgrade header, but you never do anything for those requests. To do something special with those requests, you'd need to use this syntax: `reverse_proxy @ws IP:port` (with the name of that block (`@ws`) before the IP and port)

**Comment by wedsa5** [comment]
You're right. i disabled it again and it's working ok for now. updated my comment.
