### ISSUE TITLE
Phone Numbers Not Clickable for Direct Calling in NTFY App in message

### ISSUE THREAD

**Issue by XylenSky** [binwiederhier/ntfy#957]
:bulb: **Idea**
Phone numbers in messages are not recognized as clickable links in the NTFY app. Users are unable to directly tap on phone numbers to initiate calls. This inconvenience affects the user experience by requiring manual copy-pasting of numbers into the dialer.

:computer: **Target components**
Phone numbers within messages should be formatted as clickable links. Tapping on these links should initiate phone calls directly from the NTFY app.

**Comment by Den41k92** [comment]
Can this be a configurable feature? Currently, it treats every numeric part in the message as if it was a phone number, even if it's only part of a string, and any string with an @ symbol as an email link
