### ISSUE TITLE
Upgrade to 2.8: service can't start, "attempt to write a readonly database"

### ISSUE THREAD

**Issue by maxhac03** [binwiederhier/ntfy#959]
:lady_beetle: **Describe the bug**
Upgrade from 2.7 to 2.8 with "apt upgrade ntfy" break the service.

:computer: **Components impacted**
Ubuntu 22.04.3
VM dedicated to NTFY.

:bulb: **Screenshots and/or logs**
{"time":"2023-11-24T03:08:01.973Z","level":"INFO","message":"Migrating user database schema: from 4 to 5","tag":"user_manager"}
{"time":"2023-11-24T03:08:01.973Z","level":"FATAL","message":"attempt to write a readonly database","exit_code":1}
{"time":"2023-11-24T03:08:02.304Z","level":"INFO","message":"Migrating user database schema: from 4 to 5","tag":"user_manager"}
{"time":"2023-11-24T03:08:02.306Z","level":"FATAL","message":"attempt to write a readonly database","exit_code":1}
{"time":"2023-11-24T03:08:02.549Z","level":"INFO","message":"Migrating user database schema: from 4 to 5","tag":"user_manager"}
{"time":"2023-11-24T03:08:02.549Z","level":"FATAL","message":"attempt to write a readonly database","exit_code":1}
{"time":"2023-11-24T03:08:02.823Z","level":"INFO","message":"Migrating user database schema: from 4 to 5","tag":"user_manager"}
{"time":"2023-11-24T03:08:02.823Z","level":"FATAL","message":"attempt to write a readonly database","exit_code":1}
{"time":"2023-11-24T03:08:03.055Z","level":"INFO","message":"Migrating user database schema: from 4 to 5","tag":"user_manager"}
{"time":"2023-11-24T03:08:03.055Z","level":"FATAL","message":"attempt to write a readonly database","exit_code":1}

:crystal_ball: **Additional context**
[ntfy_comandline.txt](https://github.com/binwiederhier/ntfy/files/13454795/ntfy_comandline.txt)

**Comment by binwiederhier** [comment]
That sounds like a permission issue to me: https://matthewsetter.com/sqlite-attempt-to-write-to-readonly-database/

Did you ever change the user database permissions? They should be `ntfy:ntfy` if you're running systemd, similar to this:

```
root@ntfy:~# ll /var/lib/ntfy/user.db
-rw-r--r-- 1 ntfy ntfy 1912832 Nov 24 11:43 /var/lib/ntfy/user.db
```

**Comment by maxhac03** [comment]
-rw-r--r-- 1 root root 77824 Aug 31 14:33 /var/lib/ntfy/user.db

This was indeed the issue. After fixing the permission the upgrade worked.

Thanks!
