### ISSUE TITLE
DefaultMessageLimit configurable?

### ISSUE THREAD

**Issue by mexxBf** [binwiederhier/ntfy#960]
"Hi,

I'm trying to forward messages from Gotify and it's working well, but I'm running into a problem with the message size limit. I saw it's 4096, but, for example, the messages from Proxmox are, or at least can be, much bigger. I searched and found default values that are set, but no way to configure them afterwards. Am I missing something, or do I have a chance to get the whole report? :) 

Best regards

**Comment by binwiederhier** [comment]
Dup of #77, resolved in #836 (not merged yet)
