### ISSUE TITLE
Accentuated chars in the title header aren't supported

### ISSUE THREAD

**Issue by jmnicolas90** [binwiederhier/ntfy#977]
:lady_beetle: **Describe the bug**

If I url encode accents (like é ç à è) in the title header they won't be rendered in the app.

Example: title "accentué" will look like "accentu%C3%A9" in the Android and web app.

:computer: **Components impacted**
Android and web app, probably iOS too but I don't have a device.

:bulb: **Screenshots and/or logs**
![Screenshot_20231210_183600](https://github.com/binwiederhier/ntfy/assets/68194446/787440ea-8ba2-4c98-a257-03e4dcc58c7d)

:crystal_ball: **Additional context**
It's not major, just a nice to have.
Thanks for the app, it's great!

**Comment by binwiederhier** [comment]
ntfy supports utf-8 in headers. It's likely your library or language or OS or config not supporting it. 

Please note that you can encode the headers with RFC 2047 if you don't get it to work and that'll always work. Or you can pass it via query param. 

See the blue info box here https://docs.ntfy.sh/publish/#list-of-all-parameters as well as which query param to use if you choose to use that. 

Feel free to drop by discord or matrix to ask for more help.
