### ISSUE TITLE
apprise support

### ISSUE THREAD

**Issue by binwiederhier** [binwiederhier/ntfy#99]
https://github.com/caronc/apprise

**Comment by onedr0p** [comment]
Apprise is specifically Python, I think you want the Go equivalent:

https://github.com/containrrr/shoutrrr

**Comment by bt90** [comment]
Not really. Apprise is used by a lot of projects. This would add ntfy support to HomeAssistant, changedetection, uptime-kuma, bazaar, radaar, nzbget and a few other projects.

see https://github.com/caronc/apprise/wiki/showcase#integrations

**Comment by onedr0p** [comment]
What I meant to say is, apprise is a Python library and works best integrated into apps that are written in Python.

Let's take Uptime Kuma as an example,

```js
let s = child_process.spawnSync("apprise", [ "-vv", "-b", msg, notification.appriseURL])
```

This is pretty bad practice IMO, you do not want to have you application depend on calling an external app like this. I suggested shoutrrr because it's the closest thing to a apprise library in Go.

**Comment by bt90** [comment]
This ticket is about *upstream* apprise support. e.g using ntfy as a notification backend in uptime kuma.

**Comment by onedr0p** [comment]
Wouldn't that issue have to be opened in the apprise repo to support nfty?

**Comment by bt90** [comment]
I think @binwiederhier is free to handle this as he pleases.

**Comment by binwiederhier** [comment]
I added a ticket in the apprise issue tracker (https://github.com/caronc/apprise/issues/520). I can probably do it myself, but it'll take me much much longer than if the maintainer does it.

**Comment by caronc** [comment]
> I added a ticket in the apprise issue tracker (caronc/apprise#520). I can probably do it myself, but it'll take me much much longer than if the maintainer does it. Let's see what they say.

I'll just comment right in here; i love it.  The only problem is that my full time job sucks a lot of my time these days.  But I'll do my best.  In the meantime, if you do feel eager enough to try the PR yourself, go for it.  I've documented a quick how-to-build an plugin.  Even if you can get one barely working, i'll be able to muster enough strength to cover unit tests around it and complete the MR for you if you get stuck.

But if you meet me half way here, you'll see the integration much, much faster! :heart: .

Thanks for showing interest in Apprise!

**Comment by binwiederhier** [comment]
Thanks for the kind words. I love apprise too. Multiple people have shown interest and actually, my co-worker, @particledecay, is actually already working on the integration/plugin. And now that I tagged you Joey you have to deliver :-)))

**Comment by binwiederhier** [comment]
WIP PR https://github.com/caronc/apprise/pull/524

**Comment by binwiederhier** [comment]
Any news, @particledecay? :grimacing: :heart:

**Comment by particledecay** [comment]
Out of town this weekend, but close. Was stepping through some of the plugin loading code to figure out why it wasn't detecting, but pretty sure I figured it out.

**Comment by particledecay** [comment]
@caronc hey calling out for some help if possible. I've got the notifications working, and I'm trying to support priority at the moment but I couldn't find the answer in the plugin doc. Also didn't see priority in the other docs. A plugin reference would be super helpful in this case, but I'll take a quick answer if you have one!

**Comment by binwiederhier** [comment]
@particledecay Do you need any help from me? If you can't find the time to finish I can probably take over. No worries :D

**Comment by binwiederhier** [comment]
This has been merged to master in Apprise and will likely be released in the next Apprise release.

**Comment by otbutz** [comment]
> Apprise is specifically Python, I think you want the Go equivalent:
> 
> https://github.com/containrrr/shoutrrr

https://github.com/containrrr/shoutrrr/pull/308

A bit offtopic, but shoutrrr support is being worked on, it seems.
